### ISSUE TITLE
Lightbulb Not Responding

### ISSUE THREAD

**Issue by AndrewJ1990** [iRayanKhan/homebridge-tuya#101]
Using this lightbulb https://www.kmart.com.au/product/mirabella-genio-wi-fi-dimmable-5.5w-led-candle-bulb/2746326 

Shows up and works in the grid connect app (what I'm using to get the Tuya ID & Key) however cannot get to work in homebridge. Just doesn't respond. Schema below... Not sure if I need to change any default values, using the "twlight" device.

Thanks in advance!

{
    name: 'Lounge Lamp',
    id: '55404001c44f33b2ba8c',
    key: 'c4cc365fed72f9f0',
    def: {
      schema: '[{"mode":"rw","code":"switch_led","name":"\\u5f00\\u5173","property":{"type":"bool"},"iconname":"icon-dp_power2","id":20,"type":"obj","desc":""},{"mode":"rw","code":"work_mode","name":"\\u6a21\\u5f0f","property":{"range":["white","colour","scene","music"],"type":"enum"},"iconname":"icon-dp_list","id":21,"type":"obj","desc":""},{"mode":"rw","code":"bright_value","name":"\\u4eae\\u5ea6\\u503c","property":{"unit":"","min":10,"max":1000,"scale":0,"step":1,"type":"value"},"iconname":"icon-dp_sun","id":22,"type":"obj","desc":""},{"mode":"rw","code":"temp_value","name":"\\u51b7\\u6696\\u503c","property":{"unit":"","min":0,"max":1000,"scale":0,"step":1,"type":"value"},"iconname":"icon-dp_half","id":23,"type":"obj","desc":""},{"mode":"rw","code":"scene_data","name":"\\u573a\\u666f","property":{"type":"string","maxlen":255},"iconname":"icon-dp_box2","id":25,"type":"obj","desc":""},{"mode":"rw","code":"countdown","name":"\\u5012\\u8ba1\\u65f6\\u5269\\u4f59\\u65f6\\u95f4","property":{"unit":"","min":0,"max":86400,"scale":0,"step":1,"type":"value"},"iconname":"icon-timer1","id":26,"type":"obj","desc":""},{"mode":"wr","code":"control_data","name":"\\u8c03\\u8282","property":{"type":"string","maxlen":255},"iconname":"icon-setting","id":28,"type":"obj","desc":""}]',
      extras: '[{"complexType":"","id":20,"inputStyle":"","inputType":"plain"},{"complexType":"","id":21,"inputStyle":"","inputType":" "},{"complexType":"","id":22,"inputStyle":"","inputType":"plain"},{"complexType":"","id":23,"inputStyle":"","inputType":"plain"},{"complexType":"","id":26,"inputStyle":"","inputType":" "}]',
    },

**Comment by iRayanKhan** [comment]
Can you please paste your config?

**Comment by AndrewJ1990** [comment]
Just this part? All the whole thing 


            "platform": "TuyaLan",
            "devices": [
{
                    "name": "Lounge Lamp",
                    "type": "TWLight",
                    "manufacturer": "Genio",
                    "model": "Smart Candle Bulb",
                    "id": "55404001c44f33b2ba8c",
                    "key": "c4cc365fed72f9f0",
                    "dpPower": 1,
                    "dpBrightness": 22,
                    "dpColorTemperature": 23,
                    "minWhiteColor": 140,
                    "maxWhiteColor": 400
                }
            ]

**Comment by AndrewJ1990** [comment]
{
    "bridge": {
        "name": "Homebridge 3B93",
        "username": "0E:32:E2:67:3B:90",
        "port": 51412,
        "pin": "225-56-434"
    },
    "platforms": [
        {
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "Lounge Lamp",
                    "type": "TWLight",
                    "manufacturer": "Genio",
                    "model": "Smart Candle Bulb",
                    "id": "55404001c44f33b2ba8c",
                    "key": "c4cc365fed72f9f0",
                    "dpPower": 1,
                    "dpBrightness": 22,
                    "dpColorTemperature": 23,
                    "minWhiteColor": 140,
                    "maxWhiteColor": 400
                }
            ]
        }
    ]
}

**Comment by peterluu** [comment]
I don't know if the OP is still experiencing problems, but a few things I can help with (I think). Try the following settings:

- Replace `"dpPower": 1` with `"dpPower": 20`
- Replace `"minWhiteColor": 140` with `"minWhiteColor": 0`
- Replace `"maxWhiteColor": 400` with `"maxWhiteColor": 1000"`

At this stage, there's no supporting documentation for features such as scenes or timers (that I can see).

**Comment by ElphaX** [comment]
Thanks @peterluu 
Yes documentation coming soon in the next update, but the above values in your config should fix the issue.
