### ISSUE TITLE
SimpleBlinds2 not present when i install the package. its still pointing to version 1.0.0 from @codetheweb

### ISSUE THREAD

**Issue by rcrdcst** [iRayanKhan/homebridge-tuya#102]
**Checklist**
- [x ] I have read the common issues wiki page
- [x ] I have checked to make sure the plugin is up to date

i installed this plugin today, and when i was configuring my new teeka blinds they didnt work. i have a first generation and they work well.
I digged a bit into the code and i saw that you have a new type **SimpleBlinds2**, for this new blinds. However if i go into my modules folder i dont have this file. I noticed that downloading via npm the version that i get is without the SimpleBlinds2Accessory and its from @codetheweb repo. 

can you help me with this @iRayanKhan ?

Btw keep the good work :)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: 
-  iOS version:
-  Homehubs: 
 - Node Version: 
 - Plugin Version:
-  Accessory Type

**Additional context**

**Comment by iRayanKhan** [comment]
Hey, Are you able to try the RC beta branch? It should have this issue fixed. I will see if that branch contains it, if not I'll publish a beta for it.

**Comment by iRayanKhan** [comment]
Closed: Stale.
