### ISSUE TITLE
Get ID / Key

### ISSUE THREAD

**Issue by Baeda73** [iRayanKhan/homebridge-tuya#105]
Hi All,

I know this might not be a bug, but just a question. Nevertheless, any help is appreciated.

I just bought a pair of Tuya sockets and freshly installed all available applications from the iOS App store. 

I tried to obtain the ID/Key via the MITM approach described here (certificate, proxy on wifi), but with no success. 
(iOS software complain about network issue, various SSL errors from tuya-lan find)
Also tried the firmware patch approach etc.

Am I right, that right now, no working procedure with updated software exists to obtain the ID/Key pair ?

Best,

Peter

**Comment by iRayanKhan** [comment]
Hey there, please add your device to the “Grid Connect” app, then use the MITM approach. It should be working. I am working to implement a updated way to get this working in a better way.

**Comment by Baeda73** [comment]
I tried with current "Grid Connect", but with no success. "Grid connect complains" about "Network Connection Error, Please Check Network", but nothing happens on the proxy side. "Intercepted certificate request is the last line." 
Looking forward to your updated way.

**Comment by spadival** [comment]
Check if you can get Kogan Smarter Life app on the App store. I have been able to get the id/key using Anyproxy

**Comment by Baeda73** [comment]
It works with Kogan Smarter Home and most properly also with Grid connect. It was my fault in general, had an issue with the certificate.

**Comment by Hochiss** [comment]
Sorry try to reopen this... but what's the diff. ID vs. KEY? via the app "_Kogan Smarter Home_" or "_smart life_", in device information I can only get virtual ID: xxxx, but where is KEY? which is needed in config.json.
