### ISSUE TITLE
Simple Dimmer Percentages Are Extremely Different Between Branded Apps and Apple Home App

### ISSUE THREAD

**Issue by jhopper28** [iRayanKhan/homebridge-tuya#107]
**Describe the bug**
The full range of dimming is available in the various apps branded for the simple dimmer product, but the dimmer values in Apple Home app via Homebridge are extremely different, making it nearly useless. The device I'm using is the WTESKE brand outdoor dimming outlet, and I've used it with Tuya, UComen and GridConnect. They all dim predictably from off to 100%. I've properly calibrated the minimum dimming threshold (at about 23%), and I've tried setting this back to 0 and values above the 23%, as well, with no observable difference in behavior. I have correctly selected the LED lamp type.

**To Reproduce**
1) Using the Apple Home app, adjust the dimmer brightness from off to approximately 92%.

**Expected behavior**
I expect the dimmer to adjust the brightness of the attached lamps just like the branded apps do, at least from the minimum threshold upwards, but the lamps remain off until I adjust the dimmer in the Home app to 93% or above. This gives me only 7 steps out of 100 between off and fully bright, and even those steps don't seem to be linear. 

**Screenshots**
Home app: dimmer is powering lights off despite showing 92%:
![image](https://user-images.githubusercontent.com/1385209/86833967-3f56b400-c068-11ea-9872-1d06f5528b91.png)
There and below, the lamps are off; there and above, they brighten, but by about 95% they appear fully bright.

GridConnecct app is powering lights at just about the dimmest setting, as expected:
![image](https://user-images.githubusercontent.com/1385209/86834219-9197d500-c068-11ea-965a-43138013deab.png)

**Environment (please complete the following information):**
 - OS: iOS
-  iOS version: 13.5.1
-  Homehubs: Lutron, Philips Hue, Homebridge
 - Node Version: 12.16.3
 - Plugin Version: 1.0.0
-  Accessory Type: Simple Dimmer (outdoor outlet)

Any help to calibrate things or settings I might use to configure for parity between the apps would be greatly appreciated!

**Comment by zelittle** [comment]
@jhopper28 
Did you ever find a solution to this?

**Comment by jhopper28** [comment]
No, never did.

**Comment by zelittle** [comment]
@jhopper28

I think I may have fixed it... Prior to the below, the Homebridge log would show the following at max brightness:

```
Sending String Lights {"2":255}
```

I added the following in the config

```
"scaleBrightness": 1000
```

Now I'm seeing in the Homebridge log:

```
Sending String Lights {"2":1000}

```

And the SmartLife app is in sync showing 100% instead of the 23%. Will know for sure when the sun goes down (string lights).

**Comment by jdtsmith** [comment]
I found you also have to set `minBrightness` if you want perfect matching at the low end (I was trying to get all the way down to 1% dimming).  See [this comment](https://github.com/iRayanKhan/homebridge-tuya/issues/161#issuecomment-768370585).

**Comment by jdtsmith** [comment]
BTW, it would be useful to document the options `scaleBrightness` and `minBrightness` somewhere.

**Comment by iRayanKhan** [comment]
> BTW, it would be useful to document the options `scaleBrightness` and `minBrightness` somewhere.

https://github.com/iRayanKhan/homebridge-tuya/wiki/Supported-Device-Types#white-and-color-light-bulbs

**Comment by zelittle** [comment]
> > BTW, it would be useful to document the options `scaleBrightness` and `minBrightness` somewhere.
> 
> 
> 
> https://github.com/iRayanKhan/homebridge-tuya/wiki/Supported-Device-Types#white-and-color-light-bulbs

What wasn't clear to me in the wiki was that parameters listed for one device type may (or may not?) work for other device types. 

I'm using the "SimpleDimmer" type and I wasn't clear that I could use the parameters from other device types like the "RGBTWLight". 

However, I am also using a device that isn't explicitly supported by the plugin. The outdoor dimmer by Teckin.

**Comment by jdtsmith** [comment]
Right, so perhaps it just requires copying the relevant information to [SimpleDimmer](https://github.com/iRayanKhan/homebridge-tuya/wiki/Supported-Device-Types#simple-dimmers).  These parameters are used in the BaseAccessory so presumably are fairly universal.

**Comment by iRayanKhan** [comment]
> Right, so perhaps it just requires copying the relevant information to [SimpleDimmer](https://github.com/iRayanKhan/homebridge-tuya/wiki/Supported-Device-Types#simple-dimmers). These parameters are used in the BaseAccessory so presumably are fairly universal.

Will do. The docs have been in need of a major overhaul for awhile. Maybe a project for this weekend.
