### ISSUE TITLE
Dimming function not working

### ISSUE THREAD

**Issue by Elder-HVAC-Man** [iRayanKhan/homebridge-tuya#110]
**Checklist**
- [x] I have read the common issues wiki page - Yes
- [x] I have checked to make sure the plugin is up to date - Yes

**Describe the bug**
Device is a fairly new Treatlife Fan Control & Light Dimmer Switch, model DS-03.  Homebridge Tuya is configured for type "fanlight".  Homekit and Homebridge show the device with both a fan and light sliding bars for control.  The switch actually has 4 speed controls for the fan, but only 3 speeds are available (high is missing).  The light dimming portion doesn't do anything, except turn off the light at zero.

**To Reproduce**

**Expected behavior**
Expect the dimmer to function properly and would like to have 4 fan speeds.
**Screenshots**

**Environment (please complete the following information):**
 - OS: Raspbian GNU/Linux Buster (10) 
-  iOS version: 13.5.1
-  Homehubs: Homepod and AppleTV
 - Node Version: v12.17.0
 - Plugin Version: 1.0.0
-  Accessory Type - Treatlife Fan Control & Light Dimmer Switch, model DS-03 

**Additional context**
        {
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "MBR Fan and Light",
                    "type": "fanlight",
                    "manufacturer": "Treatlife",
                    "model": "DS03",
                    "id": "7013685498f4abfd0540",
                    "key": "secret key",
                    "dpPower": 1,
                    "dpBrightness": 2
                }
            ]
        },

[TuyaAccessory] Sending MBR Fan and Light {"3":"2"}
[TuyaAccessory] Sending MBR Fan and Light {"1":true}
[TuyaAccessory] Heard back from MBR Fan and Light with command 8
[TuyaAccessory] Heard back from MBR Fan and Light with command 8
[TuyaAccessory] Sending MBR Fan and Light {"9":true}
[TuyaAccessory] Sending MBR Fan and Light {"2":53}
[TuyaAccessory] Heard back from MBR Fan and Light with command 8
[TuyaAccessory] Sending MBR Fan and Light {"9":true}
[TuyaAccessory] Sending MBR Fan and Light {"2":83}
[TuyaAccessory] Heard back from MBR Fan and Light with command 8
[TuyaAccessory] Sending MBR Fan and Light {"9":true}
[TuyaAccessory] Sending MBR Fan and Light {"2":100}
[TuyaAccessory] Heard back from MBR Fan and Light with command 8
[TuyaAccessory] Sending MBR Fan and Light {"9":true}
[TuyaAccessory] Sending MBR Fan and Light {"2":50}

**Comment by ucfhall** [comment]
Issue confirmed.

**Comment by yudielcurbelo1** [comment]
Anything on this?

**Comment by ucfhall** [comment]
@iRayanKhan @yudielcurbelo1 @Elder-HVAC-Man @basdelfos 

I believe I have fixed this or at least found a workaround. I edited /usr/lib/node_modules/homebridge-tuya/lib/SimpleFanLightAccessory.js and made the following changes:
Line 42:
Old value: maxValue: 3,
New value: maxValue: 4,

Line 58:
Old value: maxValue: 100,
New value: maxValue: 1000,

Line 59:
Old value: minStep: 10
New value: minStep: 100

This solved both issues for me but again I don't know if it's a proper fix or a workaround. Similar changes may need to be made to SimpleFanAccessory.js and SimpleDimmerAccessory.js.

The full SimpleFanLightAccessory.js is attached. Please let me know if I can assist any further.

[SimpleFanLightAccessory.js.zip](https://github.com/iRayanKhan/homebridge-tuya/files/5058729/SimpleFanLightAccessory.js.zip)

**Comment by ucfhall** [comment]
Update on the above- this fix works for HomeKit but breaks Alexa integration.

**Comment by iRayanKhan** [comment]
Thanks for the fork. Would you consider making a new SimpleFanLightAccessory and make a PR so I can merge it in? 

Thanks,
Rayan.

**Comment by ucfhall** [comment]
I apologize but I'm a newb and uou may need to translate for me...what's a fork? PR? And can you use the SimpleFanLightAccessory.js I uploaded?

**Comment by ucfhall** [comment]
@iRayanKhan never mind...figured it out. Pull request submitted, waiting for your approval. Bear in mind it does break Alexa integration.

**Comment by qthatswho** [comment]
@iRayanKhan any chance we could get this PR reviewed, merged and released in an update in the near future?

**Comment by iRayanKhan** [comment]
I don't see an open PR, I can merge it manually tonight if you'd like.

**Comment by qthatswho** [comment]
Oh, sorry, I realize I hadn't actually verified there was an open PR, was just reviewing the comment above. This would be a welcome change (though it is worth noting the caveat @ucfhall mentioned).

Thanks!

**Comment by sholleman** [comment]
Ok, I've bought the same switches by mistake (I misread and thought they supported Homekit natively). I'm on the verge of returning them but I saw @ucfhall 's changes and so made a PR for them. I can't guarantee this won't break existing simpleFanLightAccessories. One alternative would be to create a new accessory definition just for the DS-03, but I don't know enough about the framework to know just how that would work. @iRayanKhan any thoughts?

**Comment by sholleman** [comment]
FYI, I've now been able to install my changes to HOOBS and can confirm that the DS-03 now works perfectly.

**Comment by vascott1** [comment]
Hi. I have 3 of the DS03 switches. None installed yet as I cannot seem to get this working. Can someone share their entries in the config file here? The device is showing up as an accessory but the controls are wonky at best. When I turn the fan on it turns on the fan and the light. Then I can't seem to reliably try off the light. I am sure this is something simple. I have no made the modes to /usr/lib/node_modules/homebridge-tuya/lib/SimpleFanLightAccessory.js (mine is in usr/local/lib) I think I am finally closer to being able to use the switches. Merry Christmas. LOL.

Thanks for any help.

Scott. 
 
I have this:
{
            "platform": "homebridge-tuya.TuyaLan",
            "devices": [
                {
                    "name": "Livingroom Fan/Light",
                    "type": "fanlight",
                    "manufacturer": "Treatlife",
                    "model": "DS03",
                    "id": "xxxxx",
                    "key": "xxxxxx"
                }
            ]
        }

**Comment by ucfhall** [comment]
Your configuration matches mine.

**Comment by vascott1** [comment]
Thanks :) I thought I removed this as I found the issue right after posting it. They are now working as expected. I have to admit they are the only switched out there that do what they do but can’t say I like how they do it as a physical switch :) also wish they came on black. I have asked.
  
  
  
    
  

  
  
>

**Comment by reiph** [comment]
This change actually broke my setup, which was for [this device](https://www.aliexpress.com/item/32963340950.html)

Is it possible to create a few more config settings to differentiate the characteristics between different devices?
For example: `maxRotationSpeed` and `maxBrightness`

Also the devices I have do not support brightness. We may need another setting like `noBrightness`.

Another issue I found was that when the switches were flipped on the device, the statuses were not immediately updated on HomeKit. I had to force close HomeKit and restart it to get the latest updates.

I found a workaround by adding the following code to `_registerCharacteristics`
```
this.device.on('change', (changes, state) => {
	if (changes.hasOwnProperty(this.dpLightOn) && characterLightOn.value !== changes[this.dpLightOn]) characterLightOn.updateValue(changes[this.dpLightOn]);
	if (changes.hasOwnProperty(this.dpActive) && characteristicActive.value !== changes[this.dpActive]) characteristicActive.updateValue(changes[this.dpActive]);
	if (changes.hasOwnProperty(this.dpRotationSpeed) && characteristicRotationSpeed.value !== changes[this.dpRotationSpeed]) characteristicRotationSpeed.updateValue(changes[this.dpRotationSpeed]);
	console.log('[TuyaAccessory] SimpleFanLight changed: ' + JSON.stringify(state));
});
```
If you think this is legitimate solution, I can create a PR for it.

**Comment by qthatswho** [comment]
I updated to the latest plugin version via HomeBridge, but dimming for the Treatlife DS03 just doesn't work now. On/off works, but the entire dimming range seems unaffected when changing using Home app.

**Comment by jdtsmith** [comment]
Not sure about fan, but see [this comment](https://github.com/iRayanKhan/homebridge-tuya/issues/161#issuecomment-768370585) for the config-file dimming fix for Treatlife dimmers I found worked.
