### ISSUE TITLE
New Device: Kogan Garage Door

### ISSUE THREAD

**Issue by Ferni7** [iRayanKhan/homebridge-tuya#111]
**Describe your device**
Kogan Garage Door Opener - https://www.kogan.com/au/buy/kogan-smarterhome-wireless-garage-door-opener/

**Partial Support?**
Does this device work in any fashion in the plugin? 
Partial support with the following config
{
                    "name": "Garage",
                    "type": "GarageDoor",
                    "manufacturer": "Kogan",
                    "model": "Garage Door Controller",
                    "id": "yyyyyyy",
                    "key": "xxxxxx",
                    "dpAction": 1,
                    "dpStatus": 2
                }

It shows me the open/close state in homekit/homebridge, but i can't control it (open/close it)

**Additional context**
If i watch the homebridge.log while opening and closing with tuya app, i get the below events:

[TuyaAccessory] GarageDoor changed: {"101":"fopen","102":"openning","104":100,"105":true}
[TuyaAccessory] Heard back from Garage with command 8
[TuyaAccessory] GarageDoor changed: {"101":"fopen","102":"opened","104":100,"105":true}
[TuyaAccessory] Heard back from Garage with command 8
[TuyaAccessory] GarageDoor changed: {"101":"fclose","102":"opened","104":100,"105":true}
[TuyaAccessory] Heard back from Garage with command 8
[TuyaAccessory] GarageDoor changed: {"101":"fclose","102":"closing","104":100,"105":true}
[TuyaAccessory] Heard back from Garage with command 8
[TuyaAccessory] GarageDoor changed: {"101":"fclose","102":"closed","104":100,"105":true}

I tried changing the config to dpAction: 101 but it still won't open/close. The issue I beleive is that we are sending a boolean true/false to 101, but the device is expecting fclose/fopen to open/close. I tested this by hacking the code and can get it to open/close, but when i do this the garage door state isn't right.

**Comment by Ferni7** [comment]
This is my hack to GarageDoorAccessory.js which lets me open/close it, but the state isn't accurate in homekit

const myVal = [];
myVal[true] = "fOpen";
myVal[false] = "fClose";

    setTargetDoorState(value, callback) {
//        this.setState(this.dpAction, value === this.targetOpen, callback);
        this.setState(this.dpAction, myVal[value === this.targetOpen], callback);

    }

**Comment by spadival** [comment]
I have modified the plugin to work with Kogan Garage door opener. Please refer to the following comment:

https://github.com/iRayanKhan/homebridge-tuya/issues/90#issuecomment-656071240

**Comment by Ferni7** [comment]
@spadival Thank you! Just copied your GarageDoorAccessory.js in, restarted and working now including the status :)

**Comment by iRayanKhan** [comment]
@spadival would you like to make a PR so I can merge it with credit?

**Comment by spadival** [comment]
Won’t the merge screw it up for the other garage door devices? The schema seems to be totally different between these devices and I had to hard code mine in. Maybe create a new file KoganGarageDoor.js and KoganBlinds.js ?
