### ISSUE TITLE
Odd message after working

### ISSUE THREAD

**Issue by sebcastrov** [iRayanKhan/homebridge-tuya#115]
Hi, I purchased a Smartlife switch (picture below) I got the local key and device id with igenix app and worked without any issues in the Home appe for like an hour, issue is that then I connected to Tuya app and no longer worked on Home app, got an odd message and not working, this is the schema

  {
    name: 'KS-811-1Seba',
    id: 'XX',
    key: 'ZZ',
    def: {
      schema: '[{"mode":"rw","code":"switch_1","name":"\\u5f00\\u51731","property":{"type":"bool"},"iconname":"icon-dp_power2","id":1,"type":"obj","desc":""},{"mode":"rw","code":"countdown_1","name":"\\u5f00\\u51731\\u5012\\u8ba1\\u65f6","property":{"unit":"s","min":0,"max":86400,"scale":0,"step":1,"type":"value"},"iconname":"icon-dp_time2","id":9,"type":"obj","desc":""}]',
      extras: '[{"complexType":"","id":1,"inputStyle":"","inputType":" "},{"complexType":"","id":9,"inputStyle":"","inputType":" "}]',
    },
  },
]

![image](https://user-images.githubusercontent.com/52010078/88120938-3bf81800-cb92-11ea-811c-694d628fd54b.png)

)

**Comment by ElphaX** [comment]
@sebcastrov After re-pairing to the Tuya App your device key may have changed. Please check the key and redo your config - should fix the issue.
