### ISSUE TITLE
tuya-cli set consecutive commands result in a hang

### ISSUE THREAD

**Issue by cdprince** [iRayanKhan/homebridge-tuya#116]
**Checklist**
- [y ] I have read the common issues wiki page
- [ y] I have checked to make sure the plugin is up to date

**Describe the bug**
If you set one of the outlets on the Jouyou power switch, you get a hang

$ DEBUG=* tuya-cli set --ip '10.0.0.212' --id 73328546dc4f22eb3795 --key 153e74966709XXXX --dps 3 --set 0
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 10.0.0.212... +11ms
  TuyAPI Socket connected. +14ms
  TuyAPI GET Payload: +2ms
  TuyAPI { gwId: '73328546dc4f22eb3795',
  TuyAPI   devId: '73328546dc4f22eb3795',
  TuyAPI   t: '1595377569',
  TuyAPI   dps: {},
  TuyAPI   uid: '73328546dc4f22eb3795' } +1ms
  TuyAPI SET Payload: +20ms
  TuyAPI { devId: '73328546dc4f22eb3795',
  TuyAPI   gwId: '73328546dc4f22eb3795',
  TuyAPI   uid: '',
  TuyAPI   t: 1595377568,
  TuyAPI   dps: { '3': 0 } } +1ms
  TuyAPI Received data: 000055aa000000010000000a00000064000000007b226465764964223a223733333238353436646334663232656233373935222c22647073223a7b2231223a66616c73652c2232223a747275652c2233223a747275652c2239223a302c223130223a302c223131223a307d7d9a0cfe410000aa55 +12ms
  TuyAPI Parsed: +5ms
  TuyAPI { payload:
  TuyAPI    { devId: '73328546dc4f22eb3795',
  TuyAPI      dps:
  TuyAPI       { '1': false, '2': true, '3': true, '9': 0, '10': 0, '11': 0 } },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 1 } +0ms
  TuyAPI Received data: 000055aa00000002000000070000000c0000000018cfc5da0000aa55 +11ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 7, sequenceN: 2 } +1ms
  TuyAPI Got SET ack. +0ms
  TuyAPI Received data: 000055aa00000000000000080000008b00000000332e313962613038313435376431326336373545444a74713576434e7a646c66632b2f627766477133474d4130684d7a4b4d56625a6f4262536d2f6b4a2f53753866627259514365504e444c6151577873335632667971636638555357764e686b71344b5565434c50446b5669584376366b4238554a697a3235566175303d55f2bc1a0000aa55 +49ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload:
  TuyAPI    { devId: '73328546dc4f22eb3795',
  TuyAPI      dps: { '3': false },
  TuyAPI      t: 1595377568,
  TuyAPI      s: 15 },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 8,
  TuyAPI   sequenceN: 0 } +1ms
  TuyAPI Disconnect +2ms
Set succeeded.
  TuyAPI Socket closed: 10.0.0.212 +9ms

$ DEBUG=* tuya-cli set --ip '10.0.0.212' --id 73328546dc4f22eb3795 --key 153e74966709XXXX --dps 3 --set 0
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 10.0.0.212... +11ms
  TuyAPI Socket connected. +21ms
  TuyAPI GET Payload: +4ms
  TuyAPI { gwId: '73328546dc4f22eb3795',
  TuyAPI   devId: '73328546dc4f22eb3795',
  TuyAPI   t: '1595377579',
  TuyAPI   dps: {},
  TuyAPI   uid: '73328546dc4f22eb3795' } +0ms
  TuyAPI SET Payload: +34ms
  TuyAPI { devId: '73328546dc4f22eb3795',
  TuyAPI   gwId: '73328546dc4f22eb3795',
  TuyAPI   uid: '',
  TuyAPI   t: 1595377579,
  TuyAPI   dps: { '3': 0 } } +0ms
  TuyAPI Received data: 000055aa000000010000000a00000065000000007b226465764964223a223733333238353436646334663232656233373935222c22647073223a7b2231223a66616c73652c2232223a747275652c2233223a66616c73652c2239223a302c223130223a302c223131223a307d7d557f40c80000aa55 +12ms
  TuyAPI Parsed: +4ms
  TuyAPI { payload:
  TuyAPI    { devId: '73328546dc4f22eb3795',
  TuyAPI      dps:
  TuyAPI       { '1': false, '2': true, '3': false, '9': 0, '10': 0, '11': 0 } },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 1 } +1ms
  TuyAPI Received data: 000055aa00000002000000070000000c0000000018cfc5da0000aa55 +8ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 7, sequenceN: 2 } +0ms
  TuyAPI Got SET ack. +0ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +15ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +1ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +2s
  TuyAPI Parsed: +0ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +1ms
  TuyAPI Pong from 10.0.0.212 +0ms
  TuyAPI Pinging 10.0.0.212 +8s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +242ms
  TuyAPI Parsed: +0ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +63ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +1s
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +1ms
  TuyAPI Pong from 10.0.0.212 +0ms
  TuyAPI Pinging 10.0.0.212 +9s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +12ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +22ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +8ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +1ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +13ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +8ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +22ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +1s
  TuyAPI Parsed: +0ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +1ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +9s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +9ms
  TuyAPI Parsed: +0ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +1ms
  TuyAPI Pong from 10.0.0.212 +0ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +708ms
  TuyAPI Parsed: +0ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +1ms
  TuyAPI Pong from 10.0.0.212 +0ms
  TuyAPI Pinging 10.0.0.212 +9s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +14ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +13ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +13ms
  TuyAPI Parsed: +0ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +1ms
  TuyAPI Pong from 10.0.0.212 +0ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +13ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +10ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +0ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +8ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +9ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +14ms
  TuyAPI Parsed: +0ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +1ms
  TuyAPI Pong from 10.0.0.212 +0ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +234ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +0ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +38ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +1ms
  TuyAPI Pong from 10.0.0.212 +0ms
^C

$ DEBUG=* tuya-cli set --ip '10.0.0.212' --id 73328546dc4f22eb3795 --key 153e74966709XXXX --dps 3 --set 1
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 10.0.0.212... +11ms
  TuyAPI Socket connected. +16ms
  TuyAPI GET Payload: +2ms
  TuyAPI { gwId: '73328546dc4f22eb3795',
  TuyAPI   devId: '73328546dc4f22eb3795',
  TuyAPI   t: '1595378018',
  TuyAPI   dps: {},
  TuyAPI   uid: '73328546dc4f22eb3795' } +1ms
  TuyAPI SET Payload: +21ms
  TuyAPI { devId: '73328546dc4f22eb3795',
  TuyAPI   gwId: '73328546dc4f22eb3795',
  TuyAPI   uid: '',
  TuyAPI   t: 1595378017,
  TuyAPI   dps: { '3': 1 } } +0ms
  TuyAPI Received data: 000055aa000000010000000a00000065000000007b226465764964223a223733333238353436646334663232656233373935222c22647073223a7b2231223a66616c73652c2232223a747275652c2233223a66616c73652c2239223a302c223130223a302c223131223a307d7d557f40c80000aa55 +13ms
  TuyAPI Parsed: +6ms
  TuyAPI { payload:
  TuyAPI    { devId: '73328546dc4f22eb3795',
  TuyAPI      dps:
  TuyAPI       { '1': false, '2': true, '3': false, '9': 0, '10': 0, '11': 0 } },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 1 } +0ms
  TuyAPI Received data: 000055aa00000002000000070000000c0000000018cfc5da0000aa55 +10ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 7, sequenceN: 2 } +0ms
  TuyAPI Got SET ack. +0ms
  TuyAPI Received data: 000055aa00000000000000080000008b00000000332e313935643964666666323933656264343345444a74713576434e7a646c66632b2f627766477133474d4130684d7a4b4d56625a6f4262536d2f6b4a2b39545052544d616c42484d735275302b3271635650714b5a73596e3647675a69366c586739574c35386d6a4352446f2b4749667574724d3963584b34524f59413d6c1011f70000aa55 +50ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload:
  TuyAPI    { devId: '73328546dc4f22eb3795',
  TuyAPI      dps: { '3': true },
  TuyAPI      t: 1595378017,
  TuyAPI      s: 16 },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 8,
  TuyAPI   sequenceN: 0 } +1ms
  TuyAPI Disconnect +2ms
Set succeeded.
  TuyAPI Socket closed: 10.0.0.212 +11ms

$ DEBUG=* tuya-cli set --ip '10.0.0.212' --id 73328546dc4f22eb3795 --key 153e74966709XXXX --dps 3 --set 1
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 10.0.0.212... +11ms
  TuyAPI Socket connected. +16ms
  TuyAPI GET Payload: +3ms
  TuyAPI { gwId: '73328546dc4f22eb3795',
  TuyAPI   devId: '73328546dc4f22eb3795',
  TuyAPI   t: '1595378027',
  TuyAPI   dps: {},
  TuyAPI   uid: '73328546dc4f22eb3795' } +0ms
  TuyAPI SET Payload: +20ms
  TuyAPI { devId: '73328546dc4f22eb3795',
  TuyAPI   gwId: '73328546dc4f22eb3795',
  TuyAPI   uid: '',
  TuyAPI   t: 1595378027,
  TuyAPI   dps: { '3': 1 } } +1ms
  TuyAPI Received data: 000055aa000000010000000a00000064000000007b226465764964223a223733333238353436646334663232656233373935222c22647073223a7b2231223a66616c73652c2232223a747275652c2233223a747275652c2239223a302c223130223a302c223131223a307d7d9a0cfe410000aa55 +12ms
  TuyAPI Parsed: +6ms
  TuyAPI { payload:
  TuyAPI    { devId: '73328546dc4f22eb3795',
  TuyAPI      dps:
  TuyAPI       { '1': false, '2': true, '3': true, '9': 0, '10': 0, '11': 0 } },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 1 } +0ms
  TuyAPI Received data: 000055aa00000002000000070000000c0000000018cfc5da0000aa55 +5ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 7, sequenceN: 2 } +0ms
  TuyAPI Got SET ack. +0ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +14ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +1s
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +9s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +14ms
  TuyAPI Parsed: +0ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +1ms
  TuyAPI Pong from 10.0.0.212 +1ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +15ms
  TuyAPI Parsed: +0ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +1ms
  TuyAPI Pong from 10.0.0.212 +0ms
  TuyAPI Pinging 10.0.0.212 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +29ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 10.0.0.212 +1ms

**To Reproduce**
described

**Expected behavior**
I think just a succeeded would do, no hang

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: 
Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux

-  Homehubs:  xfinity wifi router

 - Node Version: 
$ node -v
v10.21.0

 - Plugin Version:  
npm@5.8.0 /usr/share/npm
$ tuya-cli -V
1.13.0

-  Accessory Type
Juoyou Wifi Power Switch/relay

**Additional context**
N/A

**Comment by iRayanKhan** [comment]
Hey @cdprince, you are looking for the Tuya-cli repo, which differs from mine. Hope you found the help you needed.
