### ISSUE TITLE
FanLight not allowing speed change

### ISSUE THREAD

**Issue by AndrewJ1990** [iRayanKhan/homebridge-tuya#118]
**Checklist**
- [Y] I have read the common issues wiki page
- Y ] I have checked to make sure the plugin is up to date

**Describe the bug**
"FanLight" accessory is not allowing me to change fan speed from HomeKit app. When the fan is turned on despite what the percentage is the fan runs at 100%. Controlling the fan in the Homebridge Config UI web page works as it should.

**To Reproduce**
Attempt to adjust fan speed through HomeKit.

**Expected behavior**
Fan speed should be either 1, 2 or 3

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: 
-  iOS version:
-  Homehubs: 
 - Node Version: 
 - Plugin Version:
-  Accessory Type

**Additional context**
Schema for fan:
 name: 'Media Switch',
    id: '0814565698f4abec0a31',
    key: '...',
    def: {
      schema: '[{"mode":"rw","code":"switch","name":"\\u98ce\\u6247\\u5f00\\u5173","property":{"type":"bool"},"iconname":"icon-power","id":1,"type":"obj","desc":""},{"mode":"rw","code":"fan_speed","name":"\\u98ce\\u901f\\u6863\\u4f4d","property":{"range":["1","2","3"],"type":"enum"},"iconname":"icon-a_fan_low","id":3,"type":"obj","desc":"1\\u30012\\u30013\\u5206\\u522b\\u4ee3\\u8868\\u4f4e\\u3001\\u4e2d\\u3001\\u9ad8\\u98ce\\u901f\\u6863"},{"mode":"rw","code":"light","name":"\\u706f\\u5f00\\u5173","property":{"type":"bool"},"iconname":"icon-tcl_function_light","id":9,"type":"obj","desc":""},{"mode":"rw","code":"master","name":"\\u603b\\u5f00\\u5173","property":{"type":"bool"},"id":101,"type":"obj","desc":"\\u706f\\u548c\\u98ce\\u6247\\u7684\\u603b\\u5f00\\u5173"},{"mode":"rw","code":"timer_fan","name":"\\u98ce\\u6247\\u5012\\u8ba1\\u65f6","property":{"range":["1","2","3","4","5"],"type":"enum"},"id":102,"type":"obj","desc":"1 \\u8868\\u793a\\u65e0\\u6548\\uff0c2\\u30013\\u30014\\u30015 \\u5206\\u522b\\u8868\\u793a\\u5012\\u8ba1\\u65f6 1h\\u30012h\\u30014h\\u30018h"},{"mode":"rw","code":"timer_light","name":"\\u706f\\u5012\\u8ba1\\u65f6","property":{"range":["1","2","3","4","5"],"type":"enum"},"id":103,"type":"obj","desc":"1 \\u8868\\u793a\\u65e0\\u6548\\uff0c2\\u30013\\u30014\\u30015 \\u5206\\u522b\\u8868\\u793a\\u5012\\u8ba1\\u65f6 1h\\u30012h\\u30014h\\u30018h"}]',
      extras: '[{"complexType":"","id":1,"inputStyle":"","inputType":""},{"complexType":"","id":3,"inputStyle":"","inputType":""},{"complexType":"","id":9,"inputStyle":"","inputType":""},{"complexType":"","id":101,"inputStyle":"","inputType":""},{"complexType":"","id":102,"inputStyle":"","inputType":""},{"complexType":"","id":103,"inputStyle":"","inputType":""}]',

config file

{
                    "name": "Media Room",
                    "type": "FanLight",
                    "manufacturer": "Deta Fan Switch",
                    "model": "Deta",
                    "id": "0814565698f4abec0a31",
                    "key": "...",
                    "dpActive": 1,
                    "dpRotationSpeed": 3,
                    "dpLightOn": 9,
                    "dpBrightness": 10
                },

**Comment by stibbzy** [comment]
I have the same fan controller (Deta), and I'm also getting errors. Mine look like this: 
��k�(����pvory] Odd message from Ceiling Fan with command 10: �� 7���HJ����}YW
[TuyaAccessory] Raw message from Ceiling Fan (3.3) with command 10: 000055aa000000010000000a0000002c00000001e8c42037fa83d4484a809794ed7d590557040df98c6bd728a7f1a5e1cd701c76bc3ee3520000aa55

The plugin finds my device, but generates two switches in the Home app (one for the fan and one for the light). Trying to just use the switches produces no change to the state of the controller.

**Comment by stibbzy** [comment]
For what it’s worth, the issue seems to be that the fan is instructed to turn on at the same time as it is instructed to set a fan speed. You can see the fan switch light blink when changing speeds in the Home app, which doesn’t happen when using the wall button manually. 

I’ve got it mostly working by commenting out the setActive part of the code in SimpleFanLightAccessory.js. This allows Home app and Siri control for fan speed adjustments (including zero speed for off), but you can’t just touch the tile to turn the fan on and off, nor can you ask Siri to just turn the fan on or off. 

More investigations to do.

**Comment by AndrewJ1990** [comment]
@stibbzy That's what's I've figured out as well, it sending the setActive when you change the speed in HomeKit. Appreciate your work in helping with this. I'm still learning heaps about how this all works

**Comment by stibbzy** [comment]
Hi @AndrewJ1990 , @iRayanKhan Yep, it works fundamentally differently to the Brilliant fan, in that whenever setActive is sent, the fan will turn on full speed. Attached is the best I can do with my limited coding knowledge (renamed to .txt). It will allow fan speed changes with the home app slider and Siri, and also allow you to turn OFF the fan from the app and Siri, but you can't turn it ON (but you can use the slider to turn it on). I've also changed the dimmable light to a switch, as the Data unit doesn't support dimming.

Unfortunately, I'm not skilled enough to know how to check for variable conditions external to the function (like, if rotation speed is more than 0, then ignore setActive request). For some reason, the status of the fan updates a lot slower than the light as well.

@murch1 has just responded to my initial request for help over at the original home bridge-tuya-lan page (he developed the initial Brilliant fan controller support), hopefully he can add some advice: https://github.com/AMoo-Miki/homebridge-tuya-lan/pull/148
[SimpleFanLightAccessory.txt](https://github.com/iRayanKhan/homebridge-tuya/files/5093907/SimpleFanLightAccessory.txt)

**Comment by stibbzy** [comment]
Hi @iRayanKhan 
If you had a chance, could you take a look at my text file above and see if there is anything simple that can be done to fix the speed control issue with Deta fan controllers? We just need to prevent the code setting setActive to true every time the rotation speed is changed. My text file is a hack job to prevent setActive from ever being set true, but this means you can’t turn the fan on from the Home app file. The only way to make it operate is to select a fan speed. 
Thanks so much,
Mark.

**Comment by ElphaX** [comment]
My DETA fan controllers are using device type fanlight and are working perfectly fine, can you confirm if this is still a valid issue?

There is also an update  #267  coming very soon that will disable any existing values to be resent to the device such as a fan that's switched ON to be told to turn ON again -_-

**Comment by stibbzy** [comment]
> My DETA fan controllers are using device type fanlight and are working perfectly fine, can you confirm if this is still a valid issue?
> 
> There is also an update #267 coming very soon that will disable any existing values to be resent to the device such as a fan that's switched ON to be told to turn ON again -_-

Hi. I can’t confirm if other issue still exists. I got frustrated with the whole thing and ended up flashing the controllers with Tasmota and controlling them from Home Assistant.

**Comment by AndrewJ1990** [comment]
Hi @ElphaX , my Deta Fan controllers are still doing the same thing. Will only operate at full speed whenever turned on or trying to change speed
