### ISSUE TITLE
Air Conditioner temperature control only works if minTemp and maxTemp is set to Fahrenheit values not Celsius; Home app doesn't show the correct values

### ISSUE THREAD

**Issue by azosnu** [iRayanKhan/homebridge-tuya#119]
In the config if I put the minTemp (61) and maxTemp (88) in Fahrenheit values instead of Celsius values (16.111) and (31.111) the AC in Home app functions but it converts the 61 and 88 values from Celsius to Fahrenheit making it look like (141) and (190) in the Home app. However, I can adjust temperature dial and it sends the correct values to air conditioner when seeing the homebridge console.

Now if I follow the parameters set forth by the plugin to use Celsius for minTemp (16.111) and maxTemp (31.111) the app will show the correct info by converting the Celsius temps to Fahrenheit. The kicker is temperature control doesn’t work and its maxed out. If I control the temperature dial, I can see in homebridge console that it sends the AC command to change temperature to 141 F. It essentially converts the 61 shown in the Home app which is supposed to be Fahrenheit and treats it as Celsius and converts the 61 C to 141 F. 

Any solution to this? So I can see the correct temperature values in the home app instead.

Thanks. 

**FYI: I have the Friedrich CHILL® PREMIER SMART ROOM AIR CONDITIONER if that helps and I am on beta v1.5.0-rc.12** 
**The AC wasn't working on the current build as it was having trouble with the socket connection.**

**The beta somehow fixes the issue however a few time homebridge console will show: Socket had a problem and will reconnect to Aros (ECONNRESET) and then in a few seconds it will make contact again and it starts working. Not sure what's happening there** 

<img width="454" alt="Farenheit" src="https://user-images.githubusercontent.com/69114262/89125560-55ac3000-d4ad-11ea-80ec-f33acfb47a8b.png">

<img width="180" height="400" alt="iOS AC" src="https://user-images.githubusercontent.com/69114262/89125603-aa4fab00-d4ad-11ea-8242-0a9af4fe7634.png">

**Comment by iRayanKhan** [comment]
Interesting. Can you give me a week before I can debug some more?

**Comment by azosnu** [comment]
Sure. Thank You.

**Comment by azosnu** [comment]
Hey did you find out what the issue was?

**Comment by azosnu** [comment]
I was going through my Homebridge GUI and under accessories, the AC shows up with the correct temperature so it seems like an issue with this build. It seems to be sending the Fahrenheit value as Celsius to Home app and the Home app in turn converts the Celsius to Fahrenheit values.

**Comment by diazabdulm** [comment]
I have the same Air Conditioner and the same issue still persists... I think this should be re-opened

**Comment by banjobanjobanjo** [comment]
Me too. My Friedrich device seems to be sending the temperature reading (and settings) in Fahrenheit, but then when I look in homebridge GUI, instead of showing 70 degrees F, it shows 158 degrees F, which means the plugin (or homebridge) is treating the F temp value as though it is in C, and converting it into F (erroneously). In homebridge GUI and the home app, it shows 158F, while the aircon shows 70F. Is there a way to ensure that the plugin is specifying that the value it is receiving from Tuya is already in F?
