### ISSUE TITLE
Spelling error in path to Setup Instructions in config-example.MD

### ISSUE THREAD

**Issue by davidh2075** [iRayanKhan/homebridge-tuya#122]
**Checklist**
- [n/a] I have read the common issues wiki page
- [n/a] I have checked to make sure the plugin is up to date

**Describe the bug**
The link in config-example.MD to the Setup Instructions is
https://github.com/iRayanKgan/homebridge-tuya/wiki/Setup-Instructions

**To Reproduce**
1. Open https://github.com/iRayankhan/homebridge-tuya
1. Click on [config-example.MD](https://github.com/iRayanKhan/homebridge-tuya/blob/master/config-example.MD)
1. Click on Setup Instructions in the text:
   * id (required) and key (required) are parameters for your device. If you don't have them, follow the steps found on the [Setup Instructions](https://github.com/iRayanKgan/homebridge-tuya/wiki/Setup-Instructions) page.

The link is https://github.com/iRayanKgan/homebridge-tuya/wiki/Setup-Instructions

**Expected behavior**
The link probably should be https://github.com/iRayanKhan/homebridge-tuya/wiki/Setup.
i.e. K**g**an should be K**h**an and Setup-Instructions should be Setup.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: n/a
-  iOS version: n/a
-  Homehubs:  n/a
 - Node Version:  n/a
 - Plugin Version: n/a
-  Accessory Type:  n/a

**Additional context**
n/a.

**Comment by iRayanKhan** [comment]
Ah my bad. Thank you for pointing this out. Will have it fixed shortly!
