### ISSUE TITLE
I want to install the latest version of tuya.

### ISSUE THREAD

**Issue by Jeoniiiii** [iRayanKhan/homebridge-tuya#123]
I am currently using version 1.0.0

I know the latest version is 1.0.3, but the version that can be installed in Homebridge is 1.0.0.

What is the latest version that can be installed now?

When will version 2.0.0 be released?

**Comment by walshy1009** [comment]
> Hey there, thanks for reminding me, I'll publish a new beta seed of V2 later today. For now, you can git clone the branch, or, if there is an existing beta for it, use that one via npm.

Any update on V2 beta seed?

**Comment by iRayanKhan** [comment]
Thanks for the reply, there should be a new build within the next 10 minutes. I'll post the build instructions in the wiki for those inclined. The build instructions will be posted here after I finish writing it so like 5-10 minutes after the update comes out.

**Comment by iRayanKhan** [comment]
Closing this for now. V2 seed is going to published right now, but it's advised to stay away unless you have a bug that it addresses.
