### ISSUE TITLE
LED Strip Issue

### ISSUE THREAD

**Issue by Faisalthe01** [iRayanKhan/homebridge-tuya#124]
I have installed a new LED Strip. I have got it working, everything works fine Colors. Just with the Brightness, the color switches to Red when i try to lower the brightness, not sure what I have done wrong.

Scheme
```
  {
    name: 'Smart LED Strip',
    id: '',
    key: '',
    def: {
      schema: '[{"mode":"rw","code":"switch_led","name":"\\u5f00\\u5173","property":{"type":"bool"},"iconname":"icon-dp_power","id":20,"type":"obj","desc":""},{"mode":"rw","code":"work_mode","name":"\\u6a21\\u5f0f","property":{"range":["white","colour","scene","music"],"type":"enum"},"iconname":"icon-dp_mode","id":21,"type":"obj","desc":""},{"mode":"rw","code":"colour_data","name":"\\u5f69\\u5149","property":{"type":"string","maxlen":255},"iconname":"icon-yanse","id":24,"type":"obj","desc":""},{"mode":"rw","code":"scene_data","name":"\\u573a\\u666f","property":{"type":"string","maxlen":255},"iconname":"icon-shoucang","id":25,"type":"obj","desc":""},{"mode":"rw","code":"countdown","name":"\\u5012\\u8ba1\\u65f6\\u5269\\u4f59\\u65f6\\u95f4","property":{"min":0,"max":86400,"scale":0,"step":1,"type":"value"},"iconname":"icon-a_nav_timer","id":26,"type":"obj","desc":""},{"mode":"wr","code":"music_data","name":"\\u97f3\\u4e50\\u706f","property":{"type":"string","maxlen":255},"iconname":"icon-dp_mic","id":27,"type":"obj","desc":""},{"mode":"wr","code":"control_data","name":"\\u8c03\\u8282","property":{"type":"string","maxlen":255},"iconname":"icon-dp_box2","id":28,"type":"obj","desc":""},{"mode":"wr","code":"debug_data","name":"\\u8c03\\u8bd5","property":{"type":"string","maxlen":255},"iconname":"icon-dp_box","id":29,"type":"obj","desc":""}]',
    },
  },
```
My Config
```

                {
                    "name": "LED Strip",
                    "type": "RGBTWLight",
                    "manufacturer": "JesLED",
                    "model": "LED Strip",
                    "id": "",
                    "key": "",
                    "dpPower": 20,
                    "dpMode": 21,
                    "dpBrightness": 24,
                    "dpColorTemperature": 23,
                    "dpColor": 24,
                    "minBrightness": 10,
                    "maxWhiteColor": 221,
                    "colorFunction": "HSB",
                    "scaleBrightness": 1000,
                    "scaleWhiteColor": 1000
                }
```

Nothing special in logs either to see what is happening

`[8/24/2020, 2:08:13 PM] [Tuya] Ready to handle LED Strip (RGBTWLight:3.3) with signature {}`

This is what it shows when i do something in Home app

```
[TuyaAccessory] Heard back from LED Strip with command 8
[TuyaAccessory] Heard back from LED Strip with command 8
[TuyaAccessory] Heard back from LED Strip with command 8
[TuyaAccessory] Heard back from LED Strip with command 8
[TuyaAccessory] Heard back from LED Strip with command 8
[TuyaAccessory] Heard back from LED Strip with command 8
[TuyaAccessory] Heard back from LED Strip with command 8
[TuyaAccessory] Heard back from LED Strip with command 8
[TuyaAccessory] Heard back from LED Strip with command 8
[TuyaAccessory] Heard back from LED Strip with command 8
```

**Comment by Faisalthe01** [comment]
I noticed from Homebridge Accessories page that if i change the Brightness to any number than 100, the Hue changes to 0 that is red Color and causing the color to change to Red.

Before
![Capture](https://user-images.githubusercontent.com/62862684/91031480-f7a1e100-e643-11ea-8c5e-c3eb83f40b1e.JPG)

After

![Capture1](https://user-images.githubusercontent.com/62862684/91031532-0ee0ce80-e644-11ea-9aed-c11d9e86623c.JPG)

**Comment by Faisalthe01** [comment]
Also, i  get this when i restart Homebridge and if the light is on but then the light tile is displayed as off in Home app i think it is because power on/off dp is true and false while the plugin looks for 0 and 1

`[TuyaAccessory] LED Strip (3.3) didn't respond with its current state.`

**Comment by iRayanKhan** [comment]
Have you tried to get your device's schema to get the signature.

**Comment by Faisalthe01** [comment]
> Have you tried to get your device's schema to get the signature?

Hey brother, thanks for replying. yes the Schema is in my first post

**Comment by iRayanKhan** [comment]
My bad it didn't let me scroll through it sideways. I'll see if I can make a config that would work with it. Im working on a bug fix right now, once it's done I'll do this.

**Comment by Faisalthe01** [comment]
> My bad it didn't let me scroll through it sideways. I'll see if I can make a config that would work with it. Im working on a bug fix right now, once it's done I'll do this.

Hey bro, this fixed the issue plus i copied the BaseAccessory.js & RGBTWLightAccessory.js from TuyaLan RC12 into my lib folder so all good 👍 

https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/81

just with this, if you can help. is it happening because of the thing i mentioned or something else

https://github.com/iRayanKhan/homebridge-tuya/issues/124#issuecomment-679445409

**Comment by iRayanKhan** [comment]
Thank you for mentioning this fix. I'll have to see what changed in the Tuya lan RC, compared to the current release. 

As for the power states, I'll have most likely have to make a new type of lightstrip accessory, that support T/F instead of 0/1. I'll update you tomorrow, if I don't reply within 48 hours please ping me.

**Comment by Faisalthe01** [comment]
> Thank you for mentioning this fix. I'll have to see what changed in the Tuya lan RC, compared to the current release.
> 
> As for the power states, I'll have most likely have to make a new type of lightstrip accessory, that support T/F instead of 0/1. I'll update you tomorrow, if I don't reply within 48 hours please ping me.

Great thank you. The RGBTW file is same as Tuya Lan’s latest RC, just the BaseAccessory.js has mode code in it, that have fixed it.

**Comment by iRayanKhan** [comment]
Hey @Faisalthe01 do you have discord by chance?

**Comment by Faisalthe01** [comment]
Hey @iRayanKhan , no sorry, but i can make one.

**Comment by iRayanKhan** [comment]
Hey @Faisalthe01,
My discord is: iRayanKhan#9697

Usernames are case sensitive.

**Comment by ElphaX** [comment]
@iRayanKhan was this followed up on Discord?

**Comment by iRayanKhan** [comment]
Yes, [see](https://github.com/Faisalthe01/test/blob/master/GarageDoorAccessory.js).

**Comment by ElphaX** [comment]
For future reference: the brightness command isnt sending color and device defaults to 0 hue which leads to red light.
Sending the color alongside the brightness on every request fixes the issue as well.
