### ISSUE TITLE
RGBW Light - Not responding in Homebridge/Homekit

### ISSUE THREAD

**Issue by arubarb** [iRayanKhan/homebridge-tuya#128]
**Checklist**
- [ x] I have read the common issues wiki page
- [ x] I have checked to make sure the plugin is up to date

**Describe the bug**
I have added my bulbs to homebridge with this plugin and have them appearing in homekit. however the bulb itself does not respond to any commands even though homebridge/homekit says it is turning on/off etc. 

 **Environment (please complete the following information):**
 - OS: Mojave
 - Plugin Version: 1.0.5
-  Accessory Type: Tuya RGBWLight

**Additional context**        Coding below.    

"platform": "TuyaLan",
            "devices": [
                {
                    "name": "Library Bulb",
                    "type": "TWLight",
                    "manufacturer": "Kogan",
                    "model": "e14 Globe",
                    "id": "",
                    "key": ""

**Comment by iRayanKhan** [comment]
Do you happen to have your devices schema?

**Comment by arubarb** [comment]
Hmm, Sorry I’m a bit of a noob, I’m not sure where that is or where to find it. Can you let me know where find it?

**Comment by identd113** [comment]
Set the type from "TWLight" to "SimpleLight" and then change it using your Tuya app.  Homebridge should print out more descriptive information.

**Comment by arubarb** [comment]
I changed it to SimpleLight, then when i turned it on using the Tuya App it said this in the logs: 

[TuyaAccessory] Heard back from Library Bulb with command 8
[TuyaAccessory] SimpleLight changed: {"20":true,"21":"white","22":1000,"23":0,"24":"000003e803e8","25":"05646402000003e803e800000000646402007803e803e80000000064640200f003e803e800000000646402003d03e803e80000000064640200ae03e803e800000000646402011303e803e800000000","26":0}

It still doesn't respond in homebridge when I turn it on or off on the accessories tab.

**Comment by identd113** [comment]
That light is very similar to mine.  This is my config, sans ID and key
```
{
         "platform": "TuyaLan",
            "devices": [
                {
                    "name": "Office Light",
                    "type": "SimpleLight",
                    "manufacturer": "3Stone",
                    "id": "",
                    "key": "",
                    "ip": "10.0.1.150",
                    "intro": false,
                    "dpPower": 20,
                    "colorFunction": "HSB",
                    "dpMode": 21,
                    "dpColor": 24,
                    "scaleWhiteColor": 1000,
                    "scaleBrightness": 1000,
                    "minBrightness": 10,
                    "dpColorTemperature": 24
                }
            ]
        }
 This should at least let you turn it on and off, but dimming between colors and white light is different

**Comment by identd113** [comment]
Also, please remove your key and i'd from the original post

**Comment by arubarb** [comment]
Perfect, that works to turn on and off! keep me posted if you find a fix for the colour function.

**Comment by PetersenLars** [comment]
I'm having the exact same issue! I was using 'TWLight' with default config and that didn't work. Nothing happened when I changed input on the Home app. Copied @identd113 's config (apart from the config) and that works. Only on and off for now unfortunately. Hopefully other functionalities will start working in the future. Thanks!

**Comment by ElphaX** [comment]
@arubarb Change it back to RGBWLight and send through the same signature line, I'll let you know what your config should be. Reopen this issue when replying.

**Comment by AnonymousPea** [comment]
@ElphaX Hi I am also having the same issues. I set it to the above details, and it turns on and off, changes colour, but can't change brightness. These are the details .

>    {

                    "type": "RGBTWLight",
                    "name": "Lamp",
                    "id": "xxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxx",
                    "manufacturer": "Kogan",
                    "model": "Kogan SmarterHome Light",
                    "dpPower": 20,
                    "dpColorTemperature": 24,
                    "dpMode": 21,
                    "dpColor": 24,
                    "colorFunction": "HSB",
                    "scaleBrightness": 1000,
                    "scaleWhiteColor": 1000
                },

When changing it in the Tuya app home bridge spits out that is the log

> [Tuya] Heard back from Lamp with command 8
[Tuya] Heard back from Lamp with command 8
[Tuya] Heard back from Lamp with command 8
[Tuya] setColorTemperature: 307
[Tuya] Sending Lamp {"21":"white","24":262}
[6/11/2021, 8:48:48 PM] [homebridge-tuya] This plugin generated a warning from the characteristic 'Saturation': characteristic was supplied illegal value: number 358 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[Tuya] Heard back from Lamp with command 8
