### ISSUE TITLE
New Device:  3DStone LED Bulb. RGBClight

### ISSUE THREAD

**Issue by identd113** [iRayanKhan/homebridge-tuya#129]
From Tuya:
RGBC light | An RGBC lighting product has adjustable light colors and brightness. RGBC stands for red, green, blue, and cool white.

**Describe your device**
3DStone
https://www.amazon.com/gp/product/B073PZMBHF

**Partial Support?**
Yes, if I map the correct DPs, then it would

**Additional context**
White brightness and color brightness are handled by different DPs:

[TuyaAccessory] SimpleLight changed: {"20":true,"21":"white","22":573,"24":"00000262030a","25":"06464601000003e803e800000000464601007803e803e80000000046460100f003e803e800000000","26":0}

[TuyaAccessory] SimpleLight changed: {"20":true,"21":"white","22":1000,"24":"00000262030a","25":"06464601000003e803e800000000464601007803e803e80000000046460100f003e803e800000000","26":0}

22 is white brightness

Color:

TuyaAccessory] SimpleLight changed: {"20":true,"21":"colour","22":1000,"24":"00000262000a","25":"06464601000003e803e800000000464601007803e803e80000000046460100f003e803e800000000","26":0}

[TuyaAccessory] SimpleLight changed: {"20":true,"21":"colour","22":1000,"24":"0000026203e8","25":"06464601000003e803e800000000464601007803e803e80000000046460100f003e803e800000000","26":0}

24 is color and brightness, 000002620 seems to be the color, and  the last 3 are the brightness, ranging from 00a to 3e8

25 is color and brightness for a list of consecutive actions, but "21" needs to be scene for this field to be read

**Comment by iRayanKhan** [comment]
Are you able to post your config please?

**Comment by identd113** [comment]
` {
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "Office Light",
                    "type": "SimpleLight",
                    "manufacturer": "3Stone",
                    "id": "XXX",
                    "key": "YYY",
                    "ip": "10.0.1.150",
                    "intro": false,
                    "dpPower": 20,
                    "colorFunction": "HSB",
                    "dpMode": 21,
                    "dpColor": 24,
                    "scaleWhiteColor": 1000,
                    "scaleBrightness": 1000,
                    "minBrightness": 10,
                    "dpColorTemperature": 24
                }
            ]
        }
`

**Comment by identd113** [comment]
I have this as simplelight to understand the config it responds to  I suspect setting to RGBTWLight would help in some of these cases.
This is also a RGB and Cool White, which is an RGBCLight

**Comment by identd113** [comment]
Any thoughts on how to have the white side of the light, have the brightness increased/decreased by 22, but have the color part changes by the last 3 of 24?

**Comment by ElphaX** [comment]
Unfortunately we don't have the device to test this flexibility, did you find a solution @identd113?  Please re-open this issue if relevant.
