### ISSUE TITLE
Authentication error: Get accesstoken failed. Username or password error!

### ISSUE THREAD

**Issue by juills** [iRayanKhan/homebridge-tuya#132]
I have homebridge-tuya installed on my raspberry pi. I am unable to authenticate to my iot.tuya.com account even though my username and password are correct. Any assistance you can give would be helpful. Thanks!

**Comment by iRayanKhan** [comment]
Hi there, I had this issue too when trying to use sign-in w/ Apple. I had to make a new Tuya account through iot.tuya.com for some reason, then a normal account. You may have to contact Tuya for assistance since this is an unofficial "bridge".
