### ISSUE TITLE
Are blinds working in latest version 1.0.5

### ISSUE THREAD

**Issue by Lestercity** [iRayanKhan/homebridge-tuya#133]
Hi Rayan. Been a long time. How are you? Was wondering if you managed to get the blinds working in latest version 1.0.5. Thanks.

**Comment by iRayanKhan** [comment]
Hey @Lestercity, I haven't gotten any direct progress, but I have added some test blinds in V2 Bx. A new seed should be out soon (hopefully). But I can't really debug further since I have looked at every approach possible, and may have to wait for when the official Tuya Api is in a hb dev's hands.
