### ISSUE TITLE
Powering on after setting brightness or color

### ISSUE THREAD

**Issue by sjors98** [iRayanKhan/homebridge-tuya#135]
**Checklist**
- [x] I have read the common issues wiki page
- [x] I have checked to make sure the plugin is up to date

**Describe the bug**
When I change the brightness or change the color of a RGBTWLight bulb the plugin sends a request to the bulb to turn the power on. This is causing my bulb to flash everytime when changing brightness or color.

**To Reproduce**
* Turn on the bulb
* Change the brightness 
* Watch how it flickers when changing brightness
* Check homebridge log to find the log below

Sets the brightness:
`[Homebridge] [TuyaAccessory] Sending [DEVICE_NAME] {"3":98}`

Sets the power to on again:
`[Homebridge] [TuyaAccessory] Sending [DEVICE_NAME] {"1":true}`

**Expected behavior**
I expect the plugin to just change the brightness or color of the bulb and don't send another power request.

**Environment (please complete the following information):**
 - OS: HOOBS 3.1.20
-  iOS version: 14
-  Homehubs: Zigbee2mqtt server and Philips hue
 - Node Version: 12.14.1
 - Plugin Version: 1.0.5 (Latest)
-  Accessory Type:  Smart Bulb RGBTWLight

**Comment by iRayanKhan** [comment]
Hi, was this from the DM that was resolved on twitter?

**Comment by sjors98** [comment]
Hi! I don’t know about that :)

**Comment by sjors98** [comment]
Hi! I've switched from tuya (Wifi) lights to zigbee (which I run via zigbee2mqtt). I'm closing this issue
