### ISSUE TITLE
Device name updated in config.json does not update the displayName in cachedAccessories

### ISSUE THREAD

**Issue by davidh2075** [iRayanKhan/homebridge-tuya#136]
**Checklist**
- [Y] I have read the common issues wiki page
- [Y] I have checked to make sure the plugin is up to date

**Describe the bug**
Probably not a bug, more of a feature request: if you change a device name in the configuration, the changed name is not updated in the cachedAccessories file. The UI (e.g. HOOBS Accessories tab) continues to display the displayName from cachedAccessories. Some log messages display one name, some the other name.

I've made a small change to my own index.js to update the cachedAccessories displayName if it differs from the device name in the config.json file. I've included the change under **Additional context** below.

**To Reproduce**

1. Change a device name in the config. For example, if using HOOBS, click on the Tuya Configuration link on the Plugins tab, edit the device name and then click Save Changes. That will restart the homebridge service.
2. If you changed config.json via some other mechanism that didn't restart the homebridge service, restart it now.
3. The first restart will cause homebridge to read on start-up the config.json file with the updated device name.
4. Restart the homebridge service again. The second restart will cause homebridge to write the cachedAccessories file when it stops the service.
5. Check the cachedAccessories file: the device's displayName isn't updated.

**Expected behavior**
Ideally, the cachedAccessories displayName would be updated by step 5 above.
There are a lot of items in cachedAccessories that one would **not** change, e.g. no UUIDs and probably nothing in the services array.
The displayName seems a fairly innocuous change. I can contain my disappointment if persuaded otherwise :-).

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: Raspbian buster release 10 kernel 4.19.97-v7l+
-  iOS version: n/a
-  Homehubs: HOOBS 3.2.6, Apple TV 4K
 - Node Version: 12.16.3
 - Plugin Version: 1.0.5
-  Accessory Type: Kogan Smart Plug With Energy Meter KASPEMHA

**Additional context**
This is the mod I made to ```addAccessory()``` in index.js, just prior to the call to ```this.cachedAccessories.set()```:
```javascript
    // *****start of additional code*****
    if (accessory && accessory.displayName !== deviceConfig.name) {
      this.log.info(
          "Configuration name %s differs from cached displayName %s. Updating cached displayName to %s ",
          deviceConfig.name, accessory.displayName, deviceConfig.name);
      accessory.displayName = deviceConfig.name;
    }
    // *****end of additional code*****
    this.cachedAccessories.set(
        deviceConfig.UUID, new Accessory(this, accessory, device, !isCached));
```

**Comment by iRayanKhan** [comment]
Thank you so much @davidh2075. Would you like to turn this into a PR so I can merge it and credit you?

**Comment by davidh2075** [comment]
Done in #137. Sorry, took me a while because a) it's my first PR on GitHub and b) I had to unravel into separate branches some overlapping commits for GarageDoorAccessory.js and TuyaAccessory.js. I commented on my updates to those in #90 and #130 respectively. Please let me know if you want me to do PRs for those, too.
FWIW, I feel that GarageDoorAccessory.js may be better if it was structured like your Chamberlain plugin. That was a bridge too far for me.
