### ISSUE TITLE
SimplyHeater - CurrentHeaterCoolerState 

### ISSUE THREAD

**Issue by LiborBaca** [iRayanKhan/homebridge-tuya#140]
**Checklist**
- [x ] I have read the common issues wiki page
- [x ] I have checked to make sure the plugin is up to date

**Describe the bug**
Hi,

I think the current implementation of the CurrentHeaterCoolerState is wrong, as homekit always show the status heating even if the current room temperature is bellow the desired temperature set on thermostat. The proper status should be idle.

I review the code, and I think I located the problem, unfortunately don't have experience with java coding.
The problem is the the active / inactive characteristics  is used as well for CurrentHeaterCoolerState

Registered characteristics:
        this.dpActive = this._getCustomDP(this.device.context.dpActive) || '1';

        service.getCharacteristic(Characteristic.CurrentHeaterCoolerState)
            .updateValue(this._getCurrentHeaterCoolerState(dps))
            .on('get', this.getCurrentHeaterCoolerState.bind(this));

And function:

    getCurrentHeaterCoolerState(callback) {
        this.getState([this.dpActive], (err, dps) => {
            if (err) return callback(err);

            callback(null, this._getCurrentHeaterCoolerState(dps));
        });
    }

    _getCurrentHeaterCoolerState(dps) {
        const {Characteristic} = this.hap;
        return dps[this.dpActive] ? Characteristic.CurrentHeaterCoolerState.HEATING : Characteristic.CurrentHeaterCoolerState.INACTIVE;
    }

While according the homebridge documentation this should be two different characteristics:

https://developers.homebridge.io/#/characteristic/Active.  - active, inactive
And 
https://developers.homebridge.io/#/characteristic/CurrentHeaterCoolerState - inactive, idle, heating, cooling

In my case the datapoints:
[TuyaAccessory] SimpleHeater changed: {"1":true,"2":240,"3":225,"4":"Auto","7":false,"13":0,"14":"no_heating"}
[TuyaAccessory] SimpleHeater changed: {"1":true,"2":240,"3":225,"4":"Auto","7":false,"13":0,"14":"heating"}

Would it be possible to update the code, so we can map the CurrentHeaterCoolerState to specific datapoint ? 
In my case its 14, so the current heating status can be properly propagated

**Comment by LiborBaca** [comment]
Well, after few 4 hours of studying I somehow make it working.
Unfortunately in my solution the CurrentHeaterCoolerState is hard coded for datapoint 14, and my values "heating", "no_heating" ... as I mentioned I have 0 experience with JS coding, so I will leave it to professionals, hopefully it can be a good starting point.

Basically I removed :

        service.getCharacteristic(Characteristic.CurrentHeaterCoolerState)
            .updateValue(this._getCurrentHeaterCoolerState(dps))
            .on('get', this.getCurrentHeaterCoolerState.bind(this));

and defined:


        const characteristicCurrentHeaterCoolerState = service.getCharacteristic(Characteristic.CurrentHeaterCoolerState)
        .updateValue(this._getCurrentHeaterCoolerState(dps))
        .on('get', this.getCurrentHeaterCoolerState.bind(this));

included the bellow on device change

            if (changes.hasOwnProperty('14')) {
                const newCurrentHeaterCoolerState = this._getActive(changes['14']);
                if (characteristicCurrentHeaterCoolerState.value !== newCurrentHeaterCoolerState) {
                characteristicCurrentHeaterCoolerState.updateValue(this._getCurrentHeaterCoolerState(state));
                }
            }

and changed getCurrentHeaterCoolerState function

    getCurrentHeaterCoolerState(callback) {
        this.getState(['14'], (err, dp) => {
            if (err) return callback(err);

            callback(null, this._getCurrentHeaterCoolerState(dp));
        });
    }

    _getCurrentHeaterCoolerState(dp) {
        const {Characteristic} = this.hap;
        switch (dp['14']) {
            
            case "heating":
                return Characteristic.CurrentHeaterCoolerState.HEATING;

            case "no_heating":
                return Characteristic.CurrentHeaterCoolerState.IDLE;

        }
    }


File attached.

[SimpleHeaterAccessory.txt](https://github.com/iRayanKhan/homebridge-tuya/files/5398423/SimpleHeaterAccessory.txt)

**Comment by marvelousmo** [comment]
same bug here

**Comment by ElphaX** [comment]
@iRayanKhan happy to code this but I don't have one to test, do you?

**Comment by LiborBaca** [comment]
@ElphaX I can test your code I have the thermostat available ... as I mentioned my dirty solution is working for me but I am sure the code is poorly written as I don't have any experience with JS coding ... in my workaround I manually point the CurrentHeaterCoolerState characteristics for datapoint 14 ... with a proper solution it should be possible for end-user to map it manually for their respective data point ... also my thermostat return heating / no_heating for idle state ... it might be different for other vendors ... so user should be able to change that as well easily:

[TuyaAccessory] SimpleHeater changed: {"1":true,"2":240,"3":225,"4":"Auto","7":false,"13":0,"14":"no_heating"}
[TuyaAccessory] SimpleHeater changed: {"1":true,"2":240,"3":225,"4":"Auto","7":false,"13":0,"14":"heating"}

_getCurrentHeaterCoolerState(dp) {
    const {Characteristic} = this.hap;
    switch (dp['14']) {
        
        case "heating":
            return Characteristic.CurrentHeaterCoolerState.HEATING;

        case "no_heating":
            return Characteristic.CurrentHeaterCoolerState.IDLE;

    }
}

**Comment by ElphaX** [comment]
Looks fine to me, only thing you may need to add are the variables to pull for status string values, but that can work - make a PR. Re-open if relevant

**Comment by EddieDSuza** [comment]
I have a similar model and was able to configure it into HomeKit but thru Siri - it says "Heating To" instead of "Cooling to" - is there a work around ? Please advise as I have a bunch of them in my house 


![WhatsApp Image 2021-12-26 at 8 14 22 PM](https://user-images.githubusercontent.com/52710883/147422203-75969566-070e-480c-8262-18e68e098e78.jpeg)
