### ISSUE TITLE
Wiki documentation updates to cover new Air Purifier accessory type

### ISSUE THREAD

**Issue by dhutchison** [iRayanKhan/homebridge-tuya#142]
As requested on PR #139, attached is a diff for the wiki repository containing the proposed documentation updates. I have tried to follow the existing documentation layout as much as possible. 

If there is anything else you think needs added let me know.  

[airpurifier.patch.txt](https://github.com/iRayanKhan/homebridge-tuya/files/5418985/airpurifier.patch.txt)

**Comment by ElphaX** [comment]
PR #139 Merged

**Comment by ElphaX** [comment]
If I’m not mistaken, you’ve provided wiki updates correct? We’ve got this ready for an upcoming update. 

Let me know if I’ve misunderstood your comment
