### ISSUE TITLE
Smart Life / Tuya garage door opened

### ISSUE THREAD

**Issue by myevit** [iRayanKhan/homebridge-tuya#145]
I've manage to add garage door opener to Homebridge Tuya with this:
```
{
    "platform": "TuyaLan",
    "devices": [
        {
            "name": "Garage Door",
            "type": "GarageDoor",
            "manufacturer": "eWeLink",
            "model": "WiFi Switch Garage Door Controller",
            "id": "XXXXX",
            "key": "XXXXX",
            "dpAction": 1,
            "dpStatus": 2,
            "flipState": true
        }
    ]
}
```
But it doesn't read state of open/close sensor. 

but homebrigde is receiving sensor updates

```
[TuyaAccessory] Heard back from Garage Door with command 8
[TuyaAccessory] GarageDoor changed: {"1":false,"7":0,"101":true,"102":false}
[TuyaAccessory] Heard back from Garage Door with command 8
[TuyaAccessory] GarageDoor changed: {"1":false,"7":0,"101":false,"102":false} 
```
Am I missing something?

**Comment by Faisalthe01** [comment]
https://github.com/iRayanKhan/homebridge-tuya/issues/108

This will fix your issue

**Comment by myevit** [comment]
changed to 101 in dpStatus

```
{
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "Garage Door",
                    "type": "GarageDoor",
                    "manufacturer": "eWeLink",
                    "model": "WiFi Switch Garage Door Controller",
                    "id": "xx",
                    "key": "xx",
                    "dpAction": 1,
                    "dpStatus": 101,
                    "flipState": true,
                    "debug": true
                }
            ]
        }
```
not working. ..
status of door doesn't updating in homekit. also no debug info.

if I add 
                    "pingTimeout": 2147483,
                    "connectTimeout": 2147483,
inn homekit door status stuck on open state

**Comment by Faisalthe01** [comment]
you need to replace your garagedoor file in lib folder with this 
https://github.com/davidh2075/homebridge-tuya/blob/master/lib/GarageDoorAccessory.js

and also remove flipState from your config

**Comment by myevit** [comment]
Works like a charm. 
I thought that .js already was in the repo.... 
Thank a lot!
