### ISSUE TITLE
 Smart Life Garage Opener after reboot loses connection with homebrigde

### ISSUE THREAD

**Issue by myevit** [iRayanKhan/homebridge-tuya#146]
When I reboot Smart Life Garage Opener it loses connection with homebrigde 

```
[TuyaAccessory] Socket had a problem and will reconnect to Garage Door (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
```
Own Tuya app still sees it after reboot and control it

Issue is fixed only after homebridge restart.

**Comment by Faisalthe01** [comment]
https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/173#issuecomment-683639737
