### ISSUE TITLE
SimpleBlinds wrong status

### ISSUE THREAD

**Issue by dmatora** [iRayanKhan/homebridge-tuya#147]
I use blinds controller with window opener.
Sometimes blinds controller will ignore close command and window status becomes closed while window is opened.
That breaks automation, until I manually tell window to open and then to close to sync the status.

Could we have an option for SimpleBlinds module to send close command 1 second before open, and vice versa, to solve wrong status issue?

Should be quick and painless fix

**Comment by ElphaX** [comment]
Is this still an issue? @dmatora 

Closing for now, but feel free to submit a pull request with the fix ;)
