### ISSUE TITLE
Inadequate Setup Instructions

### ISSUE THREAD

**Issue by GioCirque** [iRayanKhan/homebridge-tuya#151]
**Checklist**
- [x] I have read the common issues wiki page
- [x] I have checked to make sure the plugin is up to date

**Describe the bug**
The setup instructions have been simplified to point to a video. The video **ONLY** describes a setup experience from creating a brand new Tuya account by leveraging a "free trial" period. The instructions completely fail for established Tuya accounts which have fallen outside the scope of "free trial". Tuya requires these accounts to be "verified" by creating an application, being assigned an account manager, performing an interview, and then being reviewed for acceptance.

**To Reproduce**

1. Have a Tuya account older than 2 years
2. Attempt to follow along in the video
3. Observe the blocking "verification required" dialog in the Tuya Cloud Development Portal

**Expected behavior**
I would expect setup instructions to be provided without a dependency on any particular external account state/age. I would expect setup instructions to be provided in more than one modality (video + wiki + script + etc.)

**Screenshots**
Here is a screenshot of the blocking dialog which prevents the instructions' execution.
![image](https://user-images.githubusercontent.com/5244282/97724888-82b3b300-1a9b-11eb-9ae3-2e6bf39e17ab.png)

**Environment (please complete the following information):**
 - OS: macOS Catalina 10.15.7 (19H2)
-  iOS version: n/a
-  Homehubs: n/a
 - Node Version: 12.8.3
 - Plugin Version: 1.1.0
-  Accessory Type: n/a

**Additional context**
This is a documentation and supportability issue, not a technical one.

**Comment by GioCirque** [comment]
*Follow-up:* You **CAN** simply create a new Tuya account and complete the setup. You may need an additional email since I cannot find a way to delete a Tuya account.

Seems like poor etiquette to create a new account every time we need to (re)configure.

**Comment by iRayanKhan** [comment]
Yeah man I feel you.

Me, and the Tuya web dev @milo256, are in the works of something. No guarantees or eta's. Tuya's system is really bad, like really really bad. Hoping to resolve this soon, for all Tuya device owners who want integration.
