### ISSUE TITLE
Heat Storm wall heater

### ISSUE THREAD

**Issue by kylebranham67** [iRayanKhan/homebridge-tuya#155]
**Describe your device**
Heat Storm HS-1500-PHX-WIFI Infrared Heater

**Partial Support?**
Does this device work in any fashion in the plugin? 
All functions appear to work with the exception of Power on/off and child lock.  

Power on/off seems to be mapped to child lock.  Unit functions as long as it has already been powered on.  If power button is used via homekit or home bridge,  homebridge crashes and the child safety lock is enabled on the heater.  

**Device Schema**
"platform": "TuyaLan",
    "devices": [
        {
            "name": "Bedroom Heater",
            "type": "Convector",
            "manufacturer": "Heat Storm",
            "model": "PHX-1500 WIFI",
            "id": "removed",
            "key": "removed",
            "dpActive": 7,
            "dpDesiredTemperature": 2,
            "dpCurrentTemperature": 3,
            "dpRotationSpeed": 4,
            "dpChildLock": 6,
            "dpTemperatureDisplayUnits": 19,
            "cmdLow": "Low",
            "cmdHigh": "High",
            "noChildLock": true,
            "noTemperatureUnit": false,
            "minTemperature": 15,
            "maxTemperature": 30,
            "platform": "TuyaLan"
        },
        {
            "name": "Bathroom Heater",
            "type": "Convector",
            "manufacturer": "Heat Storm",
            "model": "PHX-1500 WIFI",
            "id": "removed",
            "key": "removed",
            "dpActive": 7,
            "dpDesiredTemperature": 2,
            "dpCurrentTemperature": 3,
            "dpRotationSpeed": 4,
            "dpChildLock": 6,
            "dpTemperatureDisplayUnits": 19,
            "cmdLow": "Low",
            "cmdHigh": "High",
            "noChildLock": true,
            "noTemperatureUnit": true,
            "minTemperature": 15,
            "maxTemperature": 30,
            "platform": "TuyaLan"
        }
    ]
}

**Additional context**
[TuyaDiscovery] UDP from 192.168.1.16:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.1.4:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.1.24:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.1.16:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.1.4:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.1.24:6667 0x000055aa...0x0000aa55
[TuyaAccessory] Sending Bathroom Heater {"7":true}
[TuyaAccessory] Heard back from Bathroom Heater with command 8

**Comment by kylebranham67** [comment]
Was able to change dpActive to 1 which resolved the power on/off issue.  At this point the TuyaDiscovery issue is all that remains.

**Comment by ElphaX** [comment]
Closed issue until further notice, please create new issue for anything TuyaDiscovery related.
