### ISSUE TITLE
New Device: kogan kettle

### ISSUE THREAD

**Issue by Bad2dabone** [iRayanKhan/homebridge-tuya#158]
Kogan Smart kettle
This device is not supported but have it running as an outlet (on-off)only
But am trying to find a way of getting my device schema 
Everything I have tried so far has failed including Codetheweb Java script

const TuyAPI = require('tuyapi');

const device = new TuyAPI({
  id: 'xxxxxxxxxxxxxxxxxxxx',
  key: 'xxxxxxxxxxxxxxxx',
  ip: 'xxx.xxx.xxx.xxx'});

device.get({schema: true}).then(data => {
  console.log(data);
});

The reason bing I am getting a lot of polling in homebridge logs

[TuyaAccessory] Heard back from Jug with command 8
[TuyaAccessory] Heard back from Jug with command 8
[TuyaAccessory] Heard back from Jug with command 8
[TuyaAccessory] Heard back from Jug with command 8
[TuyaAccessory] Heard back from Jug with command 8
[TuyaAccessory] Heard back from Jug with command 8
[TuyaAccessory] Heard back from Jug with command 8
[TuyaDiscovery] UDP from 192.168.0.67:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.0.67:6667 0x000055aa...0x0000aa55
[TuyaAccessory] Socket had a problem and will reconnect to Jug (ECONNRESET)
[TuyaAccessory] Sending first query to Jug (3.3)
[TuyaAccessory] Heard back from Jug with command 10
[TuyaAccessory] Heard back from Jug with command 8
[TuyaAccessory] Heard back from Jug with command 8
[TuyaAccessory] Heard back from Jug with command 8
[TuyaAccessory] Heard back from Jug with command 8

Any help or push in the right direction would be great

**Comment by Al-Mclean** [comment]
Hi Bad2dabone,

I experienced issues with my Kogan kettle too - the issues and fixes I applied can be found in issues #78 and #117. I hope you can find something in there which is of use (I still get pleanty of polling messages but the reliability is pretty good now).

Best of Luck,

Al

**Comment by ElphaX** [comment]
What device type were you thinking? Switch seems to be the best choice. Does your kettle measure water level and or set/get water temperature?
