### ISSUE TITLE
RGB Control

### ISSUE THREAD

**Issue by J4YRY4N** [iRayanKhan/homebridge-tuya#16]
I have installed a tuya light, and have it under the devices section in the config, but I am not getting any options for colour or brightness in the Home app. 
Great work overall though, I have used this for a power plug switch and a light successfully.

**Comment by codetheweb** [comment]
This package does not currently support color and brightness controls for bulbs, mainly because I don't have any.  I'll welcome any PRs that add support for them though.

**Comment by codetheweb** [comment]
Brightness controls have now been added, check out the new [README](https://github.com/codetheweb/homebridge-tuya) for instructions.

If you can provide the output of the below script I'll look into adding support for RGB bulbs.  Run it a few times changing only the color between runs so we can see what parameter controls it.

```javascript
const TuyAPI = require('tuyapi');

const device = new TuyAPI({
  id: 'xxxxxxxxxxxxxxxxxxxx',
  key: 'xxxxxxxxxxxxxxxx',
  ip: 'xxx.xxx.xxx.xxx'});

device.get({schema: true}).then(data => {
  console.log(data);
});
```

**Comment by Fabinewchurch** [comment]
Thanks for the quick answer.
This might be a silly question, but where exactly am I supposed to paste the script to get the parameters?

**Comment by codetheweb** [comment]
@Fabinewchurch just paste it into a file on your desktop or wherever is convenient.  You'll have to run `npm install tuyapi -g` before you can run it with `node <filename>.js`.

**Comment by Fabinewchurch** [comment]
@codetheweb sorry for the late answer; I tried what you said, but I cant get the script to run; I always get an error saying: "Cannot find module 'tuyapi'" but I already installed it.

**Comment by GioCirque** [comment]
You’ll likely need to

sudo npm install -g tuyapi

node <file name>.js

If that doesn’t work, can you post your console session of the attempt please?

**Comment by codetheweb** [comment]
Mentioning @kalety so they can follow this issue for updates.

@ everyone who's still trying to control RGB bulbs: until such control is implemented in `homebridge-tuya`, you may want to look into using a different plugin [like this one](https://github.com/AMoo-Miki/homebridge-tuya-lan) that supports RGB bulbs out of the box.

**Comment by zysoft** [comment]
@albertsal thank you for your input! I came across the same challenge with lightbulbs and your research helped a lot. I just submitted a pull request with `lightbulb` accessory support. It supports dimming, color temperature, and custom rgb color. You could give it a try if you want, I would appreciate your feedback!

**Comment by codetheweb** [comment]
(I'm copy/pasting this into every open issue and PR.)

This plugin is now deprecated, as I don't have enough time to maintain it along with other TuyAPI related projects. Please use AMoo-Miki's [homebridge-tuya-lan](https://www.npmjs.com/package/homebridge-tuya-lan) plugin instead. (Or, you can continue to use this plugin, but I will not be giving support or adding any new devices.)

I'm sorry about this, but this plugin is taking a disproportionate amount of my time that I believe is better spent making TuyAPI more stable and adding more tools to the ecosystem.

**Comment by iRayanKhan** [comment]
Closing; inactive thread. If you need support please re-open this issue.

This plugin now supports RBW lights.
