### ISSUE TITLE
New Device: HY368 Tuya Wifi ZigBee TRV thermostatic radiator Valve

### ISSUE THREAD

**Issue by jurekjure** [iRayanKhan/homebridge-tuya#160]
HY368 Tuya Wifi ZigBee TRV thermostatic radiator Valve, generic brand with temperature settings.

There is no support, tried with: SimpleHeater, the device does not show up in Hoobs or Homekit

Please print your devices schema below:
(would need some help here, don't know where to get it)

**Additional context**
Device url https://www.aliexpress.com/item/1005001456697590.html?spm=a2g0s.9042311.0.0.b0e54c4dCaRhe9

**Comment by PixelBurstHD** [comment]
In the log of Homebridge when it connects there will be a string output like this - what's yours? 

[12/7/2020, 8:06:03 PM] [TuyaLan] Ready to handle Bedroom Light 2 (RGBTWLight:3.3) with signature {"20":false,"21":"white","22":500,"23":400,"24":"007803e803e8","25":"000e0d0000000000000000c80000","26":0}

Curious if we can get this working as have been eying up the same kit myself and if I can get my air conditioner unit working I'm hopeful for this. Off topic, but were they hard to install? Never really done any plumbing work.

**Comment by jurekjure** [comment]
Hey PixelBurstHD, thanks for the response

Here's the string
08/12/2020, 18:43:03 [TuyaDiscovery] UDP from 192.168.64.148:6667 0x000055aa...0x0000aa55
08/12/2020, 18:43:04 [TuyaLan] Failed to discover Studio heating (bfd160a033ff3dc50bbxwf) in time but will keep looking.

Here's my config
{
    "platform": "TuyaLan",
    "devices": [
        {
            "name": "Studio heating",
            "type": "SimpleHeater",
            "manufacturer": "Tuya",
            "model": "HY368",
            "id": "bfd160a033ff3dc50bbxwf",
            "key": "4f37c9e30baeaf9f"
        }
    ]
}

And the plugin I'm using:
Tuya
1.1.0 published 11/15/2020
🏠 Offical Homebridge plugin for TuyAPI


About the installation. No issues there, simple as cake. If you already have "dumb" thermostat valves you just unhook the old ones and put the new ones on - there is no plumbing work as thermostat valves are just valve regulators - the valve is its own separate thing. But if you don't have them, than you'll need to call the plumber to switch out your valves. This means letting the water out of your system, removing the old valves and installing new ones. It can get quite expensive, but it's possible to do it on your own or with help from a friend. I'm attaching photos of the installed thermostat and the valve (without the thermostat, just with the supplied adapter installed - three different adapters are supplied with every thermostat)

I'll be adding also an electric floor heating controller for my bathroom - also tuya - later.

I recommend the product, it works awesome for me - well for now through the Tuya app ... I hope soon through homekit :)

![tempImageCQW0AU](https://user-images.githubusercontent.com/54580999/101522571-b67dd480-3987-11eb-9b34-bb967d88efb7.gif)

![tempImagelDQKq1](https://user-images.githubusercontent.com/54580999/101522592-bc73b580-3987-11eb-8530-6a107b0c5cb1.gif)

**Comment by jonasophie** [comment]
@jurekjure hello, does it works correctly on your the Home application ?

**Comment by jurekjure** [comment]
It only works as intended by the manufacturer - in the Tuya app

**Comment by jonasophie** [comment]
> It only works as intended by the manufacturer - in the Tuya app

Ok thanks ... :(

**Comment by PixelBurstHD** [comment]
> Hey PixelBurstHD, thanks for the response
> 
> Here's the string
> 08/12/2020, 18:43:03 [TuyaDiscovery] UDP from 192.168.64.148:6667 0x000055aa...0x0000aa55
> 08/12/2020, 18:43:04 [TuyaLan] Failed to discover Studio heating (bfd160a033ff3dc50bbxwf) in time but will keep looking.
> 
> Here's my config
> {
> "platform": "TuyaLan",
> "devices": [
> {
> "name": "Studio heating",
> "type": "SimpleHeater",
> "manufacturer": "Tuya",
> "model": "HY368",
> "id": "REMOVED",
> "key": "REMOVED"
> }
> ]
> }
> 
> And the plugin I'm using:
> Tuya
> 1.1.0 published 11/15/2020
> 🏠 Offical Homebridge plugin for TuyAPI
> 
> About the installation. No issues there, simple as cake. If you already have "dumb" thermostat valves you just unhook the old ones and put the new ones on - there is no plumbing work as thermostat valves are just valve regulators - the valve is its own separate thing. But if you don't have them, than you'll need to call the plumber to switch out your valves. This means letting the water out of your system, removing the old valves and installing new ones. It can get quite expensive, but it's possible to do it on your own or with help from a friend. I'm attaching photos of the installed thermostat and the valve (without the thermostat, just with the supplied adapter installed - three different adapters are supplied with every thermostat)
> 
> I'll be adding also an electric floor heating controller for my bathroom - also tuya - later.
> 
> I recommend the product, it works awesome for me - well for now through the Tuya app ... I hope soon through homekit :)
> 
> ![tempImageCQW0AU](https://user-images.githubusercontent.com/54580999/101522571-b67dd480-3987-11eb-9b34-bb967d88efb7.gif)
> 
> ![tempImagelDQKq1](https://user-images.githubusercontent.com/54580999/101522592-bc73b580-3987-11eb-8530-6a107b0c5cb1.gif)

Edit your comment to remove ID/Key :) I've removed it from this response.

With no response, you aren't getting a signature - is this your first Tuya device or are you already running others?

**Comment by jurekjure** [comment]
Hey, thanks for the response and warning.
I also have a door lock but I never tried integrating it with homebridge. This is the first time.
No I have not reset anything since getting the keys.

Could it be an issue that the thermostat valves are zigbee and connected to a tuya zigbee bridge? Should this bridge be paired with homebridge?

**Comment by PixelBurstHD** [comment]
> Hey, thanks for the response and warning.
> I also have a door lock but I never tried integrating it with homebridge. This is the first time.
> No I have not reset anything since getting the keys.
> 
> Could it be an issue that the thermostat valves are zigbee and connected to a tuya zigbee bridge? Should this bridge be paired with homebridge?

Sadly no hands on experience with them myself yet but I would think so? It might be worth checking out the Discord to see if anyone else has linked them to be honest. it's a bit more active than Github for people that dont have issues :)
