### ISSUE TITLE
simpledimmer not dimming

### ISSUE THREAD

**Issue by Gromga** [iRayanKhan/homebridge-tuya#161]
**Checklist**
- [X] I have read the common issues wiki page
- [X] I have checked to make sure the plugin is up to date

**Describe the bug**
The dimmer function doesn't work on homekit. The lights are either on (regardless of brightness value on the slider) or closed.
Also, when the light is on and looking at the slider for brightness, the light icon is crossed (see screenshot).

**To Reproduce**
Nothing specific, they don't dim consistently.

**Expected behavior**
The light should be able to me dimmed.

**Screenshots**
![Capture d’écran, le 2020-11-26 à 17 04 15](https://user-images.githubusercontent.com/34313362/100393982-876f7680-3009-11eb-8eb0-d05fd1bd268e.png)

**Environment (please complete the following information):**
 - OS: Raspbian GNU/Linux Buster (10)
-  iOS version:14.2.1
-  Homehubs: Homepod (iOS 14.2)
 - Node Version: 14.15.1
 - Plugin Version: 1.1.0
-  Accessory Type: simpledimmer

**Additional context**
Here's what show's up in the log:
[TuyaAccessory] Sending Chambre d’ami {"1":true}
[TuyaAccessory] Sending Chambre d’ami {"2":255}
[TuyaAccessory] Sending Chambre d’ami {"1":true}
[TuyaAccessory] Sending Chambre d’ami {"2":202}
[TuyaAccessory] Sending Chambre d’ami {"1":true}
[TuyaAccessory] Sending Chambre d’ami {"2":154}
[TuyaAccessory] Sending Chambre d’ami {"1":true}
[TuyaAccessory] Sending Chambre d’ami {"2":197}
[TuyaAccessory] Sending Chambre d’ami {"1":true}

Here's the available information for the device on iot.tuya.com:
![Capture](https://user-images.githubusercontent.com/34313362/100376012-ad474c00-3006-11eb-8a79-eb2829dcdc4e.PNG)

**Comment by InwardOutward** [comment]
I'm seeing the same issue as Gromga on my iOS device.
I'm also seeing the same behavior in the homebridge UI.

**Checklist**
I have read the common issues wiki page
I have checked to make sure the plugin is up to date

**Describe the bug**
On iOS same as Gromga.
The dimmer function additionally does not work in homebridge UI. When the device is on, the brightness value is always displayed as "-11%".

**Environment**
OS: Windows 10 (Build 19042)
iOS: 14.2
Node Version: 14.15.3
Homebridge Version: 1.2.4
Plugin Version: 1.1.0
Accessory Type: simpledimmer

**Secreenshot**
The screen on my iOS device is identical to Gromga's

In the accessories panel in homebridge UI, when the device is on, the brightness value is always displayed as "-11%"
![image](https://user-images.githubusercontent.com/76496124/102930316-2ac97500-446a-11eb-95ff-9902212323c4.png)

**Log output**
[TuyaAccessory] Sending Hallway {"1":true}
[TuyaAccessory] Sending Hallway {"2":255}
[TuyaAccessory] Heard back from Hallway with command 8
[TuyaAccessory] Sending Hallway {"2":172}
[TuyaAccessory] Sending Hallway {"2":32}
[TuyaAccessory] Sending Hallway {"2":195}
[TuyaAccessory] Sending Hallway {"2":25}
[TuyaAccessory] Sending Hallway {"1":false}
[TuyaAccessory] Heard back from Hallway with command 8
[TuyaAccessory] Sending Hallway {"1":true}
[TuyaAccessory] Heard back from Hallway with command 8
[TuyaAccessory] Sending Hallway {"1":false}
[TuyaAccessory] Heard back from Hallway with command 8

![image](https://user-images.githubusercontent.com/76496124/102931072-ae379600-446b-11eb-9e0b-b247b5a22e4a.png)

**Comment by jdtsmith** [comment]
This is probably an issue mapping the 0-100% range of Homekit to the Tuya dimmer's brightness numbers, which for me go from 10–1000.  I added:

```
	  "minBrightness": 10,
	  "scaleBrightness": 1000
```

to each dimmer's device stanza in the config file and this fixed it nicely.  Note that first I "unlocked" the dimming range to go down to 1% by pairing the devices in the uComen app.  If you want to stick with another lower dimming limit, like 10%, change `minBrightness` accordingly (e.g. 100).

**Comment by iRayanKhan** [comment]
Closing: Inactive, and solution provided.

If you are still experiencing this issue, please re-open.

**Comment by Gromga** [comment]
I've tried what was proposed by @jdtsmith. It didn't fix the issue. However the in-app light bubble image on the slider that was previously "slashed" regardless of brightness level now shows up as a light bubble when it's lit.

@jdtsmith I'm using the CE Smart app. So I'm not sure about the unlocking part. 

@iRayanKhan Is there any information that you would need ?

**Comment by jdtsmith** [comment]
Did you install [tuya-cli](https://github.com/TuyaAPI/cli)?  With it, you can query your dimmer for its parameters with:

```
% tuya-cli get --id XXX --key XXX --ip 192.168.0.XXX --protocol-version 3.3 -a
```

I get:

```
{
  devId: 'XXX',
  dps: { '1': true, '2': 10, '3': 10, '4': 'LED', '102': 0 }
}
```

Try changing your brightness on the switch manually from lowest to highest and seeing what the `'2'` field changes to afterwards.  That's your `minBrightness` and `scaleBrightness`.  

`dps '3'` is the minimum dimmer value, which you can set even without an app:

```
% tuya-cli set --id XXX --key XXX --ip 192.168.0.XXX --protocol-version 3.3 --dps 3 --set 10
```

For me it defaulted to 100 (i.e. 10% minimum brightness).

**Comment by Gromga** [comment]
Weird, my second message didn't got posted. After posting my previous message i found the solution for me.
```
"dpBrightness": 3,
"minBrightness": 25,
"maxBrightness": 255
```

**Comment by jdtsmith** [comment]
Yeah it seems some dimmers go to 1000, others go to 255.  You may be able to unlock lower minimum brightness using the method mentioned above.
