### ISSUE TITLE
how to pause/stop blinds

### ISSUE THREAD

**Issue by chetoile98** [iRayanKhan/homebridge-tuya#162]
hi,

I installed the plugin and it's working great with my blinds, I can open and close it with no problems, but I can't find a way to pause/stop it on home app when I'm opening it or closing it.

does anyone know how to do it ?

here's an example of my conf
                    "name": "Living room shutter",
                    "type": "SimpleBlinds",
                    "manufacturer": "LoraTap",
                    "model": "Curtain Switch Module",
                    "id": "XXXXX",
                    "key": "XXXXX",
                    "timeToOpen": 28,
                    "timeToTighten": 6

homebridge-tuya v1.1.0
Node.js v14.15.1
npm v6.14.8
homebridge v1.2.3

thanks for your help

**Comment by chetoile98** [comment]
I already tried the suggestions on issue #66 and issue #153 but didn't work :(

there's a way to create a button to pause/stop the blinds ?

thanks once again

**Comment by iRayanKhan** [comment]
Currently In HomeKit you can't pause the blinds movement, I don't have any plans to add a stop function, but if someone is willing to make a PR, I would be more than happy to merge it in.

**Comment by ElphaX** [comment]
Please re-open this issue if relevant.
