### ISSUE TITLE
Bluetooth Gateway 

### ISSUE THREAD

**Issue by jens-o** [iRayanKhan/homebridge-tuya#164]
**Describe your device**
Bluetooth gateway. 

Not sure if devices connected via a Bluetooth gateway is already supported but at least I cannot get it working.

**Partial Support?**
N/A

**Device Schema**
N/A

**Additional context**
When I retrieve the keys for my devices (using tuya-cli) I only get a key for the gateway. My Light device is in the list but has no key.  I have tried using the gwId parameter in my Homebridge but can't get it working.

**Comment by iRayanKhan** [comment]
Hello @jens-o, I currently don't have plans to add bluetooth support with this plugin. There are currently home bridge bluetooth plugins that may work for your gateway, but it may not expose the devices connected to the gateway.

This may be what you are looking for: https://github.com/vojtamolda/homebridge-bluetooth 

Good luck!

**Comment by jens-o** [comment]
Thank you for the response, then I at least know that this plugin doesn't support gateways. I will have look at the Bluetooth plugin.

But it is a Tuya gateway that I use to connect to Tuya bluetooth devices and I can connect to them from Google Home using the Tuya integration so think it could be in the scope of this plugin. I will investigate further how to connect to the devices and get back if find out.

**Comment by bkarlson** [comment]
Would be nice to add it to README, as I just spent 1/2 day trying to figure out why BLE devices connected via gateway/hub do not work.
