### ISSUE TITLE
Simple Heater - temperature issues

### ISSUE THREAD

**Issue by kaloczidev** [iRayanKhan/homebridge-tuya#166]
**Checklist**
- [x] I have read the common issues wiki page
- [x] I have checked to make sure the plugin is up to date

**Describe the bug**
I am mapping my device to a simpleHeater accessory.

After setting the temperature for the thermostat (e.g.: to 22.5C), it will set to the max value in HomeKit. Sometimes (I haven't find out when and how - investigation in progress) it also send it to the thermostat. 
Setting values on the device itself will update the HomeKit information to the correct values.

Often (Still investigating the reason) it will reads the currentTemperature as 100C. 

**To Reproduce**
See above.

**Expected behavior**
Setting temperature values won't send/set the max value.

**Screenshots**

![RPReplay_Final1607770180](https://user-images.githubusercontent.com/9059270/101982074-da843300-3c71-11eb-8c1c-24828fc85023.gif)

**Environment (please complete the following information):**
 - OS: Raspbian Homebridge
 - Plugin Version: 1.1.0
-  Accessory Type: simpleHeater

**Additional context**
Discovered the schema with tuyapi, found these datapoints with meaning:
```js
dps: {
    '1': true, // physically on/off state 
    '2': 215, // target temp.
    '3': 210, // current temp.
    '4': 'Eco', // operating mode (manual, eco, and program)
    '7': false, // child lock state
    '13': 8, // 
    '14': 'heating' // heating state, no_heating if its not heating
  }
```
Current config:
```json

  "name": "Kitchen heating panel",
  "type": "SimpleHeater",
  "manufacturer": "BVF",
  "model": "NG800",
  "id": "x",
  "key": "x",
  "dpActive": 1,
  "dpDesiredTemperature": 2,
  "dpCurrentTemperature": 3,
  "minTemperature": 15,
  "maxTemperature": 32,
  "temperatureDivisor": 10,
  "minTemperatureSteps": 0.5
```

**Comment by ElphaX** [comment]
Please let us know if this issue still exists after you use the latest update of the plugin :)
