### ISSUE TITLE
Better documentation for Homebridge json config

### ISSUE THREAD

**Issue by ciavez** [iRayanKhan/homebridge-tuya#172]
hi,
it took me a while to configure the TECKIN smart socket. 
I believe some complete and not PARTIAL examples are required in the home page. 
like this one

{
            "platform": "TuyaLan",
            "name": "TuyaLan",
            "devices": [
                {
                    "name": "T1",
                    "type": "Outlet",
                    "manufacturer": "TECKIN",
                    "model": "Wifi Smart Socket",
                    "id": "XXXXX",
                    "key": "YYYYY"
                }
            ]
        }

**Comment by iRayanKhan** [comment]
That's what the wiki is for 🙂

New readME soon.
