### ISSUE TITLE
im new to homebridge, how do it do anything? i did some of those advanced hacker sht you programmers do but my devices arent in the home app. what do i do in the config editor? 

### ISSUE THREAD

**Issue by kvn8888** [iRayanKhan/homebridge-tuya#173]
![SharedScreenshoot](https://user-images.githubusercontent.com/77308744/104257189-db63dc80-544a-11eb-91c9-2a3705ca4b12.jpg)

**Comment by AnonymousPea** [comment]
Are you using the Tuya Web Plug in or the Tuya plug in?

From the picture it shoes the Tuya Web Plug In, but this area is for the Tuya plug in. Can you show what the plug ins you have are?

**Comment by iRayanKhan** [comment]
Wrong repo 😅
