### ISSUE TITLE
Failed to discover

### ISSUE THREAD

**Issue by wasza12** [iRayanKhan/homebridge-tuya#181]
Hi,

I bought this device https://www.aliexpress.com/item/32997953761.html?spm=a2g0s.9042311.0.0.27424c4dTPPkP6. I was able to get in working flawlessly with homekit using this plugin, but yesterday, it stopped working. I'm still able to control the device using the Tuya app, but the homebridge fails to discover it and it shows up in homekit with "No Response" tag. These are relevant logs:

18/01/2021, 14:53:03 Loaded plugin 'homebridge-tuya'
18/01/2021, 14:53:03 [1/18/2021, 6:53:03 AM] Registering platform 'homebridge-tuya.TuyaLan'
18/01/2021, 14:53:03 [TuyaLan] Initializing TuyaLan platform...
18/01/2021, 14:53:03 [TuyaLan] Marked Garage door opener unreachable by faulting Service.Garage door opener.Target Door State
18/01/2021, 14:53:03 [TuyaLan] Starting discovery...
18/01/2021, 14:53:03 [TuyaDiscovery] Discovery started on port 6666.
18/01/2021, 14:53:03 [TuyaDiscovery] Discovery started on port 6667.
18/01/2021, 14:54:03 [TuyaLan] Failed to discover Garage door opener (2003646010521cc78b65) in time but will keep looking.

This is my config:
{
    "platform": "TuyaLan",
    "devices": [
        {
            "name": "Garage door opener",
            "type": "GarageDoor",
            "manufacturer": "Woltea",
            "model": "WiFi Switch Garage Door Controller",
            "id": "2003646010521cc78b65",
            "key": "xxxxx"
        }
    ]
}
Any ideas how to fix it?

**Comment by ElphaX** [comment]
Please confirm if this issue still exists, often the device can't respond fast enough due to network connectivity problems.
