### ISSUE TITLE
New Device: Proscenic 850T Robot Vacuum

### ISSUE THREAD

**Issue by jpsmith16** [iRayanKhan/homebridge-tuya#185]
**Describe your device**
Robot Vacuum - Proscenic 850T - while Proscenic is the manufacturer, I have it set up within the Tuya app / IoT Platform

**Partial Support?**
When I set up as one of the currently Supported Devices, the vacuum will appear in HomeKit, however device will not operate 

**Device Schema**
Apologies, but have been looking up how to obtain this and can't find. If someone could point me as to how I can get this, I can share?

**Additional context**
I have the vacuum connected to Home Assistant, and then into HomeKit using Home Assistant bridge. It appears as a switch and allows me to turn the vacuum on & off which is all I need. Looking to see if it can be supported within this Homebridge plugin, so I could remove the Home Assistant bridge

**Comment by ElphaX** [comment]
Please try using the Tuya Dev Portal, and you find your schema. This will be needed to make your config work correctly.

Still an issue? Please re-open if relevant.
