### ISSUE TITLE
Adaptive lighting support?

### ISSUE THREAD

**Issue by ilitchmax** [iRayanKhan/homebridge-tuya#187]
Hello,
I'm currently using your plugin with many bulbs defined as `RGBTWLight`. It's working perfectly, but is it any chance you'll add adaptive lightning support? It was introduced in 1.3.0 version of homebridge. Here is the [link](https://developers.homebridge.io/HAP-NodeJS/classes/adaptivelightingcontroller.html) for hap-nodejs class description.

**Comment by tom-23** [comment]
@ilitchmax The feature has been merged into the master and published to NPM. Updating the plugin should allow for the adaptive lighting feature to be enabled.
