### ISSUE TITLE
Simpleheater

### ISSUE THREAD

**Issue by Przylepzwm** [iRayanKhan/homebridge-tuya#188]
Is it possible to correct the status of the icon in the Home app for SimpeHeater. It currently works like this: 
-When the thermostat is off, the icon is gray (that's ok).  
-When it is on, the icon is orange and the status is heating - even when the set temperature is lower than the current temperature.  

In this case, you can display a green icon?

**Comment by Przylepzwm** [comment]
little update.  
The icon is green when: 
-I will turn off the thermostat with the temperature setpoint lower than the current one.  
-Restart Home applications.  
-Turn on the thermostat again.  

Reaching the set temperature, without the above steps, will not update the icon and the status "heating" in Home app.

**Comment by LiborBaca** [comment]
Same as :

https://github.com/iRayanKhan/homebridge-tuya/issues/140

My java coding skills are 0, but I have attached my workaround there, so you can try my version of file.

**Comment by iRayanKhan** [comment]
@LiborBaca would you consider making the name SimpleHeaterAccessory2, and making a PR? Beside to define it in index.js too. I will merge it in, or can do it manually if you'd like.

**Comment by ElphaX** [comment]
@Przylepzwm Please let us know if there any updates on this issue? ty
