### ISSUE TITLE
Can't get adaptive lightning working

### ISSUE THREAD

**Issue by ilitchmax** [iRayanKhan/homebridge-tuya#189]
**Checklist**
- [x] I have read the common issues wiki page
- [x] I have checked to make sure the plugin is up to date

**Describe the bug**
Adaptive lightning appeared nowhere. 

**To Reproduce**
Add RGBTWLight to homebridge
Connect it to homekit

**Expected behavior**
Bulb will have an adaptive lightning feature 

**Environment (please complete the following information):**
 - OS: Raspberry OS last version
-  iOS version: 14.4
-  Homehubs: Homebridge v1.3.0-beta.47
 - Node Version: v14.15.3
 - Plugin Version: 1.3.0
-  Accessory Type: RGBTWLight

**Additional context**
I already restarted and reinstalled homebridge.
Everything else is working great. Like brightness, colour, temperature control.

The config I'm using for my bulb is:
```
{
                    "name": "BulbOne",
                    "type": "RGBTWLight",
                    "manufacturer": "Yandex",
                    "model": "YaBulb",
                    "id": "***",
                    "key": "***",
                    "dpPower": "20",
                    "dpMode": "21",
                    "dpBrightness": "22",
                    "dpColorTemperature": "23",
                    "dpColor": "24",
                    "maxWhiteColor": "221",
                    "colorFunction": "HSB",
                    "minBrightness": 10,
                    "scaleBrightness": 1000,
                    "scaleWhiteColor": 1000
                }
```

**Comment by tom-23** [comment]
@ilitchmax what HomeKit hub are you using? It must be updated to iOS 14.

**Comment by PixelBurstHD** [comment]
> HomeKit hub

Just to clarify as I think this is why I have this issue too - this feature requires an Apple TV/Homepod the same way other Homekit features do?

**Comment by tom-23** [comment]
@PixelBurstHD Yes, exactly. You need one to send the commands over to HomeBridge to change the lights automatically. I've tried using a jailbroken iPhone to do this running iOS 14 but didn't manage to get the adaptive lighting to work so your only option is to go with one of the official solutions. (Cheapest at the moment is a HomePod Mini)

**Comment by PixelBurstHD** [comment]
Figured as much thanks! Probably OP's problem as well. I've been on the fence for a while but this is the reason!
