### ISSUE TITLE
Crash and incompatibility/inconsistency

### ISSUE THREAD

**Issue by LewisSpring** [iRayanKhan/homebridge-tuya#193]
**Checklist**
- [x] I have read the common issues wiki page
- [x] I have checked to make sure the plugin is up to date

**Describe the bug**
Some sort of incompatibility with a single plug and crash

Left idle

Try to use socket:
- Slow Response
- Times out
- "No response"
- See log errors

I've also changed the name of the socket in configuration (not in Home or Smart Life) and while the Log shows the correct name, the Home app shows the old name.

**Log**
Crash: https://gist.github.com/LewisSpring/2056d49a3b085d09ddd0685440d3f2a6
Running with errors: https://gist.github.com/LewisSpring/b74086cca127237bf88e820d0b6530dc

**Environment (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 Buster 5.4.83-v7+ arm
-  iOS version: 14.4
-  Homehubs: Yes
 - Node Version: 14.15.1
 - Plugin Version: 1.3.0
-  Accessory Type: Smart socket

**Additional context**
I have other plugs of the same and similar model that do not exhibit the behaviour

**I know the crash might infact be related to TPLinkSmartHome, but I've sent it here first since i've been having issues**

Config https://gist.github.com/LewisSpring/f99301efdede046ed4a575628325258b
I've reset the plug - same problem

**Comment by LewisSpring** [comment]
Update:
Two other switches have had this error now.
![image](https://user-images.githubusercontent.com/40576482/106614186-eea62b80-6562-11eb-82c7-c7f2fc23c981.png)

There was a `FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory` a couple hours ago too, but I don't know if that's homebridge-drayton-wiser or this plugin.

**Comment by LewisSpring** [comment]
It seems to get into a loop of this - just perpetual reconnect and problem errors

**Comment by LewisSpring** [comment]
![image](https://user-images.githubusercontent.com/40576482/106730156-2f0ab580-6606-11eb-9638-cb1f25cf5450.png)
[Copy of messages from gist errors2]

I've tried a fresh version of Homebridge (not HOOBs - no spare Pi) and same behaviour is happening.

**Comment by LewisSpring** [comment]
@esgie I think my device can handle multiple connection - since with Homebridge running the app and Homebridge work simulatenously.
On that note, the plug seems to work fine suddenly on that new Homebridge instance. I'll monitor it.

**Comment by LewisSpring** [comment]
There was a bit of
`[TuyaAccessory] Socket had a problem and will reconnect to Desk Lamp (ECONNRESET)
[TuyaAccessory] Sending first query to Desk Lamp (3.3)
[TuyaAccessory] Socket had a problem and will reconnect to Desk Lamp (Error: ERR_PING_TIMED_OUT)
[TuyaAccessory] Socket had a problem and will reconnect to Desk Lamp (Error: ERR_CONNECTION_TIMED_OUT)
[TuyaAccessory] Sending first query to Desk Lamp (3.3)
[TuyaAccessory] Desk Lamp (3.3) didn't respond with its current state.`
but now seems to have stabilised and works fine. I might have to add the other plugs and see if it destabiles

**Comment by LewisSpring** [comment]
With all the plugs added on the new homebridge instance - it seems to work perfectly fine.
I might move to homebridge instead - maybe that's the solution and there's an incompatibillity with HOOBS?
The only other difference I'm running HOOBS on a Pi 3B and Homebridge on a VMWare VM.

**Comment by LewisSpring** [comment]
![image](https://user-images.githubusercontent.com/40576482/106733372-b86fb700-6609-11eb-9db2-aade7407ada5.png)
Back to this again after rebooting the VM OS, but seems to go away after using the socket.

**Comment by LewisSpring** [comment]
There is still a loop issue within HOOBS,
I plugged a smart plug in for a while, and unplugged it.
I just loaded the log window, and saw (green), and then a few seconds later the crash happened (or it just loaded?)
I don't know which plugin to blame. I did have an internet outage.
![Untitled](https://user-images.githubusercontent.com/40576482/107029163-8182d800-67a6-11eb-9451-349630adcaaa.jpg)

**Comment by LewisSpring** [comment]
Looks like the Homebridge VM had the same issue, so this looping is a plugin issue.

**Comment by LewisSpring** [comment]
Just found a stack trace at the top of the Homebridge VM log from before I restarted it.
![image](https://user-images.githubusercontent.com/40576482/107029733-6c5a7900-67a7-11eb-9ed1-b6329d1425dd.png)
I think the crash is coming from this plugin, the VM only has tuya.

**Comment by LewisSpring** [comment]
@iRayanKhan Ping as advised in the readme.

**Comment by LewisSpring** [comment]
I've installed Homebridge on my Pi. I've made a copy of the HOOBs install.
Will monitor for issues.

**Comment by LewisSpring** [comment]
Homebridge is a lot more stable. By a long shot.
But the plugin will still loop if it cannot reach a device.
It normally loops on one device too: my case, the desk lamp

**Comment by zs-jakob** [comment]
I still have the same problem. Kills my RPZero and hogs the CPU – 100% load, rendering all accessories unavailable.

```
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Socket had a problem and will reconnect to Bedroom light (ETIMEDOUT)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
```

**Comment by zs-jakob** [comment]
The device above (Bedroom light) is an RGB bulb. Whenever someone turns off the power (i.e. wall switch), it becomes inaccessible. The Tuya platform should slow down the retries to once every 5 or 10 seconds. I'm running Homebridge on a Raspberry Pi Zero.

**Comment by iRayanKhan** [comment]
Can you try V2.x please?

**Comment by LewisSpring** [comment]
> Can you try V2.x please?

Getting a spam of:
`[Tuya DEBUG] decrementing this._connectionAttempts, currently 3
[Tuya] Socket had a problem and will reconnect to Spare Relay (EHOSTUNREACH)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya] Socket had a problem and will reconnect to Spare Relay (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Spare Relay
[Tuya DEBUG] decrementing this._connectionAttempts, currently 4
[Tuya DEBUG] decrementing this._connectionAttempts, currently 3
[Tuya] Socket had a problem and will reconnect to Spare Relay (EHOSTUNREACH)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya] Socket had a problem and will reconnect to Spare Relay (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Spare Relay
[Tuya DEBUG] decrementing this._connectionAttempts, currently 4
[Tuya DEBUG] decrementing this._connectionAttempts, currently 3
[Tuya] Socket had a problem and will reconnect to Spare Relay (EHOSTUNREACH)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya] Socket had a problem and will reconnect to Spare Relay (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Spare Relay
[Tuya DEBUG] decrementing this._connectionAttempts, currently 4
[Tuya DEBUG] decrementing this._connectionAttempts, currently 3
[Tuya] Socket had a problem and will reconnect to Spare Relay (EHOSTUNREACH)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya] Socket had a problem and will reconnect to Sp`
The relay in question is offline.

**Comment by iRayanKhan** [comment]
Going to add better debug flagging in V2.2 or 2.3.

**Comment by LewisSpring** [comment]
The "Characteristic value expected boolean and received undefined" error is quite prominent. It spams the log.

**Comment by iRayanKhan** [comment]
> The "Characteristic value expected boolean and received undefined" error is quite prominent. It spams the log.

That's a homebridge error. I don't have every device type so fixing these errors isn't guaranteed, I'll still try though.

**Comment by zs-jakob** [comment]
Thank you for all your hard work on this plugin! I'll update the plugin in Homebridge and let you know how it works.

**Comment by shivanathd** [comment]
i still have this issue and couldnt fix it .. please any help would be appreciated
