### ISSUE TITLE
Adaptive Lighting

### ISSUE THREAD

**Issue by jeylites** [iRayanKhan/homebridge-tuya#194]
Hi @iRayanKhan 

I see you have added Adaptive lighting to ver1.3, how do you get this component to work? 

I don’t see it show up in HomeKit.

**Comment by iRayanKhan** [comment]
Hey @jeylites,

To get adaptive lighting to show up in the Home app please be sure to have the following:

* A HomeHub running iOS 14.2+, tvOS 14.2+, audioOS 14.2+ (Latest is 14.4)
* Homebridge beta v1.3.0
* Plugin version v1.3.0
* RGBTW, or TW bulb.

**Comment by jeylites** [comment]
@iRayanKhan Got it to work, had to update to Homebridge beta v1.3.0. Thank you!
