### ISSUE TITLE
Error message when running tuya-cli wizard

### ISSUE THREAD

**Issue by livedurham** [iRayanKhan/homebridge-tuya#199]
Hi, 
After successfully installed the plugin and ran tuya-cli wizard, then I got this message: 
"There was an issue fetching that device. Make sure your account is linked and the ID is correct."
![image](https://user-images.githubusercontent.com/78651706/107872346-b8fb2e00-6ee4-11eb-8581-dc92d412ea9e.png)

**Comment by JPlexer** [comment]
Before you run "tuya-cli wizard" make sure you go to your iot site, go into API Group, and make sure you apply for: Authorization management, Device Management, Device Control. You don't need premium to do get these, just tap the "Apply" button to the right and give them a reason. It will be accepted immediately.

**Comment by iRayanKhan** [comment]
Hey @livedurham, this issue doesn't belong here, rather the Tuya-cli repo. 

@JPlexer is correct in to ensure all permissions are granted, as I ran into this issue prior.
