### ISSUE TITLE
Logging Inconsistency & Brightness Characteristic Supplied Illegal Value

### ISSUE THREAD

**Issue by Wraith324** [iRayanKhan/homebridge-tuya#203]
I'm seeing logging come across three different ways. One from homebridge-tuya, one from TuyaAccessory, and another from TuyaLan.  The TuyaAccessory doesn't have a timestamp like the others.  Can we get more consistent with this?  Also, I'm not sure what is causing the 'Brightness': characteristic was supplied illegal value error.  All devices are Feit Electric Dimmers from Costco. That error started a couple weeks ago. Prior to that I never saw it.

- [2/18/2021, 5:06:38 PM] [homebridge-tuya] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -1 exceeded minimum of 0. See https://git.io/JtMGR for more info.
- [TuyaAccessory] Heard back from Dimmer - Office with command 8
- [2/18/2021, 4:59:50 PM] [TuyaLan] Ready to handle Plug-3 (Floor Lamp) (Outlet:3.3) with signature {"1":false,"9":0,"38":"off"}

**Comment by iRayanKhan** [comment]
Thanks for reporting this. Will be fixed in V2

**Comment by sushenmathur** [comment]
Just checking if this has been fixed.
I've added a TWLight with config below and I keep getting this error 

{
                    "type": "TWLight",
                    "name": "Corridor Downlight",
                    "id": "xxx",
                    "key": "xxx",
                    "manufacturer": "Genio",
                    "model": "CCT Downlight",
                    "dpPower": 20,
                    "dpBrightness": 22,
                    "dpColorTemperature": 23,
                    "minWhiteColor": 10,
                    "maxWhiteColor": 1000
                },
