### ISSUE TITLE
Sytem crashes because of RAM Overload

### ISSUE THREAD

**Issue by MarkM500** [iRayanKhan/homebridge-tuya#208]
**Checklist**
- [x ] I have read the common issues wiki page
- [ x] I have checked to make sure the plugin is up to date

**Describe the bug**
Error in Homebridge Protokoll. Over hours too much RAM load at synology.
"[TuyaAccessory] Operating system complained of resource exhaustion; did I open too many sockets?"

**Environment (please complete the following information):**
 - OS: Homebridge 1.30
-  iOS version:
-  Homehubs: 
 - Node Version: 
 - Plugin Version: back from 1.40 to 1.30 because of #205
-  Accessory Type

Hope you can help. Because the hole system crashes because of RAM-Overload.

Thanks.
Mark

**Comment by ElphaX** [comment]
This is homebridge or device related, not the plugin it seems.
