### ISSUE TITLE
Understanding of tuya commands, schema, etc.

### ISSUE THREAD

**Issue by MarkM500** [iRayanKhan/homebridge-tuya#210]
Hi together,

as I wrote issues about my problems :-), I determined that I need to understand some more circumstances.
So I have to learn ;-) and need your help, because I didn't find the infos otherwise.

**Problem:**
Lot of command 8 messages of my tuya devices ->RAM Oveflow
One Example is Gosund SP112, configured like this:

```
 "name": "Küche Ecke",
                    "type": "CustomMultiOutlet",
                    "manufacturer": "Gosund 112",
                    "model": "Wifi Mini Smart Life Outlet",
                    "id": "xxx",
                    "key": "xxx",
                    "ip": "xxx",
                    "outlets": [
                        {
                            "name": "Schuko",
                            "dp": 1
                        },
                        {
                            "name": "USB",
                            "dp": 7
                        }
```

**Help to understand:**
1. Command 08 means - State Query - No response -> Tuya device has a problem to connect correctly, also if the function is OK. Right?
2. Since Tuya 3.12 additional infos to command 8 in the protocol of homebridge is not shown anymore, like command 8 (value1, value2,..) ->Right?
3. So my questions:
  a) How I can identify the command 8 issue, so to see what's wrong and to fix it?
  b) I read that the schema of the device helps. With which program I'm able to read the schema of the device? 
  c) Other informations I need to help to solve the command 8 issue?

Thanks a lot for your help to understand more.
Mark

**Comment by JanMostert** [comment]
Have the same problem. A device is not working okay. I am not afraid to do some debugging etc, but have no clue how to start with it. Have years of experience in programming, but not with java. I really would like to have a starting point like info how to communicate with devices. I am surprised that there is no tool that is able to diagnose a device.

**Comment by PixelBurstHD** [comment]
Once you've configured the basic requirements including ID and Key upon connecting your devices will spit out the schema in the homebridge logs like  so

`[3/13/2021, 1:40:26 AM] [TuyaLan] Ready to handle Floor Lamp (RGBTWLight:3.3) with signature {"20":true,"21":"white","22":410,"23":102,"24":"000003e803e8","25":"000e0d0000000000000000c80000","26":0}`

This is a bulb, so for this one - 20 is the data point for on/off, 21 is white or colour, 22 is brightness, 23 is colour temperature and  24 is  is the colour. You can  experiment to work out what's what pretty fast, then most devices use similar configs. I've got a bunch of bulbs that run with this, and a bunch that run default. My config then looks like this for this particular bulb and others like it:

                {
                    "name": "Floor Lamp",
                    "type": "RGBTWLight",
                    "manufacturer": "CheapBulb",
                    "model": "Smart Wifi Bulb Socket E27",
                    "id": "MYID",
                    "key": "MYKEY",
                    "dpPower": 20,
                    "dpMode": 21,
                    "dpBrightness": 22,
                    "dpColorTemperature": 23,
                    "dpColor": 24,
                    "colorFunction": "HSB"
                }

I hope this helps you both with the starting point you need 👍

**Comment by JanMostert** [comment]
Ok, now I start to understand how it works. In your example you use attributes/properties like dpPower and dpMode. These belong to the type RGBTWLight. Where can I find a list of attributes/properties for the type SimpleBlinds or SimpleBlinds2?

Groet,
Jan Mostert

**Comment by PixelBurstHD** [comment]
Some devices lack configurable DP's but there is a big update coming

> Ok, now I start to understand how it works. In your example you use attributes/properties like dpPower and dpMode. These belong to the type RGBTWLight. Where can I find a list of attributes/properties for the type SimpleBlinds or SimpleBlinds2? Groet, Jan Mostert
> […](#)
> Op 13 mrt. 2021 om 02:51 heeft PixelBurstHD ***@***.***> het volgende geschreven: ﻿ Once you've configured the basic requirements including ID and Key upon connecting your devices will spit out the schema in the homebridge logs like so [3/13/2021, 1:40:26 AM] [TuyaLan] Ready to handle Floor Lamp (RGBTWLight:3.3) with signature {"20":true,"21":"white","22":410,"23":102,"24":"000003e803e8","25":"000e0d0000000000000000c80000","26":0} This is a bulb, so for this one - 20 is the data point for on/off, 21 is white or colour, 22 is brightness, 23 is colour temperature and 24 is is the colour. You can experiment to work out what's what pretty fast, then most devices use similar configs. I've got a bunch of bulbs that run with this, and a bunch that run default. My config then looks like this for this particular bulb and others like it: { "name": "Floor Lamp", "type": "RGBTWLight", "manufacturer": "CheapBulb", "model": "Smart Wifi Bulb Socket E27", "id": "MYID", "key": "MYKEY", "dpPower": 20, "dpMode": 21, "dpBrightness": 22, "dpColorTemperature": 23, "dpColor": 24, "colorFunction": "HSB" } I hope this helps you both with the starting point you need 👍 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Some device configurations lack configurable data points at the moment, you can dive into the accessory JS to play around until it is possible from the normal config. (Had to do the same with my Air Conditioner unit)

**Comment by ElphaX** [comment]
Yes @PixelBurstHD Huge update coming soon, exciting stuff! Thanks for your input
