### ISSUE TITLE
New Device: Simple Garage Door (3.1) Type

### ISSUE THREAD

**Issue by chaot4ever** [iRayanKhan/homebridge-tuya#213]
[SimpleGarageDoorAccessory.zip](https://github.com/iRayanKhan/homebridge-tuya/files/6056611/SimpleGarageDoorAccessory.zip)

@iRayanKhan I have a Garage Door Opener with sensor for open/close defined as a "Simple Light Bulb / Socket" which is working perfectly this way returning (3.1) version . When the Door is open the Bulb sign is On, when it's closed, the Bulb sign is Off. The only beauty mistake is that it is displayed as a Bulb sign and not a Garage Door sign in the Homekit App. Can you please add the "Simple Garage Door" type as attached to the devices?

**Comment by mario0000o7** [comment]
I have same problem with my garage door it is working with Simple Light Bulb / Socket but i want garage icon. How do you resolve this problem?
