### ISSUE TITLE
siri requests vs. HomeKit UI mismatches

### ISSUE THREAD

**Issue by humjjf** [iRayanKhan/homebridge-tuya#214]
**Checklist**
- [x] I have read the common issues wiki page
- [x] I have checked to make sure the plugin is up to date

**Describe the bug**
Just installed a Treatlife Fan/Light Switch.
I was able to add the device to the platform (using HOOBS) and the device appears as expected in Homekit.
Using the HomeKit UI on my iPhone, I can set the both the fan speed and light brightness from 0 to 100% on the sliders, and the switch responds as expected.
But, if I ask Siri to do this, the switch misbehaves. E.g.:
"Hey Siri, set Fan Light to 50%" --> Switch sets the actual light to <10%

After some basic debugging w/ the HOOBS log, I noticed that using the UI does scale the 0-100% HomeKit value to the light switch's 100-1000 value. But Siri's request does not go through this scaling for some reason, instead the requested value is set directly to the accessory's configuration. E.g. "Hey Siri, set Fan Light to 500%" does actually turn the dimmer to 50% and the value printed in the log for brightness is 50%, but HomeKit UI shows 50% brightness.

Similar behavior applies for Fan speed. "Hey Siri, set Fan speed to 2%" --> Fan speed is set to 50% and value logged for speed is "2", but HomeKit UI shows 50% on slider.

**To Reproduce**
1. Ask Siri to configure a given brightness

**Expected behavior**
- "Hey Siri, set Fan Light to 50%" --> Switch sets the actual light to 50%
- "Hey Siri, set Fan speed to 50%" --> Fan speed is set to 50%

**Screenshots**

**Environment (please complete the following information):**
 - OS: 
-  iOS version: 14.4
-  Homehubs: 
 - Node Version: 
 - Plugin Version: 1.4.0
-  Accessory Type: Simple Fan Light

**Additional context**

**Comment by ElphaX** [comment]
Unable to replicate on all my Tuya devices. This shouldn't work this way, first I've heard of someone having this issue too.
Can you confirm your HomePods or devices using Siri are up to date? And if you're still having this issue or not?

Closing for now..
