### ISSUE TITLE
Error in SimpleFanAccessory.js ?

### ISSUE THREAD

**Issue by svenf01** [iRayanKhan/homebridge-tuya#223]
Hello

I'm using a Alphawise P2 that has RotationSpeed at dp 4.
With the current file the dpRotationSpeed not work for me.
It every time use the default 3.

Then i look to the file and see this line:
        this.dpActive = this._getCustomDP(this.device.context.dpActive) || '1';
        this.dpRotationSpeed = this._getCustomDP(this.device.context.RotationSpeed) || '3';

Using 'dpRotationSpeed' in config it is not working.
Then i changed the line to:
        this.dpRotationSpeed = this._getCustomDP(this.device.context.dpRotationSpeed) || '3';

Now it is working. 
So what is correct dpRotationSpeed like for dpActive or RotationSpeed?

Thanks
Sven

**Comment by ElphaX** [comment]
Thanks for the heads up @svenf01 
We've made the change to use 'dpRotationSpeed' after the next update, you can use RotationSpeed for now in your config to make it work.
