### ISSUE TITLE
Failed to parse discovery response

### ISSUE THREAD

**Issue by rasmuslos** [iRayanKhan/homebridge-tuya#224]
**Checklist**
- [x] I have read the common issues wiki page
- [x] I have checked to make sure the plugin is up to date

**Describe the bug**
When starting Homebridge I get the following error from one of the devices `Failed to parse discovery raw message on port 6667`

**To Reproduce**
I added a new light by teckin 

**Expected behavior**
The light shows up

**Screenshots**

**Environment (please complete the following information):**
 - OS: Homebridge (RaspberryPi OS)
-  iOS version: 14.5
-  Homehubs: Homepod
 - Node Version: 14.15.4
 - Plugin Version: 1.5.0
-  Accessory Type: RGBTWLight

**Additional context**
```
[02/03/2021, 14:40:35] [TuyaLan] Discovered NAME (bf4d335e6ddda37d04qcpv) identified as RGBTWLight (3.3)
[TuyaAccessory] Changing ping gap for NAME to 9s
[TuyaDiscovery] Failed to parse discovery response on port 6667: {"ip":"192.168.188.50","gwId":"xxx","active":2,"ablilty":0,"encrypt":true,"productKey":"xxx","version":"3.3"}
[TuyaDiscovery] Failed to parse discovery raw message on port 6667: 000055aa00000000000000130000009c00000000d09766676f3369eb10b5e9f132fd802a0eb593d996bc4bf516fce23a5108089c963efed715f2b042e18a82572aaf5b60dfea086682943031f1341615689d2bf159bd59981c26d5958da187e096d937c840b1058c6d8cd9456f3f7e28eed4932bb87df98f09361d818a337cda1e92d50a671c2730de35366bed4c5eeab249f98d8494c932e298de410f638ed8bf10587a96a5e6890000aa55
```

**Comment by svenf01** [comment]
I have the same problem, but with Fan.

**Environment (please complete the following information):**

OS: Homebridge (RaspberryPi OS)
Homehubs: AppleTV
Node Version: 14.15.0
Plugin Version: 1.5.1
Accessory Type: Fan (SimpleFan)

**Additional context**

[8.3.2021, 20:16:35] [Tuya] Discovered Luftreiniger (00405813c44f33988fc8) identified as Fan (3.3)
[Tuya] Changing ping gap for Luftreiniger to 9s
[TuyaDiscovery] Failed to parse discovery response on port 6667: {"ip":"192.168.1.29","gwId":"00405813c44f33988fc8","active":2,"ability":0,"mode":0,"encrypt":true,"productKey":"3EUETAhBnjdGBE5K","version":"3.3"}
[TuyaDiscovery] Failed to parse discovery raw message on port 6667: 000055aa0000000000000013000000ac00000000d09766676f3369eb10b5e9f132fd802af2044f95b8b763ce3c3e6e8a703154f31d3ca67f0f4fb1707c13878ce198744a9e0bb069cf27b00b3a22d89af4aad242cb5924bb8792fe5eae7c9040e5921a98017f2170860421e6fc66f0a1ade138915fde850cd157270c5f3d1ab5ae90b300b1520d8803341089e6e3ab28683e7c6c1c8343bc25f3403c0c4c3db59350d34ae0bd1f2cbad705886d4ed8eed5ab9eb9a3869af10000aa55

**Comment by jamesthedove** [comment]
@iRayanKhan Any feedback on this.
Also experiencing the same issue.

**Comment by nicklayb** [comment]
I'm experiencing the same issue, I did a bit of debugging and in my case it throws because of [this](https://github.com/iRayanKhan/homebridge-tuya/blame/ede074df1513bf60e2ea3731121005927b508d04/index.js#L212) change.

So what I think is happening is that it tries to trim the `deviceConfig.manufacturer` but there is no manufacturer in the payload. So maybe the manufacturer should fall back to some empty string or a fallback like "Tuya"

**Comment by jamesthedove** [comment]
Thanks @nicklayb 
I added the `manufacturer` property and it's working back again.

**Comment by svenf01** [comment]
Thanks @nicklayb
The same for me. Adding the manufacturer by hand and it work again.

**Comment by sobake** [comment]
I installed the plugin via the homebridge-ui and this bug is currently present. Filling the manufacturer field allows connection without issue.

**Comment by marcopelegrini** [comment]
We should reopen this... 

I was having this issue:

```
[TuyaDiscovery] Failed to parse discovery response on port 6667: {"ip":"10.0.1.54","gwId":"","active":2,"ablilty":0,"encrypt":true,"productKey":"","version":"3.3"}
[TuyaDiscovery] Failed to parse discovery raw message on port 6667: 000055aa00000000000000130000009c0000000058aebff485f25ca359e8b66ac70a6102d003e341b90f9a4d7d83bc11791ebc022baa301ee16fceb430eef6663ffd758d1a7bcb75ef5bb8eb330ad344dd0b106868c2c8903dec4bff0294046f69a2112cb14d42dae779bd097a67839861716672b33d9f66345dc38b49dc0f8d32d674a86d047a542608a433eeb5d0d82fd8b9cfbcc651832dd9b60158654b01a12a9a5219394bd90000aa55
```

Then adding Model and Manufacture I've managed to get it working.

--- 

One of my lights is a strip that doesn't have while value... it's a weird one I've got from Amazon: https://www.amazon.ca/gp/product/B086GHN58C

It mostly works fine but the colours are sometimes mismatched, and it shows the temperature control which doesn't work, I also get this warning:

```
[2022-10-22, 9:45:15 p.m.] [homebridge-tuya] This plugin generated a warning from the characteristic 'Saturation': characteristic was supplied illegal value: number 107 exceeded maximum of 100. See https://homebridge.io/w/JtMGR for more info.
[2022-10-22, 9:45:15 p.m.] [homebridge-tuya] Error: 
    at Saturation.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridg
```


Also leaving it here the configuration I've used for the Globe bulbs from Costco / Canadian Tire:
```
                {
                    "type": "RGBTWLight",
                    "name": "Living light",
                    "manufacturer": "Globe",
                    "model": "Bulb",
                    "id": "",
                    "key": "",
                    "dpPower": 20,
                    "dpMode": 21,
                    "dpBrightness": 22,
                    "dpColorTemperature": 23,
                    "dpColor": 24,
                    "colorFunction": "HSB",
                    "minBrightness": 10,
                    "maxBrightness": 1000,
                    "scaleBrightness": 1000,
                    "scaleWhiteColor": 1000
                },
```
