### ISSUE TITLE
Question: 4 devices from 12 are not working correct?

### ISSUE THREAD

**Issue by drheck** [iRayanKhan/homebridge-tuya#226]
Hello,
i have 12 devices. 8 standard outlets and 4 wire outlets.

8 devices are working correct.
But 4 devices are not responding correctly.

In the apple homeapp there are in the "not responding" state.

In the tuya smart life app they are available and if i change the state from On to Off, i get some logs in the homebridge logfile.
So i guess that the devices id/key are correct.
But i can not interact with them in the homekit app.

Any ideas?

Thanks a lot,
Peter

I think this is not a environment issue...

Here is a logfile section for  TY-Licht HWR:

Mar  5 20:22:13 hbridge3 systemd[1]: Started Session c6 of user root.
Mar  5 20:22:15 hbridge3 homebridge[2321]: [Tuya DEBUG] decrementing this._connectionAttempts, currently 4
Mar  5 20:22:15 hbridge3 homebridge[2321]: [Tuya DEBUG] decrementing this._connectionAttempts, currently 3
Mar  5 20:22:16 hbridge3 homebridge[2321]: [Tuya] Socket had a problem and will reconnect to TY-Licht HWR (EHOSTUNREACH)
Mar  5 20:22:16 hbridge3 homebridge[2321]: [Tuya DEBUG] after error setting _connect in 5000ms
Mar  5 20:22:18 hbridge3 systemd[1]: Started Session c7 of user root.
Mar  5 20:22:18 hbridge3 homebridge[2321]: [Tuya] Socket had a problem and will reconnect to TY-Licht HWR (Error: ERR_CONNECTION_TIMED_OUT)
Mar  5 20:22:20 hbridge3 systemd[1]: Started Session c8 of user root.
Mar  5 20:22:21 hbridge3 homebridge[2321]: [Tuya DEBUG] executing _connect after 5000ms delay
Mar  5 20:22:21 hbridge3 homebridge[2321]: [Tuya DEBUG] reconnect called for TY-Licht HWR
Mar  5 20:22:23 hbridge3 homebridge[2321]: [Tuya DEBUG] decrementing this._connectionAttempts, currently 4
Mar  5 20:22:23 hbridge3 homebridge[2321]: [Tuya DEBUG] decrementing this._connectionAttempts, currently 3
Mar  5 20:22:24 hbridge3 homebridge[2321]: [Tuya] Socket had a problem and will reconnect to TY-Licht HWR (EHOSTUNREACH)
Mar  5 20:22:24 hbridge3 homebridge[2321]: [Tuya DEBUG] after error setting _connect in 5000ms
Mar  5 20:22:26 hbridge3 homebridge[2321]: [Tuya] Socket had a problem and will reconnect to TY-Licht HWR (Error: ERR_CONNECTION_TIMED_OUT)
Mar  5 20:22:29 hbridge3 homebridge[2321]: [Tuya DEBUG] executing _connect after 5000ms delay
Mar  5 20:22:29 hbridge3 homebridge[2321]: [Tuya DEBUG] reconnect called for TY-Licht HWR
Mar  5 20:22:31 hbridge3 homebridge[2321]: [Tuya DEBUG] decrementing this._connectionAttempts, currently 4
Mar  5 20:22:31 hbridge3 homebridge[2321]: [Tuya DEBUG] decrementing this._connectionAttempts, currently 3
Mar  5 20:22:32 hbridge3 homebridge[2321]: [Tuya] Socket had a problem and will reconnect to TY-Licht HWR (EHOSTUNREACH)
Mar  5 20:22:32 hbridge3 homebridge[2321]: [Tuya DEBUG] after error setting _connect in 5000ms
Mar  5 20:22:35 hbridge3 homebridge[2321]: [Tuya] Socket had a problem and will reconnect to TY-Licht HWR (Error: ERR_CONNECTION_TIMED_OUT)
Mar  5 20:22:37 hbridge3 homebridge[2321]: [Tuya DEBUG] executing _connect after 5000ms delay
Mar  5 20:22:37 hbridge3 homebridge[2321]: [Tuya DEBUG] reconnect called for TY-Licht HWR
Mar  5 20:22:38 hbridge3 homebridge[2321]: [Tuya] Heard back from TY-Zirkulation with command 8
Mar  5 20:22:39 hbridge3 homebridge[2321]: [Tuya DEBUG] decrementing this._connectionAttempts, currently 4
Mar  5 20:22:39 hbridge3 homebridge[2321]: [Tuya DEBUG] decrementing this._connectionAttempts, currently 3
Mar  5 20:22:40 hbridge3 homebridge[2321]: [Tuya] Heard back from TY-Zirkulation with command 8
Mar  5 20:22:40 hbridge3 homebridge[2321]: [Tuya] Socket had a problem and will reconnect to TY-Licht HWR (EHOSTUNREACH)
Mar  5 20:22:40 hbridge3 homebridge[2321]: [Tuya DEBUG] after error setting _connect in 5000ms
Mar  5 20:22:43 hbridge3 homebridge[2321]: [Tuya] Socket had a problem and will reconnect to TY-Licht HWR (Error: ERR_CONNECTION_TIMED_OUT)
Mar  5 20:22:45 hbridge3 homebridge[2321]: [Tuya DEBUG] executing _connect after 5000ms delay
Mar  5 20:22:45 hbridge3 homebridge[2321]: [Tuya DEBUG] reconnect called for TY-Licht HWR
Mar  5 20:22:47 hbridge3 homebridge[2321]: [Tuya DEBUG] decrementing this._connectionAttempts, currently 4
Mar  5 20:22:47 hbridge3 homebridge[2321]: [Tuya DEBUG] decrementing this._connectionAttempts, currently 3
Mar  5 20:22:49 hbridge3 homebridge[2321]: [Tuya] Socket had a problem and will reconnect to TY-Licht HWR (EHOSTUNREACH)
Mar  5 20:22:49 hbridge3 homebridge[2321]: [Tuya DEBUG] after error setting _connect in 5000ms
Mar  5 20:22:51 hbridge3 homebridge[2321]: [Tuya] Socket had a problem and will reconnect to TY-Licht HWR (Error: ERR_CONNECTION_TIMED_OUT)
Mar  5 20:22:54 hbridge3 homebridge[2321]: [Tuya DEBUG] executing _connect after 5000ms delay
Mar  5 20:22:54 hbridge3 homebridge[2321]: [Tuya DEBUG] reconnect called for TY-Licht HWR
Mar  5 20:22:55 hbridge3 homebridge[2321]: [Tuya DEBUG] decrementing this._connectionAttempts, currently 4
Mar  5 20:22:55 hbridge3 homebridge[2321]: [Tuya DEBUG] decrementing this._connectionAttempts, currently 3
Mar  5 20:22:57 hbridge3 homebridge[2321]: [Tuya] Socket had a problem and will reconnect to TY-Licht HWR (EHOSTUNREACH)
Mar  5 20:22:57 hbridge3 homebridge[2321]: [Tuya DEBUG] after error setting _connect in 5000ms
Mar  5 20:22:59 hbridge3 homebridge[2321]: [Tuya] Socket had a problem and will reconnect to TY-Licht HWR (Error: ERR_CONNECTION_TIMED_OUT)
Mar  5 20:23:01 hbridge3 systemd[1]: Started Session c9 of user root.

**Environment (please complete the following information):**
 - OS: 
-  iOS version:
-  Homehubs: 
 - Node Version: 
 - Plugin Version:
-  Accessory Type

**Additional context**

**Comment by pelletip** [comment]
I have observed similar behaviour, producing the same type of messages.  I have 5 devices: 3 smart switches and two garage doors, usually all responding after a fresh boot, then, after a while, some devices will stop responding; I have not been able to determine yet, what trips the logic into this 'not responding' problem.  I reboot and things go back to normal.

**Comment by drheck** [comment]
Okay. Thank you for your reply, but reboot does not help... Perhaps it is a timeout problem..?

**Comment by drheck** [comment]
I have figured out the ids and keys for the failing devices. Now they work.
FYI: I have used this method for getting the keys: https://www.youtube.com/watch?v=oq0JL_wicKg

**Comment by drheck** [comment]
See my last comment...

**Comment by alejandroeclair** [comment]
@drheck i have the same issues... some devices work fine for the first 5 minutes, then all the sudden I start getting EHOSTUNREACH error... This is very annoying.

**Comment by shivanathd** [comment]
I have the same issue .. @drheck  could you help me understand how you fixed it ? 

Cc : @iRayanKhan

**Comment by shivanathd** [comment]
`Tuya DEBUG] after error setting _connect in 5000ms
[Tuya] Socket had a problem and will reconnect to Water Motor Switch (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Water Motor Switch
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for OLA Charger
[Tuya DEBUG] decrementing this._connectionAttempts, currently 4
[Tuya DEBUG] decrementing this._connectionAttempts, currently 3
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Kitchen Fan
[Tuya] Sending first query to Kitchen Fan (3.3)
[Tuya] Heard back from Kitchen Fan with command 10
[Tuya] Socket had a problem and will reconnect to Water Motor Switch (EHOSTUNREACH)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya] Socket had a problem and will reconnect to OLA Charger (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya DEBUG] decrementing this._connectionAttempts, currently 4
[Tuya DEBUG] decrementing this._connectionAttempts, currently 3
[Tuya] Socket had a problem and will reconnect to Kitchen Fan (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya] Socket had a problem and will reconnect to Water Motor Switch (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Water Motor Switch
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for OLA Charger
[Tuya DEBUG] decrementing this._connectionAttempts, currently 4
[Tuya DEBUG] decrementing this._connectionAttempts, currently 3
[Tuya DEBUG] decrementing this._connectionAttempts, currently 4
[Tuya DEBUG] decrementing this._connectionAttempts, currently 3
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Kitchen Fan
[Tuya] Socket had a problem and will reconnect to Water Motor Switch (EHOSTUNREACH)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya] Socket had a problem and will reconnect to OLA Charger (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya DEBUG] decrementing this._connectionAttempts, currently 4
[Tuya DEBUG] decrementing this._connectionAttempts, currently 3
[Tuya] Socket had a problem and will reconnect to Water Motor Switch (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Water Motor Switch
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for OLA Charger`

**Comment by drheck** [comment]
Hi shivanathd and alejandroeclair,
i can not help you with this plugin.
Sorry. A few weeks ago i had one device which lost very few days the connection. I bought a new one...

Merry christmas.
