### ISSUE TITLE
Garage Door constantly shows as closing

### ISSUE THREAD

**Issue by MexicanSkywalker** [iRayanKhan/homebridge-tuya#228]
**Checklist**
- [X] I have read the common issues wiki page
- [X] I have checked to make sure the plugin is up to date

**Describe the bug**
I am able to open and close the garage door from Hoobs dashboard. When the door is open, Home app will show the door as open and proceeds to close properly. It just hangs in the "Closing ..." animation.

3/7/2021, 11:31:59 AM [Tuya] Chamberlain GarageDoor _getTargetDoorState UNKNOWN STATE undefined
3/7/2021, 11:31:59 AM [HOOBS 792C@Garage Door@Garage Door@Target Door State] characteristic value expected number and received undefined

3/7/2021, 11:51:10 AM [Tuya] Sending Garage Door {"1":true}
3/7/2021, 11:51:10 AM [Tuya] Heard back from Garage Door with command 8
3/7/2021, 11:51:10 AM [Tuya] Chamberlain GarageDoor changed:{"1":true}
3/7/2021, 11:51:11 AM [Tuya] Heard back from Garage Door with command 8
3/7/2021, 11:51:11 AM [Tuya] Chamberlain GarageDoor changed:{"101":true}
3/7/2021, 11:51:27 AM [Tuya] Sending Garage Door {"1":false}
3/7/2021, 11:51:27 AM [Tuya] Heard back from Garage Door with command 8
3/7/2021, 11:51:27 AM [Tuya] Chamberlain GarageDoor changed:{"1":false}
3/7/2021, 11:51:39 AM [Tuya] Heard back from Garage Door with command 8
3/7/2021, 11:51:39 AM [Tuya] Chamberlain GarageDoor changed:{"101":false}

**Comment by gpwdeux** [comment]
I found that changing the DpStatus in the plug-in settings to “1” instead of the default “2” did the trick.
