### ISSUE TITLE
Feit 16ft Smart Color Changing LED Strip - Working Config.

### ISSUE THREAD

**Issue by ScottBessel** [iRayanKhan/homebridge-tuya#230]
I found this to be a working config for this Feit 16ft Smart Color Changing LED Strip.
https://www.feit.com/product/16-ft-smart-color-changing-led-strip-light/

        {
            "name": "LED Undercounter",
            "type": "RGBTWLight",
            "manufacturer": "FEIT",
            "model": "Smart LED Strip Light",
            "id": "redacted",
            "key": "redacted",
            "dpPower": 20,
            "dpMode": 21,
            "dpBrightness": 22,
            "dpColorTemperature": 23,
            "dpColor": 24,
            "colorFunction": "HSB"
        }

**Comment by iRayanKhan** [comment]
Closed: Adding this to the wiki

**Comment by Pablo-Githu** [comment]
works! thank you.
