### ISSUE TITLE
SimpleBlids2 typo with Homebridge UI

### ISSUE THREAD

**Issue by Xusqui** [iRayanKhan/homebridge-tuya#231]
Hi, neighbours and friends

I've just upgraded to version 2.0

I've gone to the Homebridge UI to see how the config was made. I've realised that my blinds are shown with no name in the "Type" field, and if I select "Simple Blinds 2", in the config .json file you can see: "type": "Simple Blinds2" with a space between Simple and Blinds, so the blinds stop working.

Hope you know what I mean!

Thanks in advance

![Captura de pantalla 2021-03-15 a las 22 58 45](https://user-images.githubusercontent.com/6235884/111227180-78292e80-85e2-11eb-998b-4afffb3c2a34.png)

![Captura de pantalla 2021-03-15 a las 22 59 29](https://user-images.githubusercontent.com/6235884/111227223-87a87780-85e2-11eb-8315-4479990c4313.png)

**Comment by iRayanKhan** [comment]
Fixed in 2.1.0 (beta). Will close once out of beta.

**Comment by iRayanKhan** [comment]
Fixed in 2.1.0

You should see it as an update in an hour or so.

Thanks!

**Comment by iRayanKhan** [comment]
May be longer than a few hours, just ran into a bug
