### ISSUE TITLE
flipping temperature 

### ISSUE THREAD

**Issue by Earnstl** [iRayanKhan/homebridge-tuya#233]
**Checklist**
- [ x] I have read the common issues wiki page
- [ x] I have checked to make sure the plugin is up to date

**Describe the bug**
I was able to integrate an InkBird IBS-M1.
The schema looks like this:
[Tuya] SimpleHeater changed: {"101":false,"102":0,"103":68,"104":955,"105":20000,"106":"AAMAAQRYApz/WAKc/yADZAAAAAAAAADoVaoA","107":0,"108":30000,"109":30000,"110":20000,"111":"AQAAAAJYApz/WAKc/yADZAAAAAAAAAAAAAAA","112":0,"113":30000,"114":30000,"115":20000,"116":"AgAAAAJYApz/WAKc/yADZAAAAAAAAAAAAAAA","117":0,"118":30000,"119":30000,"120":20000,"121":"AwAAAAJYApz/WAKc/yADZAAAAAAAAAAAAAAA","126":false,"128":30000}
I was able to get the datapoint for current temperature via the type "SimpleHeater". -> 104
I do not use the switching function.
As far as the temperature will be shown for a short period I get the right data and devided correctly by 100.
Unfortunately after a a second the reported temperature flips to 100, back to the current temperature, back to 100 and then stays there. Sometimes after a refresh it flips more then 2 times.

**To Reproduce**
make use of a temperature sensor 

**Expected behavior**
Show the current temperatur only.
No flipping.

**Screenshots**
![image](https://user-images.githubusercontent.com/80824480/111457888-13242480-8719-11eb-9d5c-5e582957bd72.png)
![image](https://user-images.githubusercontent.com/80824480/111458316-947bb700-8719-11eb-8762-fcab113e6940.png)

**Environment (please complete the following information):**
 - OS: Alpine Linux (3.12.4)
-  iOS version: -
-  Homehubs: -
 - Node Version: v14.16.0
 - Plugin Version: homebridge-tuya v2.0.0
-  Accessory Type: temp sensor via gateway

**Additional context**

**Comment by iRayanKhan** [comment]
Fixed in 2.1.0, thanks @xortuna!
