### ISSUE TITLE
SimpleBlind closes and opens at sunset

### ISSUE THREAD

**Issue by JanMostert** [iRayanKhan/homebridge-tuya#234]
**Checklist**
- [x] I have read the common issues wiki page
- [x] I have checked to make sure the plugin is up to date

**Describe the bug**
I automated the closing of a blind at sunset. When the time of closing arrives, I see the blind starting to close for a fraction of a second and then opens again (a sort of reset). When I manually select to close in the Home app, it closes.

**To Reproduce**
- Configure an automation in the Home app to close the blind at sunset.

**Expected behavior**
I gepest it to close, but it starts to close and almost directly it opens again

**Screenshots**
This is what I see in the log file:
[Tuya] Blinds asked to move from 100 to 0
[Tuya] Sending Gordijn Rechts {"1":"close"}
[Tuya] Heard back from Gordijn Rechts with command 8
[Tuya] Blinds saw change to close
[Tuya] Blinds will be marked closed in 44000ms
[Tuya] Heard back from Gordijn Rechts with command 8
[Tuya] Blinds saw change to undefined
[Tuya] Blinds asked to move from 100 to 0
[Tuya] Blinds closing had started 1616176438869; 44484ms ago
[Tuya] Blinds' adjusted assumedPosition is -1.0999999999999943
[Tuya] Sending Gordijn Rechts {"1":"open"}
[Tuya] Heard back from Gordijn Rechts with command 8
[Tuya] Blinds saw change to open
[Tuya] Heard back from Gordijn Rechts with command 8
[Tuya] Blinds saw change to undefined
[Tuya] Blinds asked to move from -1.0999999999999943 to 0
[Tuya] Blinds opening had started 1616176482869; 59226ms ago
[Tuya] Blinds' adjusted assumedPosition is 134.60454545454544

**Environment (please complete the following information):**
 - OS: macOS 10.13.6
-  iOS version: 14.4.1
-  Homehubs: HomePod 14.4
 - Node Version: latest
 - Plugin Version: 2.0.0
-  Accessory Type: SimpleBlinds

**Comment by MarkM500** [comment]
Same problem here. Often the characteristics are wrong. SimpleBlinds and SimpleBlinds2.
errors like this:
`3/20/2021, 8:11:09 AM] [homebridge-tuya] This plugin generated a warning from the characteristic 'Current Position': characteristic was supplied illegal value: number 712 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/20/2021, 8:11:09 AM] [homebridge-tuya] This plugin generated a warning from the characteristic 'Target Position': characteristic was supplied illegal value: number 712 exceeded maximum of 100. See https://git.io/JtMGR for more info.`

Thanks for help.
Mark

**Comment by JanMostert** [comment]
I really really really miss the timestamp in the logging. It is impossible to see how much time there is between the close and open command. This makes debugging very hard.

**Comment by iRayanKhan** [comment]
What version last had time stamps?

**Comment by JanMostert** [comment]
Don’t know. All I see is that other plugins write in the log file with a timestamp in each line. The Tuya Lan plugins does not. Would be very handy if there was one in each log entry

**Comment by iRayanKhan** [comment]
How are you running homebridge? The Ui should provide time stamps.

**Comment by JanMostert** [comment]
It runs like it should. In the log file (homebridge.log) I see these kind of entries:

[Tuya] Blinds asked to move from 101.1462962962963 to 0
[Tuya] Sending Gordijn Rechts {"1":"close"}
[Tuya] Heard back from Gordijn Rechts with command 8
[Tuya] Blinds saw change to close
[Tuya] Blinds will be marked closed in 54619.00000000001ms
[Tuya] Blinds asked to move from 101.1462962962963 to 100
[Tuya] Blinds closing had started 1616395955310; 57650ms ago
[Tuya] Blinds' adjusted assumedPosition is -6.759259259259252
[Tuya] Sending Gordijn Rechts {"1":"open"}
[Tuya] Heard back from Gordijn Rechts with command 8
[Tuya] Blinds saw change to open
[Tuya] Blinds will be marked open in 57650ms

What would be better is to have a timestamp like other log entries:

[3/22/2021, 8:40:57 AM] Registering platform 'homebridge-tuya.TuyaLan'
[3/22/2021, 8:40:57 AM] [TuyaLan] Initializing TuyaLan platform...
[3/22/2021, 8:40:57 AM] [TuyaLan] Marked Gordijn Rechts unreachable by faulting Service.Gordijn Rechts.Target Position
[3/22/2021, 8:40:57 AM] [TuyaLan] Marked Gordijn Links unreachable by faulting Service.Gordijn Links.Target Position
[3/22/2021, 8:40:57 AM] [TuyaLan] Starting discovery...

**Comment by JanMostert** [comment]
FYI: I stopped using this plugin because I get it not working like it should. I switched to the Tuya-web plugin; this one works, although the status in the Home app is "opening ..." when it is open and "closing ..." when it is closed.

**Comment by avbaga** [comment]
I have a same problem. 
tuya-web doesn’t work for me also.

**Comment by JanMostert** [comment]
> I have a same problem.
> tuya-web doesn’t work for me also.

What is not working? I had problems with authentication and this solved it:

_EDIT: I looked again in the app, and there was a feature to "set password" which required email verification. I went through that, and restarted homebridge, and suddenly the authentication worked and all my accessories were found._

Have a look at the working plugin: https://github.com/milo526

**Comment by JanMostert** [comment]
Same here, but automation works and "He Siri close blinds" works as well. Maybe it is better to continue this conversation on the right place ( https://github.com/milo526)
