### ISSUE TITLE
New Device: Smart Wireless Switch M4

### ISSUE THREAD

**Issue by icep87** [iRayanKhan/homebridge-tuya#236]
Is it possible to add Smart Wireless Switch M4? Or none of the switches are working?

**Comment by rsschaap** [comment]
Yes relevant, how to rebuild this integration manifest to a working device? 

[Smart Wireless Switch M4.json.txt](https://github.com/iRayanKhan/homebridge-tuya/files/9057588/Smart.Wireless.Switch.M4.json.txt)
