### ISSUE TITLE
New Device: Doorbell Tuya

### ISSUE THREAD

**Issue by mitchoklemen** [iRayanKhan/homebridge-tuya#237]
https://www.aliexpress.com/item/4001255525162.html?spm=a2g0s.9042311.0.0.27424c4dhZIdvQ

**Describe your device**
Tuya App 2MP Smart WiFi Video Doorbell Camera Visual Intercom with Chime Night vision IP Door Bell Wireless Home Security Camera

Any chance of support for this device?

Thanx, Mitcho

**Comment by iRayanKhan** [comment]
Hey Mitcho,

I currently don't have plans to add support for cameras/doorbells. If your device has an RTSP stream, you can try the [homebridge-camera-ffmpeg](https://github.com/Sunoo/homebridge-camera-ffmpeg) plugin.
