### ISSUE TITLE
Question: How to get rid of all these messages in the logfile?

### ISSUE THREAD

**Issue by drheck** [iRayanKhan/homebridge-tuya#240]
Hi,

i have a question about these messages below.

These thousands of messages in the logfile could not be good for performance and other things on my raspberry pi....

Is it possible to wrap them with debuglevels?

Thanks,
Peter

Mar 27 17:07:25 hbridge3 homebridge[471]: [Tuya] Heard back from Kamera with command 8
Mar 27 17:07:28 hbridge3 homebridge[471]: [Tuya] Heard back from VU+-3 with command 8
Mar 27 17:07:30 hbridge3 homebridge[471]: [Tuya] Heard back from VU+-3 with command 8
Mar 27 17:07:32 hbridge3 homebridge[471]: [Tuya] Heard back from Kamera with command 8
Mar 27 17:07:33 hbridge3 homebridge[471]: [Tuya DEBUG] decrementing this._connectionAttempts, currently 2
Mar 27 17:07:33 hbridge3 homebridge[471]: [Tuya DEBUG] decrementing this._connectionAttempts, currently 1
Mar 27 17:07:35 hbridge3 homebridge[471]: [Tuya] Heard back from VU+-3 with command 8
Mar 27 17:07:38 hbridge3 homebridge[471]: [Tuya] Heard back from Kamera with command 8
Mar 27 17:07:40 hbridge3 homebridge[471]: [Tuya] Heard back from Kamera with command 8
Mar 27 17:07:40 hbridge3 homebridge[471]: [Tuya] Heard back from VU+-3 with command 8
Mar 27 17:07:42 hbridge3 homebridge[471]: [Tuya] Heard back from Kamera with command 8
Mar 27 17:07:42 hbridge3 homebridge[471]: [Tuya] Heard back from VU+-3 with command 8
Mar 27 17:07:44 hbridge3 homebridge[471]: [Tuya] Heard back from Kamera with command 8
Mar 27 17:07:46 hbridge3 homebridge[471]: [Tuya] Heard back from Kamera with command 8
Mar 27 17:07:49 hbridge3 homebridge[471]: [Tuya] Heard back from VU+-3 with command 8
Mar 27 17:07:51 hbridge3 homebridge[471]: [Tuya] Heard back from Kamera with command 8

**Comment by iRayanKhan** [comment]
Will work on for v.2.2 or 2.3

**Comment by iRayanKhan** [comment]
Fixed in V2.1.0

You should see it live soon.

**Comment by iRayanKhan** [comment]
May be longer than a few hours, just ran into a bug
