### ISSUE TITLE
Neither SimpleBlinds and SimpleBlinds2 work for me

### ISSUE THREAD

**Issue by cpvbruno** [iRayanKhan/homebridge-tuya#245]
08/04/2021, 16:59:02 [TuyaLan] Discovered a device that has not been configured yet (bf3a76eaf77b0b9215iyaw@192.168.178.36).
08/04/2021, 16:59:04 [TuyaLan] Discovered Office Blind (86037560e0980610d78c) identified as SimpleBlinds (3.3)
08/04/2021, 16:59:04 [Tuya] Changing ping gap for Office Blind to 9s
08/04/2021, 16:59:04 [Tuya DEBUG] reconnect called for Office Blind
08/04/2021, 16:59:04 [Tuya] Discovery ended.
08/04/2021, 16:59:04 [TuyaLan] Connected to Office Blind
08/04/2021, 16:59:04 [Tuya] Sending first query to Office Blind (3.3)
08/04/2021, 16:59:04 [Tuya] Heard back from Office Blind with command 10
08/04/2021, 16:59:04 [TuyaLan] Ready to handle Office Blind (SimpleBlinds:3.3) with signature {"2":78,"5":true}
08/04/2021, 16:59:14 [Tuya DEBUG] decrementing this._connectionAttempts, currently 2
08/04/2021, 16:59:14 [Tuya DEBUG] decrementing this._connectionAttempts, currently 1
08/04/2021, 16:59:30 [Tuya] Blinds asked to move from 100 to 0
08/04/2021, 16:59:30 [Tuya] Sending Office Blind {"1":"2"}

**Comment by cpvbruno** [comment]
Although it says it's "sending" the command, nothing really gets done

**Comment by hubert3** [comment]
Same here - I have this AVATTO branded blinds controller device https://www.aliexpress.com/item/4001045079168.html

Works fine with the Android com.tuya.smartlife_3.6.1-70 app which I also used to extract devid and key, and also with Tuya 3.26 iOS app

**Comment by ElphaX** [comment]
Thanks for raising this issue! Can both of you possibly reply with the device signature? It will look like this: ` [TuyaLan] Ready to handle Blinds (SimpleBlinds:3.3) with signature {"1":true,"2":false}`

Please run homebridge in debug mode if you cannot see this, also if possible provide a signature for an already open & closed set of blinds. - Can get your devices working in the next update ;)

**Comment by xrust83** [comment]
Zemismart Tabular motor ZM25TQ
[TuyaLan] Ready to handle CurtainRoll (SimpleBlinds:3.3) with signature {"1":"stop","2":0,"3":0,"5":"forward","7":"opening","11":"fully_open","12":0,"103":true,"104":true,"105":true,"106":"contiuation"}

**Comment by codyc1515** [comment]
Hello all - I have discovered the issue (for my device at least - Kogan Smart Blinds).

The plug-in sends either 1 / 2 or on / off to the device, depending on if you select SimpleBlinds or SimpleBlinds2.

However, this device is actually expecting to receive open / close, in lieu of 1/2 & on/off. Fairly simple change to make it work and it appears to work fantastically. You can do this manually to the SimpleBlinds2 accessory file (under lib folder) if need be. The values are there towards the beginning of the file.

It seems disingenuous to me to create SimpleBlinds3 when the values may well change again in the future, so perhaps some parameters cmdOpen and cmdClose could be created where the default values could be overwritten, as in the Air Conditioner accessory, and a helpful piece placed on the wiki about potential alternatives.

Unfortunately these devices don’t seem too smart so I think it unlikely that we may be able to auto-detect the correct parameter.

**Comment by codyc1515** [comment]
@iRayanKhan fix above.

**Comment by codyc1515** [comment]
Sorry ignore my previous comment. It looks like @iRayanKhan already thought of this. To make my device work (Kogan Smart Blinds) it was actually quite simple - simply add the following to the config:

                    "name": "Dining Room Blinds",
                    "type": "SimpleBlinds",
                    "manufacturer": "Kogan",
                    "model": "Smart Blinds",
                    "id": "XXX",
                    "key": "XXX",
                    **"cmdOpen": "open",
                    "cmdClose": "close"**

**Comment by codyc1515** [comment]
I have developed a version of the accessory that will pull the live state from the device (moving state and % state), as well as any events if they occur manually, but didn’t have a chance to post this yet.

**Comment by ElphaX** [comment]
Great, post when possible!

we are working on merging both blinds and making global variables based off config options.

The next update should be great!

**Comment by codyc1515** [comment]
> Great, post when possible!
> 
> we are working on merging both blinds and making global variables based off config options.
> 
> The next update should be great!

Well it’s simply just as above (open / close, as opposed to on / off).

**Comment by ElphaX** [comment]
That in itself is _already_ available by specifying the dp values in your config. Am I missing something then?

**Comment by codyc1515** [comment]
You are right but it’s not obvious for new users and the SimpleBlinds and SimpleBlinds2 terminology is also coming to newcomers, in my mind at least.

**Comment by AnonymousPea** [comment]
Any update on the ability for % open/close?

**Comment by hubert3** [comment]
@bgoncal did you ever get this working? I used the TuyaWebPlatform plugin the last few years but since that broke for me today I tried local access again, and still the same issue as you had here years ago, discovery doesn't work

**Comment by bgoncal** [comment]
No, I am not using Tuya based products anymore

**Comment by adrianjagielak** [comment]
@hubert3 I've forked this plugin, as it's seemingly abandoned, to continue its development in **[homebridge-tuya-plus](https://github.com/adrianjagielak/homebridge-tuya-plus)**. Could we continue in [this issue](https://github.com/adrianjagielak/homebridge-tuya-plus/issues/12)?
