### ISSUE TITLE
Working config: Treatlife Smart Tunable White Bulb

### ISSUE THREAD

**Issue by benwtf** [iRayanKhan/homebridge-tuya#248]
Device Name: x

Device Type: TWLight

Plugin Version: 2.0.1

Link to buy: https://www.amazon.com/gp/product/B08J3X9XQ3

Working/non-working capabilities: Fully working

Config:

                {
                    "type": "TWLight",
                    "name": "Office Lamp",
                    "id": "xxx",
                    "key": "xxx",
                    "manufacturer": "Treatlife",
                    "model": "Smart Light Bulb",
                    "dpPower": 20,
                    "dpBrightness": 22,
                    "dpColorTemperature": 23,
                    "scaleBrightness": 1000,
		    "scaleWhiteColor": 1000
                }

**Comment by AngryKiller** [comment]
Hello, it seems to also work for some of LSC Smart Connect LED and Incandescent light bulbs, thanks for your configuration.

**Comment by benwtf** [comment]
Added config to wiki
