### ISSUE TITLE
Lag changing light brightness

### ISSUE THREAD

**Issue by InstigatorX** [iRayanKhan/homebridge-tuya#252]
**Checklist**
- [x] I have read the common issues wiki page
- [X] I have checked to make sure the plugin is up to date

**Describe the bug**
I'm noticing significant amount of lag when moving RGBTW light brightness up and down in HOME app. When I use my finger on lights controlled by this plug and slide the brightness up or down the slide doesn't move smoothly. When I use it on lights controlled by other plugins the control is smooth and increments 1% at a time for very fine control.

This issue makes it hard to pick a specific brightness % as the slider jumps up/down more than 1% at a time.

EDIT: I have 1 non-RGBTW light (SimpleDimmer type) and brightness slider works as expected. e.g. smooth in 1% increments.

The lights works properly. However, my concern is there's something underlying in the implementation that needs to be addressed. I could be wrong, but noticed from log that there are at 2 commands sent to light separately whenever there is a change made. Could this be slowing things down? Maybe batch the commands as 1 discrete call?

[Tuya] Sending Ceiling Alcove 1 {"24":"000003e80154"}
[Tuya] Sending Ceiling Alcove 1 {"20":true}
[Tuya] Heard back from Ceiling Alcove 1 with command 8
[Tuya] Heard back from Ceiling Alcove 1 with command 8
[Tuya] Sending Ceiling Alcove 1 {"24":"000003e802a8"}
[Tuya] Sending Ceiling Alcove 1 {"20":true}
[Tuya] Heard back from Ceiling Alcove 1 with command 8
[Tuya] Heard back from Ceiling Alcove 1 with command 8

**To Reproduce**

Long press Tuya light to get to brightness control in Home app. Slide brightness up and down. Slider doesn't move smoothly. Long press non-Tuya light and do same steps. Slider moves smoothly.

**Expected behavior**
Slider moves slowly up/down for very fine control of the brightness.

**Environment (please complete the following information):**
 - OS: HOOBS
-  iOS version: 14
-  Homehubs: 14
 - Node Version: 
 - Plugin Version:
-  Accessory Type

**Additional context**

**Comment by EdwinJS** [comment]
@InstigatorX  Let me know which devices or Accessory Type you're using and we'll fix it up. 
@iRayanKhan thinking I might clean them up, using a newCharacteristicValue vs currentCharacteristicValue similar to the Oil Diffsuer.

**Comment by InstigatorX** [comment]
@ElphaX RGBTWLight ... is that what you were looking for?

**Comment by ElphaX** [comment]
@InstigatorX Thanks, we've fixed it! Should be live in the next update of the plugin coming very soon!
