### ISSUE TITLE
New Device: 

### ISSUE THREAD

**Issue by Johnreturns** [iRayanKhan/homebridge-tuya#256]
hello. I have some tuya rgbw spotlights. I was wondering what is the device schema, and how I can find it for my spotlights

**Comment by iRayanKhan** [comment]
You can find the device schema in the Tuya int website, where you got your ID/keys.

**Comment by Johnreturns** [comment]
Hello. In the tuya website when pressing on details i get the following
![BD847857-A831-4D2C-9299-9CD9B5B11575](https://user-images.githubusercontent.com/69439488/116013629-ed543e80-a639-11eb-8f6d-d0ae7b3d35cd.jpeg)
Also i managed to get this line from the logs
“ Ready to handle Smart Bulb 3 (RGBTWLight:3.3) with signature {"20":true,"21":"white","22":1000,"23":1000,"24":"000003e803e8","25":"000e0d0000000000000000c80000","26":0}”

But I don’t know how to deduce the parameters from these

**Comment by Johnreturns** [comment]
I assumed the dpPower is 20, dpmode is 21, dpBrightness is 22, dpColorTemperature is 23, dpColorTemperature is 24 and dpScene is 25. But using these parameters only the on off function works as expected.

**Comment by ElphaX** [comment]
Looking for some spotlights myself, link me if you can please! @Johnreturns 

Also, the device parameters you mentioned all appear fine, not sure what's causing only the ON/OFF to work, what does your config look like?

**Comment by Johnreturns** [comment]
Hello. The specific item that I bought was removed, but the seller has new listings for spotlights.  Smart-house Store
https://star.aliexpress.com/share/share.htm?image=HTB1GQ1uRpzqK1RjSZFvq6AB7VXai.jpg&title=Smart-house%20Store&platform=AE&redirectUrl=https%3A%2F%2Fm.aliexpress.com%2Fstore%2Fv3%2Fhome.html%3FshopId%3D5004414%26sellerId%3D237923332%26pagePath%3Dindex.htm%26sellerAdminSeq%3D237923332%26srcSns%3Dsns_Copy%26tid%3Dwhite_backgroup_101 
This is the store, if you search for "gu10" it will show you many spotlight options.

**Comment by Johnreturns** [comment]
This is my config currently
 "devices": [
                {
                    "name": "Smart Bulb 3",
                    "type": "RGBTWLight",
                    "manufacturer": "AliExpress",
                    "model": "ZN216635",
                    "id": "845772364c11ae09cb67",
                    "key": "01b2981236cc2bf6",
                    "dpPower": "20",
                    "dpMode": "21",
                    "dpBrightness": "22",
                    "dpColorTemperature": "23",
                    "dpColor": "24",
                    "minWhiteColor": "0",
                    "maxWhiteColor": "1000",
                    "colorfunction": "HSB",
                    "scaleWhiteColor": "0",
                    "scaleBrightness": "0"
                }
            ]

**Comment by Johnreturns** [comment]
"devices": [
                {
                    "name": "Smart Bulb 3",
                    "type": "RGBTWLight",
                    "manufacturer": "AliExpress",
                    "model": "ZN216635",
                    "id": "xxxxxxxxx",
                    "key": "xxxxxxxxx",
                    "dpPower": "20",
                    "dpMode": "21",
                    "dpBrightness": "22",
                    "dpColorTemperature": "23",
                    "dpColor": "24",
                    "minWhiteColor": "0",
                    "maxWhiteColor": "1000",
                    "colorfunction": "HSB",
                    "scaleWhiteColor": "0",
                    "scaleBrightness": "0"
                }
            ]

**Comment by nrtkin** [comment]
> You can find the device schema in the Tuya int website, where you got your ID/keys.

Hi, 
How can I extract the datapoint identifier from the device Schema? Or is there any descriptions for the identifiers in the code and where I have to look?
Thank you

**Comment by ElphaX** [comment]
@nrtkin It's quite a guessing game but often in order with the signature shown in logs.
