### ISSUE TITLE
New Device: Treatlife Glowlight

### ISSUE THREAD

**Issue by SirGc** [iRayanKhan/homebridge-tuya#272]
**Describe your device**
https://www.amazon.com/Treatlife-Bedrooms-Assistant-SmartThings-Dimmable/dp/B08RDT8HQ4

Dimmable Color and White tunable table light

**Partial Support?**

No

**Device Schema**
```
"devices": [
                {
                    "type": "RGBTWLight",
                    "name": "Glow Light",
                    "id": "eb85dca0f2c9219556fliv",
                    "key": "XXX",
                    "manufacturer": "Treatlife",
                    "model": "Glowlight NL10"
                }
            ],
            "platform": "TuyaLan"
        }
```

**Additional context**
Commands are sent from the Home app and show up in the Homebridge console, yet nothing happens.

This was showing up in the console
>[4/27/2021, 5:14:15 PM] [TuyaLan] Marked Glow Light unreachable by faulting Service.Glow Light.On
>[4/27/2021, 5:14:15 PM] [TuyaLan] Starting discovery...
>[4/27/2021, 5:14:15 PM] [TuyaDiscovery] Discovery started on port 6666.
>[TuyaDiscovery] Discovery started on port 6667.

>[4/27/2021, 5:14:16 PM] [TuyaLan] Discovered Glow Light (eb85dca0f2c9219556fliv) identified as RGBTWLight (3.3)
>[Tuya] Changing ping gap for Glow Light to 9s
>[Tuya DEBUG] reconnect called for Glow Light
>[4/27/2021, 5:14:16 PM] [TuyaLan] Connected to Glow Light
>[Tuya] Sending first query to Glow Light (3.3)
>[Tuya] Heard back from Glow Light with command 10
>[4/27/2021, 5:14:16 PM] [TuyaLan] Ready to handle Glow Light (RGBTWLight:3.3) with signature {"20":true,"21":"colour","22":200,"23":5,"24":"00f303e803e8","25":"000e0d0000000000000000c80000","26":0}
>[Tuya] Color format for Glow Light (3.3) is undetectable.
>[4/27/2021, 5:14:16 PM] [homebridge-tuya] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
>Initializing HAP-NodeJS v0.9.4...
>Initializing HAP-NodeJS v0.9.4...
>Initializing HAP-NodeJS v0.9.4...
>Initializing HAP-NodeJS v0.9.4...

>[4/27/2021, 5:14:20 PM] [Tuya DEBUG] decrementing this._connectionAttempts, currently 2
>[Tuya DEBUG] decrementing this._connectionAttempts, currently 1
>[Tuya DEBUG] decrementing this._connectionAttempts, currently 2
>[Tuya DEBUG] decrementing this._connectionAttempts, currently 1

The devices work with the [homebridge-tuya-web](https://github.com/milo526/homebridge-tuya-web) plugin.

**Comment by iRayanKhan** [comment]
You need to add the DP points. Please read the readME.

**Comment by SirGc** [comment]
Ok. I think I found what goes there

```
{
                    "type": "RGBTWLight",
                    "name": "Glow Light - Local",
                    "id": "eb85dca0f2c9219556fliv",
                    "key": "14e406996608501d",
                    "manufacturer": "Treatlife",
                    "model": "Glowlight NL10",
                    "dpPower": 1,
                    "dpBrightness": 3,
                    "dpColorTemperature": 4,
                    "minWhiteColor": 0,
                    "maxWhiteColor": 1000,
                    "dpMode": 2,
                    "dpColor": 5,
                    "scaleBrightness": 1000,
                    "scaleWhiteColor": 1000
                },
```

This is from the Tuya IoT Platform Device details.


Code | Type | Values
-- | -- | --
switch_led | Boolean | {true,false}
work_mode | Enum | {"range":["white","colour","scene","music"]}
bright_value_v2 | Integer | {"min":10,"max":1000,"scale":0,"step":1}
temp_value_v2 | Integer | {"min":0,"max":1000,"scale":0,"step":1}
colour_data_v2 | Json | {}
scene_data_v2 | Json | {}
countdown_1 | Integer | {"unit":"s","min":0,"max":86400,"scale":0,"step":1}
music_data | Json | {}
control_data | Json | {}
rhythm_mode | Raw | {"maxlen":255}
sleep_mode | Raw | {"maxlen":255}
wakeup_mode | Raw | {"maxlen":255}

Is correct? I still can't control this light with these DP points in the config. I can't even turn it on.

**Comment by SirGc** [comment]
I found this in the console. Are these the DP points? What is what?
>[4/28/2021, 5:58:39 PM] [TuyaLan] Ready to handle Glow Light - Local (RGBTWLight:3.3) with signature {"20":false,"21":"white","22":1000,"23":313,"24":"016302620244","25":"000e0d0000000000000000c80000","26":0}
[Tuya] Color format for Glow Light - Local (3.3) is undetectable.

**Comment by ElphaX** [comment]
Change the following options in your config and it should work:

                    "dpPower": 20,
                    "dpBrightness": 22,
                    "dpColorTemperature": 23,
                    "minWhiteColor": 0,
                    "maxWhiteColor": 1000,
                    "dpMode": 2,
                    "dpColor": 5

Let me know how you go with this!

**Comment by SirGc** [comment]
Ok. Great. Thanks for the help. That works.
I'm getting this in the log

>[Tuya] Sending Glow Light - Local {"21":"colour","24":"016103e80244"}
>[Tuya] Heard back from Glow Light - Local with command 8
>[Tuya] Heard back from Glow Light - Local with command 8

**Comment by ElphaX** [comment]
Good news! And yes we’ll be hiding those logs in the next update 😊
