### ISSUE TITLE
New Device: tuya double wall socket (UK) 

### ISSUE THREAD

**Issue by tomp10000** [iRayanKhan/homebridge-tuya#274]
**Describe your device**

I bought this device, a double smart wall socket, from ebay, but it doesn't seem to work with this tuya plugin or any of the others. I have plenty of tuya devices of all sorts of different kinds and have never encountered a problem like this before. I don't think this device is currently supported.

https://www.ebay.co.uk/itm/193465423461?hash=item2d0b701665:g:sMwAAOSwj-BdHvD3

**Partial Support?**

No. The outlet DP will create an icon for it but the icon does not control the sockets.

**Comment by ElphaX** [comment]
Did you set the datapoints in the config? Please post your config, and device schema.

More info needed. Still an issue? Please re-open if relevant.
