### ISSUE TITLE
New Device: ME102H thermostat

### ISSUE THREAD

**Issue by vinste** [iRayanKhan/homebridge-tuya#281]
Smart Thermostat ME102H: thermostat for electric floor heating

Device on/off is supported with simpleheater type, but target and current temps are not right.

dpCurrentTemperature index should be '24'
dpDesiredTemperature should be '16'

I have a ready-to-push branch with a tested new 'ComplexHeater' accessory if you like

**Comment by vinste** [comment]
Understood that I can override the default DP in the config file, my bad

**Comment by Anzic23** [comment]
I set dpCurrentTemperature index should be '24' and dpDesiredTemperature should be '16' in config, but can't set DesiredTemperature. Who can suggest how to solve the problem?
@vinste does this thermostat work with this plug-in?
