### ISSUE TITLE
Failed to parse discovery response on port 6667???

### ISSUE THREAD

**Issue by Raiden38** [iRayanKhan/homebridge-tuya#283]
I am not sure what that means... I try to add some light (RGBTWLights or even SimpleLights) and I get this error:

[17/05/2021, 20:45:46] [TuyaLan] Discovered Dehors (XXXXXXX) identified as RGBTWLight (3.3)
[Tuya] Changing ping gap for Dehors to 9s
[TuyaDiscovery] Failed to parse discovery response on port 6667: {"ip":"192.168.0.35","gwId":"XXXXXXXXX","active":2,"ablilty":0,"encrypt":true,"productKey":"keyg7fga8utjq4zz","version":"3.3"}
[TuyaDiscovery] Failed to parse discovery raw message on port 6667: 000055aa00000000000000130000009c0000000023d01e5fef56833314cef60fb086ed33ab55f9fe6aadbdb1e0a8a8902ed5a5d55433d1385cba75e927e370bf793657a56a1c2fdfbed0c1e8fecc0f3fc7391abdc2fb8459b1155fc75d4bf6699f92cba4c0ba520148045e7605fa0498dfea5aabb04cec9c94b4d801e9b6c482895d2e268ab948b14108be42ed345d439d1bc90f6eda8eea40e93b1e3fc14a2570e18279e38f1a280000aa55

**Comment by grzegorz914** [comment]
same for me

**Comment by mreed5168** [comment]
Same

**Comment by neek0la** [comment]
i too have the same issue

**Comment by neek0la** [comment]
Fixed my problem.
Make sure you enter the manufacturers details in the config.

This fixed my issue

**Comment by grzegorz914** [comment]
Fixed for me too, must be bug.

**Comment by ElphaX** [comment]
Device requires a default manufacturer setup to minimise user reports for better plugin experience, closing for now.
