### ISSUE TITLE
Getting wrong status on master power button for power strip

### ISSUE THREAD

**Issue by explorador** [iRayanKhan/homebridge-tuya#29]
master switch (dps: 6) is getting a value of 0 and homekit always says it's off when I close/reopen the app. This is the output when master switch is on:
`{ devId: 'xxxxxxxxxxxxxxxxxxxxx',
  dps: { '1': true, '2': true, '3': true, '4': true, '5': true, '6': 0 } }`
Output when master switch is off:
`{ devId: 'xxxxxxxxxxxxxxxxxxxxx',
  dps: 
   { '1': false,
     '2': false,
     '3': false,
     '4': false,
     '5': false,
     '6': 0 } }`

**Comment by codetheweb** [comment]
What does your `config.json` look like?

**Comment by explorador** [comment]
`"platforms": [
		{
			"platform": "TuyaPlatform",
			"name": "TuyaPlatform",
			"devices": [
				{
					"name": "Power Strip",
					"id": "xxxxxxxxxxxxxxxxxxxxx",
					"key": "xxxxxxxxxxxxxxxxxxxxx",
					"ip": "xxxxxxxxxxxxxxxxxxxxx",
					"options": {
						"dps": 6
					}
				}
			]
		}
	]`

**Comment by explorador** [comment]
Power strip turns on/off fine, the status is just wrong

**Comment by codetheweb** [comment]
It doesn't look to me like DPS 6 actually controls anything... have you tried other DPS indices?

**Comment by codetheweb** [comment]
Oh, I see the issue.

There's no single status property for the master switch, it's just whether or not all other properties are set to true.

Unfortunately, in its current state, homebridge-tuya can't really work with devices like this.  My recommendation would be to make a scene that turns all properties on and off.

I'll look into adding support for this whenever I next have my one-day hackathon of updating my NPM modules. 😛

**Comment by codetheweb** [comment]
(I'm copy/pasting this into every open issue and PR.)

This plugin is now deprecated, as I don't have enough time to maintain it along with other TuyAPI related projects. Please use AMoo-Miki's [homebridge-tuya-lan](https://www.npmjs.com/package/homebridge-tuya-lan) plugin instead. (Or, you can continue to use this plugin, but I will not be giving support or adding any new devices.)

I'm sorry about this, but this plugin is taking a disproportionate amount of my time that I believe is better spent making TuyAPI more stable and adding more tools to the ecosystem.

**Comment by iRayanKhan** [comment]
Closing; inactive thread. If you need support please re-open this issue.
