### ISSUE TITLE
Error displayed in Apple Home app but device is working correctly 

### ISSUE THREAD

**Issue by konstantinjdobler** [iRayanKhan/homebridge-tuya#290]
**Checklist**
- [x] I have read the common issues wiki page
- [x] I have checked to make sure the plugin is up to date

**Describe the bug**
I have added an RGB lamp with this plugin to home bridge and the functionality is working great, thanks! However, every time I turn a scene containing the RGB lamp on, the Apple Home app indicates that something went wrong in the scene icon. But the device worked perfectly. If I turn the scene off, no error. If I turn the *single* lamp itself on or off individually, I also get no error message. This is how it looks in the Home app (same error happens in the iOS app):
<img width="901" alt="Bildschirmfoto 2021-05-22 um 17 03 10" src="https://user-images.githubusercontent.com/28780372/119231185-c5b0a300-bb1f-11eb-9cd2-1807e02c5051.png">

**Environment (please complete the following information):**
 - OS: Raspbian on Raspberry Pi 4
 - Node Version: 14.17
 - Plugin Version: 2.0.1
-  Accessory Type: RGBTWLight

**Additional context**
This is the log output when turning on one example scene that results in the error:
```
[Tuya] Sending Stehlampe {"20":true}
[Tuya] Sending Stehlampe {"22":607}
[Tuya] setColorTemperature: 76
[Tuya] Sending Stehlampe {"21":"white","23":847}
[Tuya] Heard back from Stehlampe with command 8
[Tuya] Heard back from Stehlampe with command 8
[Tuya] Heard back from Stehlampe with command 8
```
Log when turning scene off:
```
[Tuya] Sending Stehlampe {"20":false}
[Tuya] Heard back from Stehlampe with command 8
```
Log Tuning individual lamp off and on:
```
[Tuya] Sending Stehlampe {"20":false}
[Tuya] Heard back from Stehlampe with command 8
[Tuya] Sending Stehlampe {"20":true}
[Tuya] Heard back from Stehlampe with command 8
```

So from the logs I believe it has something to do with the multiple `command 8`'s that are being sent back. Sorry @iRayanKhan for the long issue, but do you know were this issue could come from / what I can do to fix it?

Config.json:
```json
{
    "devices": [
        {
            "type": "RGBTWLight",
            "name": "Stehlampe",
            "id": "xxx",
            "key": "xxx",
            "manufacturer": "Anten",
            "dpPower": 20,
            "dpBrightness": 22,
            "dpColorTemperature": 23,
            "dpMode": 21,
            "dpColor": 24,
            "colorFunction": "HSB",
            "scaleBrightness": 1000,
            "scaleWhiteColor": 1000
        }
    ],
    "platform": "TuyaLan"
}
```

**Comment by iRayanKhan** [comment]
Thanks for the detailed issue, I've had this issue too with non homebridge devices. 

Try restarting your home hubs.

**Comment by ElphaX** [comment]
Yeah it seems like the issue appears when other devices can't confirm whether the scene ran or not, super weird. And also @konstantinjdobler the command 8 is often just the device telling us its alive ;)
