### ISSUE TITLE
Cannot select WhiteColour/Temperature of RGBTWLight

### ISSUE THREAD

**Issue by AnonymousPea** [iRayanKhan/homebridge-tuya#305]
**Checklist**
- [ ] I have read the common issues wiki page
- [ ] I have checked to make sure the plugin is up to date

**Describe the bug**
Cannot select the WhiteColour (temperature) of light.

I have been reading all the other issues regarding lighting not working and I have managed to fix some of the issues by adjusting what others have said, and thus fix most of my lighting issues, but I still have one issue. 
I have colour working, adaptive lighting working, and % working. The issue I am having is that I can't select a the temperature of the light, (only RGB works) except when in adaptive lighting mode, temperature works through adaptive, but I can not specifically set a temperature. 

**To Reproduce**

                    "type": "RGBTWLight",
                    "name": "Lamp",
                    "id": "....",
                    "key": ".....",
                    "manufacturer": "Kogan",
                    "model": "Kogan SmarterHome Light",
                    "dpPower": 20,
                    "dpColorTemperature": 23,
                    "dpMode": 21,
                    "dpColor": 24,
                    "colorFunction": "HSB",
                    "scaleBrightness": 1000,
                    "scaleWhiteColor": 1000,
                    "minBrightness": 10,
                    "maxWhiteColour": 221,
                    "dpBrightness": 22
                }

in HomeKit App, try to change temperature of light. 

**Expected behavior**
I should be able to select the colour of the light, **or the temperature**. I should not have to select a "colour" that is similar to the desired temperature. 

**Environment (please complete the following information):**
 - Raspberry Pi with Homebridge v4.41.1
-  iOS version: 14.6
-  Homehubs: Apple TV & HomePod Miini
 - Plugin Version: v2.0.1
-  Accessory Type: Tuya RBG and White 
https://www.kogan.com/au/buy/kogan-smarterhome-5w-colour-warmcool-white-smart-bulb-e14-wi-fi/?utm_source=google&utm_medium=product_listing_ads&gclid=CjwKCAjwz_WGBhA1EiwAUAxIcfKU8_Q4XRENCpIbQa9Vevv_BYnsV76GSPIwU4ZlU0XsCTYLz7Q8BhoCVl0QAvD_BwE

**Comment by ElphaX** [comment]
Please try after the latest update.

Still an issue, please re-open if relevant.
