### ISSUE TITLE
Invitation from Official Tuya smart.

### ISSUE THREAD

**Issue by GITOLEO** [iRayanKhan/homebridge-tuya#306]
Dear Sir,
This is from Tuya Smart.We have seen your great work here which helped the Tuya devices to be connected into IoT. We would like invite you to join our Homebridge Tuya Plug-in Beta Test with Tuya support. Your feedback would be helpful to the whole community! Check we have cooperated with Home Assistant Official for improving the integration and users experience. And we hope we could help the homebridge community for their needs as well.
![image](https://user-images.githubusercontent.com/85163056/124347043-c5262480-dc14-11eb-88a0-c75b9c986561.png)
If you are interested in,pls let us know.
Our contact:devops@tuya.com.
Skype:Devops-Tuya.
Good day!
Best Regards!

**Comment by qthatswho** [comment]
@iRayanKhan Have you seen this request?

**Comment by ElphaX** [comment]
Hi! Yes, we’re also currently in talks with their team to bring the community the best outcome. Unfortunately we can’t say much more at the moment but the official Tuya team looks to want nothing but the best for all of you
