### ISSUE TITLE
Support for All Fan Regulators

### ISSUE THREAD

**Issue by sahil-bawa** [iRayanKhan/homebridge-tuya#307]
**Checklist**
- [x] I have read the common issues wiki page
- [x] I have checked to make sure the plugin is up to date

**Describe the bug**
Indian Fan Regulators have minimum rotation speed of 1 and maximum of 5. When you send 33%, 67%, 100% rotation speeds to these regulators, they crash and have to be restarted. The plugin doesn't allow changing dpRotationSpeed more than 3. Also, the json being sent is {"3": "2"} for rotation speed 2. I believe HomeMate's regulators are expecting "2": "2" (not sure have to check. https://www.reddit.com/r/homebridge/comments/odd60v/help_homemate_tuyacompatible_ceiling_fan/

**To Reproduce**
Add HomeMate 5-speed regulator to smart life and then HB. try the fan speed change.

**Expected behavior**
Fan speed should be controlled between speeds 1 to 5 and on/off should work.

**Screenshots**

**Environment (please complete the following information):**
 - OS: HomeBridge)S
-  iOS version: 14
-  Homehubs: 
 - Node Version: 
 - Plugin Version:
-  Accessory Type: 5-Speed Fan Regulator (India)

**Additional context**

**Comment by sahil-bawa** [comment]
reddit question reference: https://www.reddit.com/r/homebridge/comments/odd60v/help_homemate_tuyacompatible_ceiling_fan/

**Comment by ElphaX** [comment]
Fan v2 allows for 5 speed regulation. Please use that with the correct dp values.

Still an issue, please re-open if relevant.
