### ISSUE TITLE
Cannot see device in Home App

### ISSUE THREAD

**Issue by biocross** [iRayanKhan/homebridge-tuya#310]
**Checklist**
- [x] I have read the common issues wiki page
- [x] I have checked to make sure the plugin is up to date

**Describe the bug**
First of all, thank you for your work on this plugin. 

I have a smart IR transmitter that controls my Air Conditioner and TV via Infrared. I've gone through the steps in the readme and wiki, and have configured the plugin to expose my Air Conditioner to HomeKit.

My configuration looks like this: 

```
{
            "options": {
                "username": "XXX",
                "password": "XXX",
                "accessId": "XXX",
                "accessKey": "XXX",
                "lang": "en",
                "projectType": "2",
                "appSchema": "tuyaSmart",
                "countryCode": 123,
                "debug": true
            },
            "name": "TuyaPlatform",
            "platform": "TuyaPlatform",
            "devices": [
                {
                    "name": "Living Room Cooler",
                    "type": "AirConditioner",
                    "manufacturer": "Daikin",
                    "model": "XXX",
                    "id": "XXX",
                    "key": "XXX",
                    "noHeat": true,
                    "minTemperature": 19,
                    "maxTemperature": 31,
                    "minTemperatureSteps": 1
                }
            ]
        }
```

I can even see in the logs that the plugin discovers my devices:

```
Adding: Smart IR (wnykq / XXXX)
Adding: Air Conditioning (infrared_ac / XXXX)
Adding: TV (infrared_tv / XXXX)
```

My issue is, I can't see any of these devices in my actual `Home` app, or the`Accessories` tab in homebridge config UI.

**Expected behavior**
The accessories added in the config should show up in the Home app.

**Environment (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster)
-  iOS version: 14.7
-  Homehubs: ?
 - Node Version: v14.17.2
 - Plugin Version: 1.3.0
-  Accessory Type: Air Conditioner (via Smart IR)

**Comment by iRayanKhan** [comment]
Hey, this isn't my plugin. My plugin just called Tuya, not TuyaPlatfrom

**Comment by ElphaX** [comment]
Incorrect Issue, closed.
