### ISSUE TITLE
Extract Tuya Local Keys - New Tutorial Video

### ISSUE THREAD

**Issue by eddiedsouza** [iRayanKhan/homebridge-tuya#321]
Released a updated tutorial to get the [Tuya Local Keys](https://youtu.be/FpY-xsY-pZ8)

Get the local key in three easy steps with absolutely no line of code and its all done in their website.

**Comment by iRayanKhan** [comment]
Hey @eddiedsouza, thanks for letting me know. Are you able to update the written wiki too?

Thanks,
 Rayan

**Comment by EddieDSuza** [comment]
[Page Updated](https://github.com/iRayanKhan/homebridge-tuya/wiki/Get-Local-Keys-for-Your-Devices)
