### ISSUE TITLE
devices doesn't respond 

### ISSUE THREAD

**Issue by xgrm** [iRayanKhan/homebridge-tuya#327]
**Describe the bug**
hi,
i'm using your plugin for few months and for some reason this week the devices on homeKit don't respond..
after i'm restart the bridge they come back but after a while they do it again..
the debug show this when a device stop working:

[Tuya] Socket had a problem and will reconnect to Device_name (EHOSTUNREACH)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya] Socket had a problem and will reconnect to Device_name (EHOSTUNREACH)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya] Socket had a problem and will reconnect to Device_name (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya] Socket had a problem and will reconnect to Device_name (Error: ERR_CONNECTION_TIMED_OUT)

**To Reproduce**

restart the child bridge

**Environment (please complete the following information):**
 - OS: Raspbian GNU/Linux Buster (10)
 -  iOS version:  15.0
-  Homehubs: homebridge
 - Node Version: 14.16.0
 - Plugin Version: 2.0.1
-  Accessory Type: light, simple switch

**Comment by petervanoostveen** [comment]
Happened to me as well but found the culprit(s).
If I connect too many WiFi IP Cameras I get the same errors, reducing the
number of WiFi IP Cams (or connecting them via Ethernet) solves the problem.
I'm 100% stable with 50+ Tuya devices.

**Comment by xgrm** [comment]
H,
The truth is that the problem was in my router he was down for one minute every day and when he came up he gave different ip to the device’s..
After I gave a static ip to every device the problem solved
