### ISSUE TITLE
Connectivity errors with SimpleLight devices since MacOs Monterey

### ISSUE THREAD

**Issue by AlainKaim** [iRayanKhan/homebridge-tuya#336]
**Checklist**
- [ x] I have read the common issues wiki page
- [ x] I have checked to make sure the plugin is up to date

**Describe the bug**
Homebridge is running on my Mac since ages.
I have upgraded to MacOs Monterey last week, and since that time, three of my SimpleLight have trouble to connect with the Tuya plugin. Their brands are Waza and SmartPlug.
The three SimpleLight are working well with Tuya and Alexa apps, so they are well connected through my wifi network.
And I have another Waza SimpleLight and many other devices which are working well with Homebridge.

Do I need to upgrade something, and what ? Thanks for your help!

**To Reproduce**
Even after rebooting Homebridge or even the wifi router, I see these error messages in the log.
And in Home app, the devices Est, Ouest and Canape are not responding.

[Tuya] Socket had a problem and will reconnect to Canape (EHOSTDOWN)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya] Socket had a problem and will reconnect to Est (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya] Socket had a problem and will reconnect to Ouest (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya] Socket had a problem and will reconnect to Canape (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] decrementing this._connectionAttempts, currently 4
[Tuya DEBUG] decrementing this._connectionAttempts, currently 3
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Canape
[Tuya] Socket had a problem and will reconnect to Canape (EHOSTDOWN)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Est
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Ouest
[Tuya] Socket had a problem and will reconnect to Canape (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] decrementing this._connectionAttempts, currently 4
[Tuya DEBUG] decrementing this._connectionAttempts, currently 3
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Canape
[Tuya DEBUG] decrementing this._connectionAttempts, currently 4
[Tuya DEBUG] decrementing this._connectionAttempts, currently 3
[Tuya DEBUG] decrementing this._connectionAttempts, currently 2
[Tuya DEBUG] decrementing this._connectionAttempts, currently 1
[Tuya DEBUG] decrementing this._connectionAttempts, currently 2
[Tuya DEBUG] decrementing this._connectionAttempts, currently 1
[Tuya] Socket had a problem and will reconnect to Canape (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya DEBUG] decrementing this._connectionAttempts, currently 2
[Tuya DEBUG] decrementing this._connectionAttempts, currently 1
[Tuya] Socket had a problem and will reconnect to Canape (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Canape
[Tuya] Socket had a problem and will reconnect to Canape (EHOSTDOWN)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya] Socket had a problem and will reconnect to Canape (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Canape
[Tuya] Socket had a problem and will reconnect to Canape (EHOSTDOWN)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya DEBUG] decrementing this._connectionAttempts, currently 4
[Tuya DEBUG] decrementing this._connectionAttempts, currently 3
[Tuya] Socket had a problem and will reconnect to Canape (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Canape
[Tuya] Socket had a problem and will reconnect to Canape (EHOSTDOWN)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya] Socket had a problem and will reconnect to Est (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya] Socket had a problem and will reconnect to Ouest (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] after error setting _connect in 5000ms
[Tuya DEBUG] decrementing this._connectionAttempts, currently 4
[Tuya DEBUG] decrementing this._connectionAttempts, currently 3
[Tuya] Socket had a problem and will reconnect to Canape (Error: ERR_CONNECTION_TIMED_OUT)
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Canape
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Est
[Tuya DEBUG] executing _connect after 5000ms delay
[Tuya DEBUG] reconnect called for Ouest

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOs Monterey 12.0.1
-  iOS version: 15.1
-  Homehubs: 
 - Node Version: v14.16.0.
 - Plugin Version: 2.0.1
-  Accessory Type : SimpleLight

**Additional context**

**Comment by AlainKaim** [comment]
Sorry for this wrong diagnosis: rebooting my (Netgear Orbi) wifi router solved the issue.

**Comment by artwayne420** [comment]
Stop sending me fucking emails
