### ISSUE TITLE
Variable Positioning of Curtains

### ISSUE THREAD

**Issue by codetheweb** [iRayanKhan/homebridge-tuya#35]
Pinging @kalu1 for updates.

**Comment by galzil** [comment]
Thanks for the plugin, I'm not sure we can get the curtain's position' I don't see it in the app as well.
I can't get it to stop though, only up and down

**Comment by kalu1** [comment]
Hey, galzil, positioning hasn’t worked yet. But in HomeKit it looks like that it’s working. Just press the curtain button (3D touch) and there is a slider.

**Comment by kalu1** [comment]
Yop the same behavior like mine. That’s the reason why codetheweb create this issue. Just wait 😉.

**Comment by codetheweb** [comment]
(I'm copy/pasting this into every open issue and PR.)

This plugin is now deprecated, as I don't have enough time to maintain it along with other TuyAPI related projects. Please use AMoo-Miki's [homebridge-tuya-lan](https://www.npmjs.com/package/homebridge-tuya-lan) plugin instead. (Or, you can continue to use this plugin, but I will not be giving support or adding any new devices.)

I'm sorry about this, but this plugin is taking a disproportionate amount of my time that I believe is better spent making TuyAPI more stable and adding more tools to the ecosystem.

**Comment by iRayanKhan** [comment]
Closing; inactive thread. If you need support please re-open this issue.
