### ISSUE TITLE
Is this plugin still maintained?

### ISSUE THREAD

**Issue by jfmach** [iRayanKhan/homebridge-tuya#352]
Hello!

I was wondering is this plugin is still being maintained? It works fantastic but I have not seen an update recently.
Thank you!

- Jeff

**Comment by homefuzz-oz** [comment]
Same question here @iRayanKhan. 
reason is I am thinking of having a stab to include the fakegato energy history feature, and saw that you had a look at it once, so was wondering if there is some prototype I should work off or just go off the latest main?

**Comment by iRayanKhan** [comment]
I'm still here, just been busy with school, and enjoyed my break. I'll have an update out eventually. Once I merge all the PR's I'll have a development branch for people to fork off of.

**Comment by iRayanKhan** [comment]
> Same question here @iRayanKhan. 
> 
> reason is I am thinking of having a stab to include the fakegato energy history feature, and saw that you had a look at it once, so was wondering if there is some prototype I should work off or just go off the latest main?

You can open a PR based off main. You will most likely have to rebase.

**Comment by bkowalk** [comment]
@iRayanKhan THANK YOU SO MUCH for keeping this plugin going! Just found this today after months of my Tuya fan controllers being the only smart item in my house I couldn't get into Homebridge. Then I finally found your repo here and my god does it feel satisfying finally getting these working. 

Thank you!!!

**Comment by iRayanKhan** [comment]
Glad to hear @bkowalk.

Closing this issue for now. Hoping to have a release out in 2-3 weeks, and a beta this weekend. If anyone has changes they would like to test, please do so off main, then beta once it's updated.
