### ISSUE TITLE
Just wondering if this plugin is still being supported?

### ISSUE THREAD

**Issue by nefariouslegion** [iRayanKhan/homebridge-tuya#383]
Looking into using this plugin for it's adaptive lighting. But it doesn't seem it's been updated in quite some time. So I'm wondering if it's still being maintained or is it just dead?

**Comment by iRayanKhan** [comment]
Hey there, this plugin still works, but I haven't had time to dedicate to add new features. 

Adaptive lighting works. 

I plan to go through the pull requests and do minor house keeping in December.

**Comment by nefariouslegion** [comment]
Cool, thank you for letting me know!

**Comment by crunchtime2k** [comment]
Thank you for making this. Its a huge help to many ryan

**Comment by michael-j-green** [comment]
@iRayanKhan; thankyou for building and maintaining this plugin!

I just wanted to know if you had any plans to add other community members to the project (if there aren't already) to help you with maintaining it? This way updates can continue to be released, while not putting too much of a burden on you.

**Comment by 05TEVE** [comment]
Hi @nefariouslegion, I am helping out now and looking to get a new version published soon. 
I have just pushed a new beta to npm. 3.1.0-beta.2. Looking for testers :)
