### ISSUE TITLE
Can’t get WiFi breakers to work

### ISSUE THREAD

**Issue by hajopaj** [iRayanKhan/homebridge-tuya#39]
Has anyone have any experience with these tuya WiFi breakers?

![img_0185](https://user-images.githubusercontent.com/43090955/51242330-fb598600-197f-11e9-8997-5e35b257d4d9.jpeg)

I’m getting a "no answer" in my home app on iOS while all my other devices are working fine and all ip’s and keys and addresses match the devices they should...

Config.json looks like this:

>>>
{
"accessories" : [
],
"bridge" : {
"username" : "CD:22:3D:E3:CE:41",
"name" : "Homebridge",
"pin" : "031-45-788",
"port" : 0
},
"platforms" : [
{
"platform" : "TuyaPlatform",
"name" : "TuyaPlatform",
"devices" : [
{
"id" : "84622486600194ae6499",
"key" : "287f539b98a61de5",
"name" : "Stehlampe alt",
"ip" : "192.168.178.63"
},
{
"id" : "84622486600194ae77fd",
"key" : "877649743c5ef828",
"name" : "Lampe Box",
"ip" : "192.168.178.22"
},
{
"id" : "0620012384f3eba64ea4",
"key" : "7feaf531a4b4a9f8",
"name" : "Schreibtischlampe",
"ip" : "192.168.178.68"
},
{
"id" : "06200123ecfabc1c5cac",
"key" : "f1104e9dca4760e9",
"name" : "Drucker",
"ip" : "192.168.178.35"
},
{
"id" : "06200123ecfabc1cb3f7",
"key" : "31b77d11376b142a",
"name" : "Wickeltisch Lampe",
"ip" : "192.168.178.26"
},
{
"id" : "06200123ecfabc1cb870",
"key" : "1719e1a50573c547",
"name" : "Stehlampe",
"ip" : "192.168.178.23"
},
{
"id" : "6cf5b5422dac85e2eb21ux",
"key" : "847c690b0a6c37c2",
"name" : "Esszimmertisch 1",
"ip" : "192.168.178.31"
},
{
"id" : "6ca0fa68a6c570c1dasyfh",
"key" : "f03e19f644e5ae4c",
"name" : "Esszimmertisch 2",
"ip" : "192.168.178.32"
}
]
}
]
}
<<<

The last two devices are the ones not responding.
I added "type" : "generic" to both of them but still no change

Anyone can help?

**Comment by codetheweb** [comment]
I assume they work correctly with the app?

Are you able to ping those IP addresses from the machine running Homebridge?

**Comment by codetheweb** [comment]
What's the output of `DEBUG=* homebridge" when you toggle the unresponsive devices a few times?

**Comment by hajopaj** [comment]
![img_0186](https://user-images.githubusercontent.com/43090955/51415165-28bb5500-1b75-11e9-9a95-4de3e10d6387.jpeg)
First this

**Comment by hajopaj** [comment]
![img_0187](https://user-images.githubusercontent.com/43090955/51415174-37a20780-1b75-11e9-9d8f-e15aebcd7678.jpeg)
Then that

**Comment by codetheweb** [comment]
Gave it a quick search and I don't think the error is this plugin's fault.  People have suggested [changing parameters on avahi](https://github.com/nfarina/homebridge/issues/1923) as well as making sure that there's not an orphan Homebridge process running from the same config folder on the same host.

You may also want to try deleting the `persist/` and `accessories/` folders in your Homebridge config location.

**Comment by hajopaj** [comment]
I tried changing the cache size in Avahi and deleting both folders.
Afterwards I got a "no answer" from all of my devices in home app and still could not toggle the devices although they are displayed (but also always were) in my Homebridge-config-ui.

**Comment by hajopaj** [comment]
Debug is the same as before...

**Comment by codetheweb** [comment]
I'm sorry, but if you're still getting the same error in the first screenshot I can't help as it's more a Homebridge problem.  You may want to open an issue [here](https://github.com/nfarina/homebridge/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

**Comment by hajopaj** [comment]
I did some more "research" and I noticed that in the sharedprefs data in Nox there is a difference in the "dps" parts of the preferences.xml file.
For the not working switches it says:

"dps": {"1":false,"101":"0","102":0}

and for all the working ones it says:

"dps":{"1":false,"11":0}

Could it be that I just have to add some "options" and "dps" to config.json? - And if yes, any idea how are they supposed to look?

Seems kind of probable to me since debug says everything is working fine...

**Comment by codetheweb** [comment]
As you're not getting an error that seems related to TuyAPI, I would be surprised if that was the problem.

You could try controlling your device with [tuya-cli](https://www.npmjs.com/package/@tuyapi/cli) using the same parameters that are in your `config.json`.  If that works, it's very unlikely that the source of problems is this plugin.  If not, we'll have to do some more investigation.

**Comment by hajopaj** [comment]
![img_0188](https://user-images.githubusercontent.com/43090955/51788355-67f13380-217d-11e9-9f82-3dd0cb148939.jpeg)

**Comment by codetheweb** [comment]
It's possible you have the wrong key for your device, as data would then not be encoded or decoded correctly (so set and get both fail).

You might want to try acquiring the keys again.  Are you doing it with `tuya-cli list-app` or some other method?

**Comment by hajopaj** [comment]
I checked again but I aquired the code with Tuya-cli and it seems to be right.
As you can see in the second picture I was able to send the set command but nothing 
happened.
I am sure I used the correct keys since I directly copied them out of Tuya-cli.
No ideal why it won‘t switch anything...

**Comment by codetheweb** [comment]
Hmm... do you have other devices of the same model that work?

**Comment by hajopaj** [comment]
No I don’t have any other devices of that make. They don’t have a brand name as you can see on the picture but I thought if they run with tuya smart, I can make them run with Homebridge-tuya as well...

I also thought about flashing the devices with tasmota. - do you think that could make it work?
I have to use another plugin as far as I understood or could they still work with Homebridge-tuya then?

**Comment by hajopaj** [comment]
Any other idea what else I could possibly do?
Since I don‘t get any errors I don‘t know what to fix...

**Comment by hajopaj** [comment]
pi@raspberrypi:~ $ DEBUG=* node test.js
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'tuyapi'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/test.js:1:78)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)

> Am 31.01.2019 um 20:29 schrieb Max Isom <notifications@github.com>:
> 
> DEBUG=* node test.js

**Comment by hajopaj** [comment]
Do I have to run something else since I am using Homebridge with Raspbian?

**Comment by hajopaj** [comment]
Installed it and did a restart but I’m still getting the same error.

**Comment by codetheweb** [comment]
Hmm, unless you changed your NPM configuration I think that should have worked.

You can also try installing it to your current directory with `npm i tuyapi` (without the `-g` flag).

**Comment by hajopaj** [comment]
Got this:

pi@raspberrypi:~ $ DEBUG=* node test.js
  TuyAPI Payload:  { gwId: '6ca0fa68a6c570c1dasyfh',
  devId: '6ca0fa68a6c570c1dasyfh' } +0ms
  TuyAPI Send attempt 1 +24ms
  TuyAPI Sending this data: 000055aa000000000000000a0000004a7b2267774964223a2236636130666136386136633537306331646173796668222c226465764964223a2236636130666136386136633537306331646173796668227d000000000000aa55 +2ms
  TuyAPI Connect 192.168.178.32 +3ms
  TuyAPI Socket connected. +136ms
  TuyAPI Received data back: 192.168.178.32 +21ms
  TuyAPI 000055aa000000000000000a00000021000000016a736f6e206f626a206461746120756e76616c6964d25378690000aa55 +0ms
  TuyAPI decrypt 192.168.178.32 ¸C}õ:É­ ÿ±Tzp
L>!, 10 +8ms
  TuyAPI Disconnect +2ms
(node:5928) UnhandledPromiseRejectionWarning: ¸C}õ:É­ ÿ±Tzp
L>!,
(node:5928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  TuyAPI Socket closed: 192.168.178.32 +11ms
pi@raspberrypi:~ $

**Comment by codetheweb** [comment]
Ok, your device is returning a packet that when translated into ASCII says `json obj data unvalid`.

The packet you're sending looks fine, so the next step would be for you to capture a session of app activity with Wireshark and send it to me so I can compare the packets TuyAPI is sending with the packets the app sends.

**Comment by hajopaj** [comment]
![img_0197](https://user-images.githubusercontent.com/43090955/52534034-943faf00-2d3c-11e9-94da-469ce30cac50.jpeg)

**Comment by hajopaj** [comment]
I don’t know what you can read out of these...
I used the capture filter "host 192.168.178.32"
Is there a way to capture more packages as I’m noticing that these don’t change in any particular way?

**Comment by codetheweb** [comment]
Thanks for the screenshots, but they're all fundamentally the same packet the device is broadcasting to advertise its IP.

Try setting the filter to your phone's IP.

**Comment by hajopaj** [comment]
I’m sorry, but when I set the "host" filter to my iPhones ip and switch the breakers over the tuya app there is not anything to see in wireshark. I only get "HomeKit" stuff, nothing else

**Comment by codetheweb** [comment]
You might be sniffing on the wrong interface.  I think you need to be sniffing on a wireless interface that's connected to the same network your device is.

**Comment by codetheweb** [comment]
(I'm copy/pasting this into every open issue and PR.)

This plugin is now deprecated, as I don't have enough time to maintain it along with other TuyAPI related projects. Please use AMoo-Miki's [homebridge-tuya-lan](https://www.npmjs.com/package/homebridge-tuya-lan) plugin instead. (Or, you can continue to use this plugin, but I will not be giving support or adding any new devices.)

I'm sorry about this, but this plugin is taking a disproportionate amount of my time that I believe is better spent making TuyAPI more stable and adding more tools to the ecosystem.

**Comment by iRayanKhan** [comment]
Closing; inactive thread. If you need support please re-open this issue.
