### ISSUE TITLE
Plugin Maintained?

### ISSUE THREAD

**Issue by bwp91** [iRayanKhan/homebridge-tuya#429]
Hi @iRayanKhan 

Are you still maintaining this plugin? If not, would you be willing to transfer to homebridge ownership so we can continue the maintenance?

Cheers!

**Comment by dibsies** [comment]
@bwp91--did @iRayanKhan ever get back to you on this? Would love to see this plugin revived with some of the outstanding issues fixed.

**Comment by 05TEVE** [comment]
@dibsies , I have been speaking with @iRayanKhan and got access to the repo so will be looking into pushing a new version soon with some of the fixes included.

**Comment by 05TEVE** [comment]
I have started publishing new versions of this. On NPM there is a new version 3.1.0-beta.1 which has a few different PRs merged in to start.

Please feel free to test it out.

**Comment by bwp91** [comment]
Ah lovely, thanks @05TEVE !
