### ISSUE TITLE
How install and test 3.1.0 Pre-release

### ISSUE THREAD

**Issue by corasaniti** [iRayanKhan/homebridge-tuya#442]
Hi @iRayanKhan 

How can I install version 3.1.0 Pre-release?
If I search in the homebridge GUI or install with npm I can only install the stable version 2.01
I think you are doing a great job, to allow us to use Tuya in "local mode"
Thanks in advance

**Comment by 05TEVE** [comment]
Hi @corasaniti, from the home bridge ui for the plugin you should be able to see an install alternate versions option. In there the latest beta is 3.1.0-beta.13.

**Comment by corasaniti** [comment]
@iRayanKhan 
Do you mean v1.0.3 latest? and not 3.1.0-beta.13 I can't find 3.1.0-beta.13
Thank you

![Cattura1](https://github.com/iRayanKhan/homebridge-tuya/assets/5001932/6a95cc8f-3aa1-4f41-91a7-b5edb45f07b7)
![Immagine1](https://github.com/iRayanKhan/homebridge-tuya/assets/5001932/0eab548e-66b2-445c-81d2-5a4fcbbf0208)

**Comment by 05TEVE** [comment]
Hi, that is my fork of the plugin that I was using for some testing. Please switch to the main verified version Irayankahn:homebridge-tuya. The beta is published there and should be downloadable from the homebridge ui.

**Comment by corasaniti** [comment]
@05TEVE OK thanks here I was able to find it...
![Immagine](https://github.com/iRayanKhan/homebridge-tuya/assets/5001932/33152e3a-b013-4b81-98c7-a9c9d40ed2a8)

**Comment by corasaniti** [comment]
@05TEVE, @iRayanKhan 
I tried version 3.1.0 beta13 of the plugin and it works perfectly. Unfortunately though it has a side effect with my instance of Nodered. The device with a certain IP cannot be connected to Nodered and Homebridge at the same time.

So I am forced to use either Nodered or Homebridge, while with the previous Homebridge cloud plugin I am able to use Nodered (via LAN) and Hombebridge (via cloud) at the same time

However, an excellent job was done, the plugin works very well
Thank you
