### ISSUE TITLE
After Update to Release 3.1.0 all devices/scenes and automations have been deleted in homekit!!!

### ISSUE THREAD

**Issue by drheck** [iRayanKhan/homebridge-tuya#445]
I have installed the update 3.1.0 and all my devices (and the associated scenes and automatiions also) have been deleted in homekit.
Please test and fix this error.
This cost me two hours to get all running again.

**Comment by 05TEVE** [comment]
Apologies for this @drheck . In testing I completed the upgrade and didn't experience this issue. I believe this was most likely related to some of the config schema changes that were included in the PRs between the 2.0.1 and the 3.1.0 version (Some two years worth of changes). 

I do not intend on making any further changes to the schemas so this shouldn't happen again.

**Comment by drheck** [comment]
Okay. I have reinstalled 2.0.1 and the configured new...
I mean i have not seen new devices after deletion of the old ones - but i am not sure.
I will test this with my Homebridge Testsystem.

**Comment by drheck** [comment]
I looked and the disappeared devices are coming after a some minutes...
So i will update and reconfigure...
You can close the issue.
