### ISSUE TITLE
Siri "wasn't able to find anything like that this time"

### ISSUE THREAD

**Issue by Jefronty** [iRayanKhan/homebridge-tuya#47]
Everything still works perfectly well the Home app or from the swipe up UI, but Siri no longer works with any of the devices, always responding with "Sorry, I wasn't able to find anything like that this time."
I haven't update iOS or anything else and I used to be able to use Siri.  Any ideas or suggestions?

**Comment by codetheweb** [comment]
No idea, sorry.  You might want to try restarting your phone if you haven't already.

You might also want to try deleting the `persist/` and `accessories/` folders in your Homebridge config folder, although those shouldn't affect anything.

**Comment by Jefronty** [comment]
Thanks, I have restarted the phone and I've restarted homebridge but no change.

**Comment by codetheweb** [comment]
The only other option I can think of (although it seems a bit drastic) is removing the bridge from HomeKit on your phone, deleting `persist/` and `accessories/`, and changing the MAC address in `config.json` to completely reset everything.

**Comment by codetheweb** [comment]
(I'm copy/pasting this into every open issue and PR.)

This plugin is now deprecated, as I don't have enough time to maintain it along with other TuyAPI related projects. Please use AMoo-Miki's [homebridge-tuya-lan](https://www.npmjs.com/package/homebridge-tuya-lan) plugin instead. (Or, you can continue to use this plugin, but I will not be giving support or adding any new devices.)

I'm sorry about this, but this plugin is taking a disproportionate amount of my time that I believe is better spent making TuyAPI more stable and adding more tools to the ecosystem.

**Comment by iRayanKhan** [comment]
HI @Jefronty,
I also face this issue, and it is an Apple/Siri Parsing issue. Siri doesn't seem to understand what device you are try to control no matter how blatant the name is. This isn't related to the plugin and as such am closing this issue. Hope it resolved for you within the year xD.
