### ISSUE TITLE
3.3 outlet only working at half

### ISSUE THREAD

**Issue by palla89** [iRayanKhan/homebridge-tuya#53]
Hi! I know you're not supporting this project anymore, but the alternative is not updated for the latest firmware and the developer probably has stopped supporting it.

I'm testing yours and after some code changes, I found the way to turn on and off the first "switch" (the main outlet), but even settings "dps" to 2, the USB outlet doesn't respond. 
In logs I see that the second device is appearing as offline.
 If I try to remove the first and only add the USB one (dps = 2) it's not working anyway. What could I try?

Thank you for your awesome work!

**Comment by codetheweb** [comment]
I would try playing around with the main dependency of this plugin, [TuyAPI](https://github.com/codetheweb/tuyapi).  Try calling `device.get({schema: true})` to get the complete property list and go from there.

**Comment by palla89** [comment]
I'll try it tonight or tomorrow and let you know, thank you very much for the answer!!

**Comment by codetheweb** [comment]
No problem, let me know if it works out.

**Comment by palla89** [comment]
it worked!! Just for reference, I thought the second toggle could be the number 2, it's instead the number 7.
Besides that, I know your plugin is deprecated but it's the only one that can work with newest firmware! Thank you again!

**Comment by palla89** [comment]
Sorry if I reopen it, I just noticed a problem and can't figure out what it could be:
If I insert both dps of the same device in the config.json in this way:

```
"platform": "TuyaPlatform",
            "name": "TuyaPlatform",
            "devices": [
                {
                    "name": "Outlet 1 - Presa",
                    "manufacturer": "KooGeek",
                    "model": "KLSP2 Plug",
                    "ip:": "192.168.2.243",
                    "id": "xxxx",
                    "key": "xxxx",
                    "version": "3.3",
                    "options": {
                        "dps": 7
                    }
                },
                {
                    "name": "Outlet 1 - USB",
                    "manufacturer": "KooGeek",
                    "model": "KLSP2 Plug",
                    "ip:": "192.168.2.243",
                    "id": "xxxx",
                    "key": "xxxx",
                    "version": "3.3",
                    "options": {
                        "dps": 1
                    }
                }
                
            ]
```

Home app only shows me the first of the two outlets. this is the log:

<img width="1069" alt="log" src="https://user-images.githubusercontent.com/12301205/61171805-cddf4500-a57c-11e9-85d0-6dcdbd8cdcb8.png">
The device is the same so the ip, key and localkey are the same, what could I try? If you have any direction to give me, I can try to fix it and open a PR!

**Comment by codetheweb** [comment]
It looks right to me, although the `manufacturer` and `model` properties don't affect anything.

I'd try nuking the `accessories/` and `persist/` directories in your `.homebridge` location to clear any cached data and see if that fixes things.

**Comment by palla89** [comment]
I tried right now but unfortunately it doesn't fix the problem, it seems that after the plugin finds the first occurrence, the other instance of the same device is busy or can't be found :(

**Comment by codetheweb** [comment]
Any ideas @basdelfos?

**Comment by basdelfos** [comment]
I would have to look into this. I suspect it has to do something with discovering devices. I noticed that when the discovery is looping through the devices that are configured, discovering the first device will result in UDP messages from all devices, discovering the last device will result in only one UDP message from the last device that isn't connected. It looks like that devices that are already connected, don't answer the discovery request. That could declare why the second time the same device is not discovered, because it doesn't respond with an UDP message.

But that is just right out of my mind without any evidence, I have to dig into the code and try to virtually replicate this.

**Comment by basdelfos** [comment]
@palla89 Is this the actual device you are using? 

https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjR-7GT07bjAhWKM-wKHSZRCPIQjRx6BAgBEAU&url=https%3A%2F%2Fwww.ebay.com%2Fitm%2FKoogeek-Smart-Plug-Wi-Fi-Enabled-Wireless-for-Amazon-Alexa-Google-Home-Q1H7-%2F254201871398&psig=AOvVaw1sg_6C42XEAGcd2nih7707&ust=1563270634382971

**Comment by palla89** [comment]
Hi @basdelfos, thank you for your answer! Yes the device is that one, here the exact amazon link I used: https://www.amazon.it/gp/product/B07QNT8X61/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1 

Regarding the problem, that's something similar to what I thought too. 
Another issue, that confirms to me that it could be a discovery problem, is that if I unplug the device, my entire homebridge setup stops responding, but I couldn't check the logs in that moment so I can't say something more accurate. I will try again and report!

**Comment by basdelfos** [comment]
> Another issue, that confirms to me that it could be a discovery problem, is that if I unplug the device, my entire homebridge setup stops responding, but I couldn't check the logs in that moment so I can't say something more accurate. I will try again and report!

I just noticed a similar issue. My devices didn't respond anymore, resulting in HomeKit reporting an error. It turned out that one of the devices wasn't reachable anymore, resulting in Homebridge not reporting back to HomeKit. Will need to investigate this also and make it more robust and reconnect when a connection with one of the devices has been broken.

**Comment by palla89** [comment]
Thank you very much! If you need something, I can try to help! Especially on the weekend 😄

**Comment by iRayanKhan** [comment]
Closing; inactive thread. If you need support please re-open this issue.
