### ISSUE TITLE
Device Request: Add Reverse Cycle Air Conditioner

### ISSUE THREAD

**Issue by TheHomekitWayFinder** [iRayanKhan/homebridge-tuya#56]
Can you add support for Tuya Air conditioners with options for heating, cooling, dry and fan. Such as this Kogan one: https://www.kogan.com/au/buy/kogan-smarterhome-41kw-portable-air-conditioner-14000-btu-reverse-cycle/

**Comment by TheHomekitWayFinder** [comment]
#

**Comment by codetheweb** [comment]
I'm not actively developing this plugin, but feel free to create a PR that adds support for this.

**Comment by iRayanKhan** [comment]
Closing; inactive thread. If you need support please re-open this issue.
