### ISSUE TITLE
RGBW Bulb control

### ISSUE THREAD

**Issue by garygoodger** [iRayanKhan/homebridge-tuya#57]
Hello,

Has RGBW control been added to this plugin yet? If so, is there any documentation on it? Your plugin is far more stable than others, however without RGBW controls it makes it impossible for me to use as all of my bulbs are RGBW.

Thanks in advance!

**Comment by codetheweb** [comment]
I'm not actively developing this plugin, but if you test out https://github.com/codetheweb/homebridge-tuya/pull/30 and it works I can merge it in.

**Comment by iRayanKhan** [comment]
Closing; inactive thread. If you need support please re-open this issue.
