### ISSUE TITLE
RC2

### ISSUE THREAD

**Issue by Lestercity** [iRayanKhan/homebridge-tuya#64]
Hi Rayan. Will the RC2 be available in this new repo with support for the Blinds? And should we do a fresh install or will it be available by update? I opened new issue because the issue in the old repo is archived and I cant comment anymore in that issue. Thx again.

**Comment by iRayanKhan** [comment]
1) Yes Rc2 will be pushed today, this was an unexpected change so sorry for the delay.

2) Currently this plugin uses the same config format as the last one, which I have to change. All you would have to do is install the last plugin, install this one, and rename the platform name to just "Tuya" not "Tuya-platform" I will let you know when that is pushed.

**Comment by iRayanKhan** [comment]
Closing; use #66 to discuss about blinds as that thread is more active now.

**Comment by Lestercity** [comment]
Just installed your new version 1.0.0 that was released 6 hrs ago. Should I change something in the config? 

Mvg Lester

woensdag 8 april 2020 02:00 +0200 van notifications@github.com  <notifications@github.com>:
