### ISSUE TITLE
Unable to get device ID

### ISSUE THREAD

**Issue by dewoert** [iRayanKhan/homebridge-tuya#67]
I'm trying to get the IDs form a GarageDoor opener.
The device is working nicely in TuyaSmart App.
Followed the instructions from [https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions) to setup my iPhone (IOS 13.4)
Profile installed, certificate trusted.
Command on (Raspberry) : `sudo tuya-lan-find --port 8081 --schema`
Add proxy settings to WiFi on iPhone.
When starting the TuyaSmart App, i get "Network errror, try again"
Clicking "Ok" several times gets me into the app. 
But no info in the console on Raspberry
I can controle the GarageDoor opener without problems, even with proxy active. 
Any idea how to get this working so i can get the IDs to add in HomeBridge config ?

Also tried the uComen App, but that app doesn't support a GarageDoor Opener.

**Comment by iRayanKhan** [comment]
So the TuyaSmart and other Tuya apps sadly broke/patched the method used to get the ID/Keys. The only working app is uComen Home, and sadly it doesn't support garage openers. I am looking for another way to get these keys. If someone uploads an older version of the Tuya app, that could be a great start.

**Comment by codetheweb** [comment]
It's not as streamlined as the old method, but I've updated the setup instructions for TuyAPI users: https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md.

**Comment by dewoert** [comment]
> It's not as streamlined as the old method, but I've updated the setup instructions for TuyAPI users: https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md.

I think i have setup everything, when starting the tuya-cli-link command, it is trying to discover devices, but no luck:
`✖ Device(s) failed to be registered!
Error: Timed out waiting for devices to connect.
`
Also tried other device (LED strip), but also no response

**Comment by dewoert** [comment]
**Problem solved.**
Created another RPi with only basic apps
Made sure 5G WiFi is turned off at my router.
Created another (new) config in Tuya Dev.
After that, both devices showed me the ID and localKey.
Devices (Garage Door Openren, en LED Strip) working nicely now with HomeBridge

**Comment by codetheweb** [comment]
👍
