### ISSUE TITLE
2 band switch

### ISSUE THREAD

**Issue by stalkerj** [iRayanKhan/homebridge-tuya#69]
Hi. I got this 2 band switch.
https://aliexpress.ru/item/4000289352430.html?spm=a2g0s.9042311.0.0.36fe33edZOcMxs
I added only like smart outlet, but it works slow. About 1-2 seconds waiting time.
Is it possible to add it another way?

**Comment by iRayanKhan** [comment]
Can you please paste your config and schema please? Please blur ID's and Key's.

**Comment by stalkerj** [comment]
{
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "My Power Strip",
                    "type": "CustomMultiOutlet",
                    "manufacturer": "GeekBee",
                    "model": "Smart Wifi Power Strip",
                    "id": "xxxxxxxxxxxx",
                    "key": "xxxxxxxxxxx",
                    "outlets": [
                        {
                            "name": "Outlet 1",
                            "dp": 1
                        },
                        {
                            "name": "Outlet 2",
                            "dp": 2
                        }
                    ]
                }
            ]
        }
_________________________
Also tried config from MultiOutlet. The same slow working. Slow only from Homekit, but when I turn on  the phisical button it appears at the same moment at the Homekit.

Here is scheme

[
  {
    name: 'Туалет',
    id: 'xxxxxxxxxxxx',
    key: 'xxxxxxxxxxxxx',
    def: {
      schema: '[{"mode":"rw","code":"switch_1","name":"\\u5f00\\u51731","property":{"type":"bool"},"iconname":"icon-dp_power2","id":1,"type":"obj","desc":""},{"mode":"rw","code":"switch_2","name":"\\u5f00\\u51732","property":{"type":"bool"},"iconname":"icon-dp_power2","id":2,"type":"obj","desc":""},{"mode":"rw","code":"countdown_1","name":"\\u5f00\\u51731\\u5012\\u8ba1\\u65f6","property":{"unit":"s","min":0,"max":86400,"scale":0,"step":1,"type":"value"},"iconname":"icon-dp_time2","id":9,"type":"obj","desc":""},{"mode":"rw","code":"countdown_2","name":"\\u5f00\\u51732\\u5012\\u8ba1\\u65f6","property":{"unit":"s","min":0,"max":86400,"scale":0,"step":1,"type":"value"},"iconname":"icon-dp_time2","id":10,"type":"obj","desc":""}]',
      extras: '[{"id":1,"inputStyle":"","inputType":"plain"},{"id":2,"inputStyle":"","inputType":"plain"},{"id":9,"inputStyle":"","inputType":" "},{"id":10,"inputStyle":"","inputType":" "}]',
    },
  },
]

**Comment by tjonaitis** [comment]
Hi,

I have these 2-gang switches: https://www.aliexpress.com/item/32975580253.html?spm=2114.12010612.8148356.12.49825a48m1aRUZ and I can confirm that there is quite a big lag, around 2 seconds... I also use this plugin with dimmer switches and they don’t have such issue, lights turn on instantly.

**Comment by stalkerj** [comment]
Plugin tuya web has no such lag

**Comment by iRayanKhan** [comment]
I think it's the polling time which depending if you can change it or not is that reason why. Which other plugin are you using?

**Comment by stalkerj** [comment]
> I think it's the polling time which depending if you can change it or not is that reason why. Which other plugin are you using?

https://www.npmjs.com/package/homebridge-tuya-web

**Comment by iRayanKhan** [comment]
Hi there.
Me and the dev have started talks a while ago regarding the future of both plugins. Currently I can't think of a fix of why there would be a delay with local control, but not with server control. If you don't mind using the web plugin since it seems to work that would be the best option currently since I can't debug why there would be a delay.
