### ISSUE TITLE
Garage Door Opener Opening and Closing state

### ISSUE THREAD

**Issue by dewoert** [iRayanKhan/homebridge-tuya#70]
Hello,
My GarageDoor Opener is working, but not reporting the state correctly.
The opener uses a sensor to detect if the Garage Door is closed.
When i open de Garage Door, this sensor reports (correctly) its state as closed, so from HomeK i get 2 message: "Garage Door OPEN" and directly Garage "Door CLOSED";
Is it possible to build in a timeout for that ?
Also i'm not seeing the "Opening" and "Closing" status ?
Would be nice to have a configurable setting (parameter) to give an indication about how long it takes to close or open the garage door. 

Opening log info:
[TuyaAccessory] Sending Goldwing Garage {"1":true}
[TuyaAccessory] Heard back from Goldwing Garage with command 8
[TuyaAccessory] GarageDoor changed: {"1":true,"7":0,"101":false}
[TuyaAccessory] Heard back from Goldwing Garage with command 8
[TuyaAccessory] GarageDoor changed: {"1":true,"7":0,"101":true}

Closing log info:
[TuyaAccessory] Sending Goldwing Garage {"1":false}
[TuyaAccessory] Heard back from Goldwing Garage with command 8
[TuyaAccessory] GarageDoor changed: {"1":false,"7":0,"101":true}
[TuyaAccessory] Heard back from Goldwing Garage with command 8
[TuyaAccessory] GarageDoor changed: {"1":true,"7":0,"101":true}
.
.
.
[TuyaAccessory] Heard back from Goldwing Garage with command 8
[TuyaAccessory] GarageDoor changed: {"1":true,"7":0,"101":false}
[TuyaAccessory] Heard back from Goldwing Garage with command 8
[TuyaAccessory] GarageDoor changed: {"1":false,"7":0,"101":false}

**Comment by iRayanKhan** [comment]
I'm confused by what you mean with
> Is it possible to build in a timeout for that ?

Also in terms of being able to configure it the garage door is able to show opening/closing and how long it takes to close it, it depends if the accessory supports it. 

Could I get the schema of the device?

**Comment by dewoert** [comment]
With the timeout i mean:
When i press on "Open GarageDoor", it should report a status "Opening"..
After the "Timeout" is should report "Opened". 
That value depends on the type garagedoor, and therfore a configurabel value would be nice.

How do i get the Schema info from the device ?
(Can only get the ID's trough the "new" methode)

**Comment by iRayanKhan** [comment]
Can you link the new method you used please?

**Comment by dewoert** [comment]
[https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md)
I created an account at https://iot.tuya.com/ and used the info from that account to get the device active.
`tuya-cli link --api-key <myApiKey> --api-secret <myApiSecret> --schema <mySchemName> --ssid <mySSID> --password <myPassword> --region eu`
Result:
`[
  {
    id: <ID of device>,
    ip: <myHomeIP>,
    localKey: '<myKey>',
    name: '车库门控制器'
  }
]`

**Comment by apollo316** [comment]
@iRayanKhan I'm also experiencing this issue. Tuya garage door opener reports **Ready to handle Garage Door (GarageDoor:3.3) with signature {"1":true,"7":0,"101":false,"102":11,"103":0}** where 101:false is the door state. 

I've set dpstatus: 101 in the config.json but it's not getting the door state. If I open the door manually it reports in the Homebridge log that the 101 state changed to true but Homekit shows the door closed still. 

Also to note, the 102 status is the timer set in the Tuya app for how long the garage door takes to open. This is not read by the homebridge tuya plugin either. When I open the garage door in Homekit it instantly says opened, instead of reading that 11 second timer to say "opening..." and then read the door state to see it is "Opened".

**Comment by apollo316** [comment]
@iRayanKhan I think I see the issue. When 1=true but 101=false it's incorrectly reading the dpAction as the state. When 1=true and 101=true it sees the door is open. If I close the door manually outside of homekit 101 changes to false (closed) but dpAction still reads as true. dpAction needs to be ignored, and the dpStatus used as the actual door state. If dpStatus is used as the door state and showed true, Homekit should say the door is open and then send dpAction as false, even if dpAction is already being read as false, so it sends the correct command.

**Comment by apollo316** [comment]
For clarity:
1. dpAction says true and dpStatus says true Homekit = shows the door open and it closes when I use homekit to close it.
2. dpAction says false and dpStatus says true Homekit = shows the door closed and does not respond when I use homekit to close it. (Should say open and should send dpAction false when I close the door in homekit)
3. dpAction says false and dpStatus says false = shows the door closed and opens when I use homekit to open it.
4. dpAction says true and dpStatus says false = shows the door opened and does not respond when I use homekit to open it. (Should say closed and should send dpAction true when I open the door in homekit)

dpStatus should be used for the door state and should override whatever dpAction says when an open/closed command is sent. dpAction should only be used to send the right  true/false command.

**Comment by apollo316** [comment]
If I change dpAction in the config.json it reads the correct door state regardless of how I open or close the door (manually, homekit, tuya app) but no longer can send the correct command to open or close the door.

**Comment by apollo316** [comment]
@iRayanKhan @dewoert 

I've tinkered with the GarageDoorAccessory.js based on my previous theory and have the garage door working perfectly with everything but one thing. The door now reads the state correctly, opens and closes as it should, everything. But, if I open the garage door manually Homekit says Opening or Closing indefinitely. When I tap the garage door while it says Opening or Closing it immediately refreshes to the correct state of the door, and then works again through homekit as it should. I can't figure out how to fix this.

GarageDoorAccessory.js:
`const BaseAccessory = require('./BaseAccessory');

class GarageDoorAccessory extends BaseAccessory {
    static getCategory(Categories) {
        return Categories.GARAGE_DOOR_OPENER;
    }

    constructor(...props) {
        super(...props);
    }

    _registerPlatformAccessory() {
        const {Service} = this.hap;

        this.accessory.addService(Service.GarageDoorOpener, this.device.context.name);

        super._registerPlatformAccessory();
    }

    _registerCharacteristics(dps) {
        const {Service, Characteristic} = this.hap;
        const service = this.accessory.getService(Service.GarageDoorOpener);
        this._checkServiceName(service, this.device.context.name);

        this.dpAction = this._getCustomDP(this.device.context.dpAction) || '1';
        this.dpStatus = this._getCustomDP(this.device.context.dpStatus) || '2';

        this.currentOpen = Characteristic.CurrentDoorState.OPEN;
        this.currentOpening = Characteristic.CurrentDoorState.OPENING;
        this.currentClosing = Characteristic.CurrentDoorState.CLOSING;
        this.currentClosed = Characteristic.CurrentDoorState.CLOSED;
        this.targetOpen = Characteristic.TargetDoorState.OPEN;
        this.targetClosed = Characteristic.TargetDoorState.CLOSED;
        if (!!this.device.context.flipState) {
            this.currentOpen = Characteristic.CurrentDoorState.CLOSED;
            this.currentOpening = Characteristic.CurrentDoorState.CLOSING;
            this.currentClosing = Characteristic.CurrentDoorState.OPENING;
            this.currentClosed = Characteristic.CurrentDoorState.OPEN;
            this.targetOpen = Characteristic.TargetDoorState.CLOSED;
            this.targetClosed = Characteristic.TargetDoorState.OPEN;
        }

        const characteristicTargetDoorState = service.getCharacteristic(Characteristic.TargetDoorState)
            .updateValue(this._getTargetDoorState(dps[this.dpStatus]))
            .on('get', this.getTargetDoorState.bind(this))
            .on('set', this.setTargetDoorState.bind(this));

        const characteristicCurrentDoorState = service.getCharacteristic(Characteristic.CurrentDoorState)
            .updateValue(this._getCurrentDoorState(dps[this.dpStatus]))
            .on('get', this.getCurrentDoorState.bind(this));

        this.device.on('change', (changes, state) => {
            console.log('[TuyaAccessory] GarageDoor changed: ' + JSON.stringify(state));

            if (changes.hasOwnProperty(this.dpStatus)) {
                const newCurrentDoorState = this._getCurrentDoorState(state);
                if (characteristicCurrentDoorState.value !== newCurrentDoorState) characteristicCurrentDoorState.updateValue(newCurrentDoorState);
            }
        });
    }

    getTargetDoorState(callback) {
        this.getState(this.dpStatus, (err, dp) => {
            if (err) return callback(err);

            callback(null, this._getTargetDoorState(dp));
        });
    }

    _getTargetDoorState(dp) {
        return dp ? this.targetOpen : this.targetClosed;
    }

    setTargetDoorState(value, callback) {
        this.setState(this.dpAction, value === this.targetOpen, callback);
    }

    getCurrentDoorState(callback) {
        this.getState([ this.dpStatus], (err, dps) => {
            if (err) return callback(err);

            callback(null, this._getCurrentDoorState(dps));
        });
    }

    _getCurrentDoorState(dps) {
        // ToDo: Check other `dps` for opening and closing states
        return dps[this.dpStatus] ? this.currentOpen : this.currentClosed;
    }
}

module.exports = GarageDoorAccessory;
`

**Comment by iRayanKhan** [comment]
Please try V1.4.0.

**Comment by apollo316** [comment]
Tried 1.4.0 and it seems stuck at sending the open/close command but it is reading the state correctly. I tried tinkering with the new GarageDoorAccessory.js but I can't seem to get it working. It keeps saying Unknown_State and Unknown_Status
**[2/15/2021, 10:39:20 AM] [TuyaLan] Ready to handle Garage Door (GarageDoor:3.3) with signature {"1":true,"7":0,"101":false,"102":11,"103":0}
[TuyaAccessory] Kogan GarageDoor _getTargetDoorState UNKNOWN STATE true
[TuyaAccessory] Kogan GarageDoor _getCurrentDoorState UNKNOWN STATUS false**
and
**[TuyaAccessory] GarageDoor changed: {"1":false,"7":0,"101":false,"102":11,"103":600}**

What I do know is that on 1.3.0 with this GarageDoorAccessory.js everything works as it should:
`

const BaseAccessory = require('./BaseAccessory');



class GarageDoorAccessory extends BaseAccessory {

    static getCategory(Categories) {

        return Categories.GARAGE_DOOR_OPENER;

    }



    constructor(...props) {

        super(...props);

    }



    _registerPlatformAccessory() {

        const {Service} = this.hap;



        this.accessory.addService(Service.GarageDoorOpener, this.device.context.name);



        super._registerPlatformAccessory();

    }



    _registerCharacteristics(dps) {

        const {Service, Characteristic} = this.hap;

        const service = this.accessory.getService(Service.GarageDoorOpener);

        this._checkServiceName(service, this.device.context.name);



        this.dpAction = this._getCustomDP(this.device.context.dpAction) || '1';

        this.dpStatus = this._getCustomDP(this.device.context.dpStatus) || '2';



        this.currentOpen = Characteristic.CurrentDoorState.OPEN;

        this.currentOpening = Characteristic.CurrentDoorState.OPENING;

        this.currentClosing = Characteristic.CurrentDoorState.CLOSING;

        this.currentClosed = Characteristic.CurrentDoorState.CLOSED;

        this.targetOpen = Characteristic.TargetDoorState.OPEN;

        this.targetClosed = Characteristic.TargetDoorState.CLOSED;

        if (!!this.device.context.flipState) {

            this.currentOpen = Characteristic.CurrentDoorState.CLOSED;

            this.currentOpening = Characteristic.CurrentDoorState.CLOSING;

            this.currentClosing = Characteristic.CurrentDoorState.OPENING;

            this.currentClosed = Characteristic.CurrentDoorState.OPEN;

            this.targetOpen = Characteristic.TargetDoorState.CLOSED;

            this.targetClosed = Characteristic.TargetDoorState.OPEN;

        }



        const characteristicTargetDoorState = service.getCharacteristic(Characteristic.TargetDoorState)

            .updateValue(this._getTargetDoorState(dps[this.dpAction]))

            .on('get', this.getTargetDoorState.bind(this))

            .on('set', this.setTargetDoorState.bind(this));



        const characteristicCurrentDoorState = service.getCharacteristic(Characteristic.CurrentDoorState)

            .updateValue(this._getCurrentDoorState(dps[this.dpStatus]))

            .on('get', this.getCurrentDoorState.bind(this));



        this.device.on('change', (changes, state) => {

            console.log('[TuyaAccessory] GarageDoor changed: ' + JSON.stringify(state));



            if (changes.hasOwnProperty(this.dpStatus)) {

                const newCurrentDoorState = this._getCurrentDoorState(state);

                if (characteristicCurrentDoorState.value !== newCurrentDoorState) characteristicCurrentDoorState.updateValue(newCurrentDoorState);

            }

        });

    }



    getTargetDoorState(callback) {

        this.getState(this.dpStatus, (err, dp) => {

            if (err) return callback(err);



            callback(null, this._getTargetDoorState(dp));

        });

    }



    _getTargetDoorState(dp) {

        return dp ? this.targetOpen : this.targetClosed;

    }



    setTargetDoorState(value, callback) {

        this.setState(this.dpAction, value === this.targetOpen, callback);

    }



    getCurrentDoorState(callback) {

        this.getState([this.dpStatus, this.dpStatus], (err, dps) => {

            if (err) return callback(err);



            callback(null, this._getCurrentDoorState(dps));

        });

    }



    _getCurrentDoorState(dps) {

        // ToDo: Check other `dps` for opening and closing states

        return dps[this.dpStatus] ? this.currentOpen : this.currentClosed;

    }

}



module.exports = GarageDoorAccessory;

`

**Comment by myevit** [comment]
v.1.4 confirming "dpAction": 1 is triggering door action but "dpStatus": 101 no longer returning door status, also state become flipped

```
[2/19/2021, 11:47:52 AM] [TuyaLan] Discovered Garage Door (xxxxxxx) identified as GarageDoor (3.3)
[TuyaAccessory] Changing ping gap for Garage Door to 9s
[TuyaAccessory DEBUG] reconnect called for Garage Door
[TuyaAccessory] Discovery ended.
[2/19/2021, 11:47:52 AM] [TuyaLan] Connected to Garage Door
[TuyaAccessory] Sending first query to Garage Door (3.3)
[TuyaAccessory] Heard back from Garage Door with command 10
[2/19/2021, 11:47:52 AM] [TuyaLan] Ready to handle Garage Door (GarageDoor:3.3) with signature {"1":true,"7":0,"101":true,"102":false}
[TuyaAccessory DEBUG] decrementing this._connectionAttempts, currently 2
[TuyaAccessory DEBUG] decrementing this._connectionAttempts, currently 1
[TuyaAccessory] Sending Garage Door {"1":false}
[TuyaAccessory] Heard back from Garage Door with command 8
[TuyaAccessory] eWeLink GarageDoor changed:{"1":false}
[TuyaAccessory] Sending Garage Door {"1":true}
[TuyaAccessory] Heard back from Garage Door with command 8
[TuyaAccessory] eWeLink GarageDoor changed:{"1":true}
```
old config that used to work

```
                   "name": "Garage Door",
                    "type": "GarageDoor",
                    "manufacturer": "eWeLink",
                    "model": "WiFi Switch Garage Door Controller",
                    "id": "xxxxxx",
                    "key": "xxxxxxx",
                    "dpAction": 1,
                    "dpStatus": 101,
                    "pingTimeout": 2147483,
                    "connectTimeout": 2147483

```

**Comment by ElphaX** [comment]
Still an issue? Please re-open if relevant.
