### ISSUE TITLE
Devices keep disconnecting (Error: ERR_CONNECTION_TIMED_OUT)

### ISSUE THREAD

**Issue by uddinr** [iRayanKhan/homebridge-tuya#71]
Hi,

I have been using this package for Teckin single outlet sockets, I have around 12 sockets and for some of the sockets I keep getting the following error:

[TuyaAccessory] Socket had a problem and will reconnect to DeviceName (Error: ERR_CONNECTION_TIMED_OUT)

on occasions i get the following console logs:

[TuyaAccessory] Sending first query to DeviceName (3.3)
[TuyaAccessory] DeviceName (3.3) didn't respond with its current state.

I have given static ip addresses to all devices.

ALL devices work fine using the Ucomen Home App and respond instantly.

Is there anything i can do to troubleshoot this?

Also, i disabled the console log for TuyaDiscovery as i had a log file reaching 34GB! 

Any help or advice would be greatly appreciated.

**Comment by iRayanKhan** [comment]
Jesus 34GB? Will definitely need to fix that. 

Could I get your config and device's schemas?

**Comment by uddinr** [comment]
so the issue with logs was due to the following console logs:

[TuyaDiscovery] UDP from 192.168.1.201:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.1.201:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.1.203:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.1.203:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.1.204:6667 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 192.168.1.204:6667 0x000055aa...0x0000aa55
.....

i have overcome the large log file being generated by restricting the log file size using the following:

[https://serverfault.com/questions/900499/how-do-i-limit-launchd-log-size-on-os-x](https://serverfault.com/questions/900499/how-do-i-limit-launchd-log-size-on-os-x)

here is my schema:


> {
    "bridge": {
        "name": "xxxx",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 51826,
        "pin": "xxx-xx-xxx"
    },
    "description": "",
    "accessories": [
        {
            "accessory": "sky-q-experimental",
            "name": "Sky",
            "ipaddress": "192.168.1.49"
        }
    ],
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8581
        },
        {
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "Socket1",
                    "type": "Outlet",
                    "manufacturer": "Teckin",
                    "model": "Smart Socket SP23",
                    "id": "xxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxx",
                    "ip": "192.168.1.211"
                },
                {
                    "name": "Socket2",
                    "type": "Outlet",
                    "manufacturer": "Teckin",
                    "model": "Smart Socket SP23",
                    "id": "xxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxx",
                    "ip": "192.168.1.212"
                },
                {
                    "name": "Socket3",
                    "type": "Outlet",
                    "manufacturer": "Teckin",
                    "model": "Smart Socket SP23",
                    "id": "xxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxx",
                    "ip": "192.168.1.209"
                },
                {
                    "name": "Socket4",
                    "type": "Outlet",
                    "manufacturer": "Teckin",
                    "model": "Smart Socket SP23",
                    "id": "xxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxx",
                    "ip": "192.168.1.208"
                },
                {
                    "name": "Socket5",
                    "type": "Outlet",
                    "manufacturer": "Teckin",
                    "model": "Smart Socket SP23",
                    "id": "xxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxx",
                    "ip": "192.168.1.207"
                },
                {
                    "name": "Socket6",
                    "type": "Outlet",
                    "manufacturer": "Teckin",
                    "model": "Smart Socket SP23",
                    "id": "xxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxx",
                    "ip": "192.168.1.206"
                },
                {
                    "name": "Socket7",
                    "type": "Outlet",
                    "manufacturer": "Teckin",
                    "model": "Smart Socket SP23",
                    "id": "xxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxx",
                    "ip": "192.168.1.205"
                },
                {
                    "name": "Socket8",
                    "type": "Outlet",
                    "manufacturer": "Teckin",
                    "model": "Smart Socket SP23",
                    "id": "xxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxx",
                    "ip": "192.168.1.204"
                },
                {
                    "name": "Socket9",
                    "type": "Outlet",
                    "manufacturer": "Teckin",
                    "model": "Smart Socket SP23",
                    "id": "xxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxx",
                    "ip": "192.168.1.203"
                },
                {
                    "name": "Socket10",
                    "type": "Outlet",
                    "manufacturer": "Teckin",
                    "model": "Smart Socket SP23",
                    "id": "xxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxx",
                    "ip": "192.168.1.201"
                },
                {
                    "name": "Socket11",
                    "type": "Outlet",
                    "manufacturer": "Teckin",
                    "model": "Smart Socket SP23",
                    "id": "xxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxx",
                    "ip": "192.168.1.202"
                },
                {
                    "name": "Socket12",
                    "type": "Outlet",
                    "manufacturer": "Teckin",
                    "model": "Smart Socket SP23",
                    "id": "xxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxx",
                    "ip": "192.168.1.210"
                }
            ]
        },
        {
            "platform": "BraviaPlatform",
            "tvs": [
                {
                    "name": "TV",
                    "ip": "192.168.1.29",
                    "soundoutput": "speaker",
                    "applications": false,
                    "sources": [
                        "extInput:hdmi",
                        "extInput:widi"
                    ]
                }
            ]
        },
        {
            "platform": "Ring",
            "refreshToken": "xxxx"
        }
    ]
}

4 of the sockets have firmware 1.0.0 and the rest have 1.0.3
i have updated to your latest release

i have noticed in the logs i get a lot of ECONNRESET logs

please let me know if you need anything else

**Comment by iRayanKhan** [comment]
So that is your config, the schema is the device info like brightness, commands, on/off codes, etc.

**Comment by iRayanKhan** [comment]
Closing: Fixed in V1.4.0.
