### ISSUE TITLE
Novostella Brand Lights...Could not find

### ISSUE THREAD

**Issue by jmo2610** [iRayanKhan/homebridge-tuya#72]
Hi there.  Thanks for keeping this plugin up and running.  I recently installed, and everything seems to be working fine, except that I have three Novostella bulbs that are not found by the plugin.  They are RGBCW lights, instead of RGBTW.  I'm not sure if that has anything to do with it.  They work fine in the Smart Life app, as well as Ucomen.  And I have Ohlux brand bulbs that work just fine with your plugin.

Are these Novostellas just somehow not compatible?

**Comment by iRayanKhan** [comment]
Hello,
What are the devices schemas? I have never heard of a C type of light?

**Comment by jmo2610** [comment]
This is the box they came in.  I don't really know more info about them, except that they're a wifi light and they work in Smart Life (and all the other similar apps) in the exact same way that other wifi bulbs work.
https://bit.ly/3ebPPDG
https://bit.ly/2Rq7qyh

**Comment by iRayanKhan** [comment]
Are you able to extract the schema by chance?

**Comment by jmo2610** [comment]
I actually just went ahead and sold the lights on eBay.  I didn't much care for the Smart Life app experience with the lights, and it was clearly becoming a lot of effort to get them integrated with Homekit.  Thanks for getting back to me, though.

**Comment by iRayanKhan** [comment]
Sorry for not being able to help. I have found the way to integrate Tuya based lights is using the Tuya-Web plugin. 

If I knew Tuya devices would be this complicated, I wouldn't have gotten them either lol
