### ISSUE TITLE
Smart Blinds Tuya

### ISSUE THREAD

**Issue by philmue1988** [iRayanKhan/homebridge-tuya#74]
Hi guys,

first of all thanks for working on that plugin!
I tried to install it on HB and have all required info(ID,Key). Now HB is starting and i get the message :

Apr 13 10:58:21 raspberrypi homebridge[25747]: [TuyaDiscovery] UDP from 192.168.2.146:6667 0x000055aa...0x0000aa55
Apr 13 10:58:21 raspberrypi homebridge[25747]: [4/13/2020, 10:58:21] [TuyaLan] Discovered My Simple Blinds (bf632fa48ff1a7a14ehhls) identified as SimpleBlinds (3.3)
Apr 13 10:58:21 raspberrypi homebridge[25747]: [TuyaAccessory] Changing ping gap for My Simple Blinds to 9s
Apr 13 10:58:21 raspberrypi homebridge[25747]: [4/13/2020, 10:58:21] [TuyaLan] Connected to My Simple Blinds
Apr 13 10:58:21 raspberrypi homebridge[25747]: [TuyaAccessory] Sending first query to My Simple Blinds (3.3)
Apr 13 10:58:21 raspberrypi homebridge[25747]: [TuyaAccessory] My Simple Blinds (3.3) didn't respond with its current state.
Apr 13 10:58:21 raspberrypi homebridge[25747]: [4/13/2020, 10:58:21] [TuyaLan] Ready to handle My Simple Blinds (SimpleBlinds:3.3) with signature {}

the blinds are showing in HB but nothing happened when i try to controll them.

Is there an idee of the Problem?

**Comment by iRayanKhan** [comment]
Hi there, please refer to issue #66 as I am adding a fix.

**Comment by iksheth** [comment]
is it fixed ?
