### ISSUE TITLE
SmartBlinds variation

### ISSUE THREAD

**Issue by NamelessPharaoh** [iRayanKhan/homebridge-tuya#75]
hello i had created this variation on https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/89

with some blinds the constants sent by the controls are not '1', '2'
they need to be replaced by
'1' = 'on'
'2' = 'off'
 you can add this as a variation

**Comment by iRayanKhan** [comment]
Thanks for this, will add this. Moving all smart blind discussion to #66.
