### ISSUE TITLE
Brightness level goes to 0% when Home App is opened.

### ISSUE THREAD

**Issue by Zaphor88** [iRayanKhan/homebridge-tuya#76]
is the issue still being worked on?

https://github.com/iRayanKhan/homebridge-tuya-platform/issues/8

**Comment by iRayanKhan** [comment]
Hi, sorry for the delayed responses. 
So the schema is details about the device like brightness, codes, commands, etc. I can provide instructions later tonight.

**Comment by Zaphor88** [comment]
Yes a guide would be great.  I don't know where I would get the information from.

**Comment by Zaphor88** [comment]
hello with the homebride update 1.0.0 the function of the lamp has changed.  the% display was completely gone.  I then tested the setting again.  in the end the adjustment of "dpBrightness": 3 solved the problem.
