### ISSUE TITLE
uComen app and Tuya Lan Find

### ISSUE THREAD

**Issue by Faisalthe01** [iRayanKhan/homebridge-tuya#80]
did uComen app blocked the Id & keys too?
I get cant past "Intercepted certificate request"

no id or key when I launch the uComen app.

**Comment by crampus** [comment]
It's entirely possible. ucomen has been updated in the last 2 weeks.

The tuya-lan-find mechanism seems to now be outdated.

I have heard some older versions of Android stored keys unencrypted in XML files that can be extracted if the device is rooted - it might be that from now on the only way to retrieve keys is to have a rooted Android handset/tablet.

**Comment by Faisalthe01** [comment]
I remember Tuya Lan Find was giving a error when unsupported Smart Life and Tuya app run but this time it’s giving nothing. Maybe something wrong with Tuya Lan Find

**Comment by chinloon** [comment]
When traffic is encrypted, Tuya-Lan-Find will not show anything.  Another other IOS app can pick up the ID and key?

**Comment by chinloon** [comment]
Was poking around the iphone backups like in this for roborock 
[https://github.com/Maxmudjon/com.xiaomi-miio/blob/master/docs/obtain_token.md#ios-users](https://github.com/Maxmudjon/com.xiaomi-miio/blob/master/docs/obtain_token.md#ios-users)
ut so far have  not been able to find the ID and keys...

**Comment by crampus** [comment]
#crosspost from semi-related issue #73

I managed to retrieve my key using Android.

While keys are next to impossible to retrieve from iOS, they’re easy enough on Android.

What you’ll need:
• An Android handset `note: BlueStacks for Windows/Mac gets hung up on setting a lockscreen passcode (as it doesn’t lock; so you can’t add in certificate trusts) - you will need a dedicated Android/AOSP x86/x64 distro in a VM, or native Android device.`
• Installation from external sources enabled
• [Packet Capture](https://www.apkmirror.com/apk/grey-shirts/packet-capture/packet-capture-1-7-2-release/) (1.7.2 tested) or later
• [Tuya Smart Life](https://www.apkmirror.com/apk/tuya-inc/smart-life-smart-living/smart-life-smart-living-3-6-1-release/) (3.6.1 tested) Some other versions or other branded versions released prior to December 2019 **might** work, but I make no guarantees or warrants of fitness for any given configuration, device, or sexual identity.

1. Set up Packet Capture
2. Filter to the Tuya app.
3. Start a capture
4. Trigger your IoT device
5. Stop the Capture
6. Decrypt the SSL packets
7. You will get a JSON payload with the local_key in plaintext.
8. Plug and play into your configs.
9. Magic.

**Comment by Faisalthe01** [comment]
> #crosspost from semi-related issue #73
> 
> I managed to retrieve my key using Android.
> 
> While keys are next to impossible to retrieve from iOS, they’re easy enough on Android.
> 
> What you’ll need:
> • An Android device `note: BlueStacks for Windows/Mac gets hung up on setting a lockscreen passcode (as it doesn’t lock; so you can’t add in certificate trusts) - you will need a dedicated Android/AOSP x86/x64 distro running bare metal or in a VM with a dedicated WLAN NIC, or native Android device.`
> • Installation from external sources enabled
> • [Packet Capture](https://www.apkmirror.com/apk/grey-shirts/packet-capture/packet-capture-1-7-2-release/) (1.7.2 tested) or later
> • [Tuya Smart Life](https://www.apkmirror.com/apk/tuya-inc/smart-life-smart-living/smart-life-smart-living-3-6-1-release/) (3.6.1 tested) Some other versions or other branded versions released prior to December 2019 **might** work, but I make no guarantees or warrants of fitness for any given configuration, device, or sexual identity.
> 
> 1. Set up Packet Capture
> 2. Filter to the Tuya app.
> 3. Start a capture
> 4. Trigger your IoT device
> 5. Stop the Capture
> 6. Decrypt the SSL packets
> 7. You will get a JSON payload with the local_key in plaintext.
> 8. Plug and play into your configs.
> 9. Magic.

Those steps looks a bit hard.

**Comment by kalety** [comment]
Use Cocoon Connect to get the id's, also Alexa compatible.

**Comment by mrmaximas** [comment]
> #crosspost from semi-related issue #73
> 
It's works. Thank You. Today i got key for Tuya RTL based Yandex Plug.

**Comment by dkossman** [comment]
The Grid Connect app also worked for me on iOS to capture ID and Key

**Comment by Faisalthe01** [comment]
Used Kogan Smart Home
