### ISSUE TITLE
Please add TUYA based Wi-Fi Valve / Leak Sensor / Door Sensor

### ISSUE THREAD

**Issue by mrmaximas** [iRayanKhan/homebridge-tuya#82]
![74769327-450b5300-529b-11ea-9678-401dbe1507ee](https://user-images.githubusercontent.com/61165387/81219782-f8592d80-8fe8-11ea-9fad-c56fc0928879.jpeg)
Below are the intercept results from Ucomen Home app.
{
name: 'Valve',
id: 'хххх',
key: 'хххх',
def: {
schema: '[{"mode":"rw","code":"switch_1","name":"\u5f00\u51731","property":{"type":"bool"},"iconname":"icon-dp_power2","id":1,"type":"obj","desc":""},{"mode":"rw","code":"countdown_1","name":"\u5f00\u51731\u5012\u8ba1\u65f6","property":{"unit":"s","min":0,"max":86400,"scale":0,"step":1,"type":"value"},"iconname":"icon-dp_time2","id":9,"type":"obj","desc":""}]',
extras: '[{"id":1,"inputStyle":"","inputType":"plain"},{"id":9,"inputStyle":"","inputType":"plain"}]',
},

{
name: 'Door Detector',
id: 'yyyyy',
key: 'yyyyy',
def: {
schema: '[{"mode":"ro","code":"doorcontact_state","name":"\u95e8\u78c1","property":{"type":"bool"},"iconname":"icon-zanting","id":1,"type":"obj","desc":"\u3010\u5fc5\u9009\u3011"},{"mode":"ro","code":"battery_state","name":"\u7535\u6c60\u7535\u91cf\u72b6\u6001","property":{"range":["low","middle","high"],"type":"enum"},"id":3,"type":"obj","desc":"\u3010\u975e\u5fc5\u9009\u3011"}]',
},

===
{
name: 'Water leak sensor',
id: 'zzzz',
key: 'zzzzz',
def: {
schema: '[{"mode":"ro","code":"watersensor_state","name":"\u6c34\u6d78\u68c0\u6d4b\u72b6\u6001","property":{"range":["alarm","normal"],"type":"enum"},"iconname":"icon-a_water","id":1,"type":"obj","desc":""},{"mode":"ro","code":"battery_state","name":"\u7535\u6c60\u7535\u91cf\u72b6\u6001","property":{"range":["low","middle","high"],"type":"enum"},"iconname":"icon-dianliang","id":3,"type":"obj","desc":""}]',
},

Thanks!

**Comment by iRayanKhan** [comment]
Hi there, sorry for the delayed response.

Please look at #91, as I am in the process of overhauling the plugin. It will add support on how to add unsupported devices, but currently I can't provide any direct assistance, and I am sorry for that. I will get back to you directly once the rewrite has more progress.

**Comment by chemicalsam** [comment]
> Hi there, sorry for the delayed response.
> 
> 
> 
> Please look at #91, as I am in the process of overhauling the plugin. It will add support on how to add unsupported devices, but currently I can't provide any direct assistance, and I am sorry for that. I will get back to you directly once the rewrite has more progress. 

I am definitely interested in the Valve added as I have two already

**Comment by utester123123bb** [comment]
Also interested in this .

**Comment by ElphaX** [comment]
Can you please confirm if the current Valve Accessory works for you?

**Comment by vitaliy-kozlov** [comment]
> Can you please confirm if the current Valve Accessory works for you?

Yep, works like a charm. Thanks

**Comment by jkalamarz** [comment]
Any progress on Water leak sensor?

**Comment by roee21** [comment]
Any progress on Water leak sensor?

**Comment by whatUwant** [comment]
Recently I got the same valve manipulator, but it responds only to the "close" command sent by the plugin, not the "open" command.
It works as expected in the Tuya app. 
Is your device still working with this plugin? @mrmaximas

**Comment by mrmaximas** [comment]
> Recently I got the same valve manipulator, but it responds only to the "close" command sent by the plugin, not the "open" command. It works as expected in the Tuya app. Is your device still working with this plugin? @mrmaximas

some time ago i have moved all my devices to zigbee2mqtt 🤷🏻‍♂️😂

**Comment by whatUwant** [comment]
> some time ago i have moved all my devices to zigbee2mqtt 🤷🏻‍♂️😂

I see. I assume you no longer use this device, since it's WiFi only.
