### ISSUE TITLE
Which version to use?

### ISSUE THREAD

**Issue by chinloon** [iRayanKhan/homebridge-tuya#83]
I noticed that the homebridge-tuya is version 1.0.0 but there is a later 1.0.2 version but it seems not to want to update to 1.0.2.  Is that fine?

--------
pi@raspberrypi:~ $ sudo npm list -g --depth=0
npm WARN npm npm does not support Node.js v10.19.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
/usr/local/lib
├── homebridge@0.4.53
├── homebridge-tuya@1.0.0
└── pm2@4.4.0

npm ERR! peer dep missing: bufferutil@^4.0.1, required by ws@7.2.5
npm ERR! peer dep missing: utf-8-validate@^5.0.2, required by ws@7.2.5
npm ERR! peer dep missing: bufferutil@^4.0.1, required by ws@7.2.5
npm ERR! peer dep missing: utf-8-validate@^5.0.2, required by ws@7.2.5
pi@raspberrypi:~ $ sudo npm outdated -g
npm WARN npm npm does not support Node.js v10.19.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
Package          Current  Wanted  Latest  Location
homebridge        0.4.53  0.4.53   1.0.4
homebridge-tuya    1.0.0   1.0.2   1.0.0

**Comment by iRayanKhan** [comment]
Hi there, sorry for the delayed response.

Please look at #91 for more info. I know I kinda ghosted when it comes to info about the sensors, and I am now back to working on the plugin as school is over. I have a fix in the RC branch and will provide more instructions later in the week with how to fix these issues. It seems like you should upgrade your node version.

**Comment by iRayanKhan** [comment]
Closing: Inactive thread, plugin updated.
