### ISSUE TITLE
LED Strip

### ISSUE THREAD

**Issue by DavidWhicker** [iRayanKhan/homebridge-tuya#86]
Hello

Is there going to be support for LED strip with colour? I cannot get mine to work at all.

**Comment by DavidWhicker** [comment]
Further to above. I have this working but it doesn't get the correct state on startup. the light is on but the tile is off. if I turn it on and off then it works. But won't stay synced

**Comment by tonysprenk** [comment]
What do you mean by wont stay synced? Like when the power is cut off?

**Comment by tonysprenk** [comment]
Maybe [this](https://github.com/RavenSystem/esp-homekit-devices/wiki/Accessory-Configuration#Initial-State) can help.

**Comment by DavidWhicker** [comment]
Hi

I actual managed to fix this issue. It was the power "dpPower" using a different identifier. Corrected that and it worked. 

However I do have an issue that if I try and change the colour on the home app nothing happens and then the lights become unresponsive until a forced restart

**Comment by iRayanKhan** [comment]
It may depend on the colour code formatting or style the manufacturer uses. Try different types in the config.

**Comment by Faisalthe01** [comment]
> Hi
> 
> I actual managed to fix this issue. It was the power "dpPower" using a different identifier. Corrected that and it worked.
> 
> However I do have an issue that if I try and change the colour on the home app nothing happens and then the lights become unresponsive until a forced restart

Hey mate, how did you correct the identifier? mine is using True and False too and causing the same issue. and is your Brightness working?

**Comment by DavidWhicker** [comment]
No I gave up and went Philips hue

**Comment by Faisalthe01** [comment]
> No I gave up and went Philips hue
> […](#)

How did you correct the identifier?

**Comment by DavidWhicker** [comment]
I didn’t use the product at all. I sent back and brought Philips hue which is native HomeKit

**Comment by iRayanKhan** [comment]
You can try to use the Tuya-Web plugin, as it has better support for lights.
