### ISSUE TITLE
Nedis SmartLife Air Conditioner WIFIACMB1WT12

### ISSUE THREAD

**Issue by DJay-X** [iRayanKhan/homebridge-tuya#87]
@iRayanKhan Any chance or interest to integrate Nedis SmartLife Air Conditioner WIFIACMB1WT12 ?
https://nedis.com/en-us/product/smart-living/smart-home/automation/550718437/smartlife-air-conditioner-12000-btu-up-to-75-m3-wi-fi-android-ios-energy-class-a

![WIFIACMB1WT12_P67-removebg-preview](https://user-images.githubusercontent.com/3874239/82691197-d0f79700-9c5d-11ea-88ad-0a2485753dc8.png)

Thanks for your time and work sharing with the community. 🙏

**Comment by iRayanKhan** [comment]
Thanks for the kind words, currently working on a plugin overhaul, and afterwords, there will hopefully be a better way to add accessories.

**Comment by PBX2020** [comment]
Hi @DJay-X this does work albeit limited - I've got the exact same air conditioner (though different brand 'Famgizmo' its physically and spec wise the exact same like a lot of the cheaper smart electronics are just rebrands)

You'll need your id and key ofc (google is your friend here) my config is below - the swing functionality and fan speed doesn't work, and the status will show off as soon as you exit the Home App/CC widget after turning on, but you can turn it on and off, control the temp and see the current temperature of the room the unit is in. There's also no way to switch modes from AC to Fan only or Dry.

```
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "AC",
                    "type": "AirConditioner",
                    "manufacturer": "Famgizmo",
                    "model": "KAPRA14WFGA",
                    "id": "YOURIDHERE",
                    "key": "YOURKEYHERE",
                    "noCool": false,
                    "noHeat": true,
                    "cmdCool": "COOL",
                    "cmdHeat": "HEAT",
                    "noSwing": true,
                    "minTemperature": 16,
                    "maxTemperature": 31,
                    "minTemperatureSteps": 1
                }
```

I'm going to poke around as per some notes on Discord as to why lots of the functionality doesn't work and try it getting working, but only locally until @iRayanKhan is done with his work on the overhaul before exploring how it will work there - btw looking forward to the beta, great work on all this!

**Comment by DJay-X** [comment]
Thanks to you both. Can't wait to see more of your work @iRayanKhan 
And @PBX2020 what a great hint. Thanks for the config also.
I receive my AC hopefully in the next 2 weeks. Ordered already 2 weeks ago. 
And I will of course immediately give it a try with with the plugin and the suitable settings.
I hope I can come back to you if I struggle. 
Thanks again. 🤗

**Comment by DJay-X** [comment]
Unfortunately the AC with Smart Life connection was out of stock. :( And because of the heat is starting I now bought the same model without WIFI. So unfortunately I will close my ticket. Thanks anyway. All the best to you guys. 👍
