### ISSUE TITLE
Room's to Default

### ISSUE THREAD

**Issue by bliestek** [iRayanKhan/homebridge-tuya#89]
I have discovered an issue where all devices served by this plugin automatically change back to the 'default' room after reboot of the homebridge device. All other plugins are fine. Tested this on 2 different homebridges and experiences same results.

**Comment by iRayanKhan** [comment]
What kind of devices are you using with the plugin? I haven't seen this issue reported yet before, so do you mind also stating your environment?

**Comment by iRayanKhan** [comment]
Closing: Inactive.
