### ISSUE TITLE
New Devices Request

### ISSUE THREAD

**Issue by JDrizz** [iRayanKhan/homebridge-tuya#90]
Hi team

I have a request to add some new devices. I purchased a Kogan WIFI Garage Door Opener and tried using the Garage Door code from this plugin and while it did show up in Homekit it didn't actually control the garage door. I believe the one used in this plugin might be different to the one from Kogan (but they are both Tuya products) https://www.kogan.com/au/buy/kogan-smarterhome-wireless-garage-door-opener/ I have attached the code from Burn Suite, hopefully it is what you need. 
[Garage.Door.Opener.copy.docx](https://github.com/iRayanKhan/homebridge-tuya/files/4714762/Garage.Door.Opener.copy.docx)

My other request was for the Kogan Robot Vacuum I have. I see in Homebridge it finds the device but says it hasn't be setup. I found a Eufy vacuum plugin (Eufy is apart of Tuya I believe) which did work and add the vacuum to HomeKit the only issue is it kept reconnecting. The vacuum I have is https://www.kogan.com/au/buy/kogan-smarterhome-lx10-robot-vacuum-mopping-function/ I have a log for this but it is pretty long and I I don't know how to copy it correctly from Burn Suite.

Lastly I have an Inkbird Wifi Thermostat which I would like to control. Again it uses the Tuya chip and I have the Burn Suite info (attached but looks messy) a link to the thermostat is here. I used the simple thermostat code and I did get the thermostat to show up but it keeps showing no response on Homekit. I can click the thermostat on and off but that's about it. Not sure if it has anything to do with the settings. https://www.ink-bird.com/products-temp-controller-itc308wifi.html
[Inkbird.docx](https://github.com/iRayanKhan/homebridge-tuya/files/4714764/Inkbird.docx)

Any assistance would be fantastic :)

**Comment by iRayanKhan** [comment]
Hi there, sorry for the delayed response.

Please look at #91 as currently I am in the works of a plugin overhaul that should make it easier to add unsupported devices. I am sorry that I can't provide direct assistance at the moment, but will get back to you soon!

Stay safe!

**Comment by spadival** [comment]
While we are waiting for V2, here's the details on [Kogan Smart Blinds Driver](https://www.kogan.com/au/buy/kogan-smarterhome-smart-blinds-driver/)
[Kogan Smart Blinds Driver.docx](https://github.com/iRayanKhan/homebridge-tuya/files/4816060/Kogan.Smart.Blinds.Driver.docx)

BTW, FYI - I used the anyproxy method to get the device details.

https://gist.github.com/aceslick911/0cac96ab122fa9c6cd9ca18a696ea961

**Comment by spadival** [comment]
I have managed to get both the Kogan WIFI Garage Door Opener and Kogan smart blinds driver working.

[](https://github.com/spadival/homebridge-tuya/blob/master/lib/GarageDoorAccessory.js
)
If you want to try it (at your own risk) while this plugin is updated, you will have to update the plugin with the following terminal command. Terminal is available in Homebridge Config UI X

`sudo npm install -g git+https://github.com/spadival/homebridge-tuya.git`

**Comment by iRayanKhan** [comment]
Hey @spadival it appears that this code works for some people. I will be sure to merge your code in and give credit.
Please await the new V2 beta seed.

If anyone has anymore questions please ping me and re-open this issue.

**Comment by davidh2075** [comment]
Hello @iRayanKhan and @spadival, thank you both for the help above for getting a Kogan garage door opener working.

After I had my door working with @spadival's code, I attempted to merge back in the generic garage door opener code and use the name/value pair `"manufacturer": "Kogan"` to select the Kogan-specific behaviour. I have only a Kogan opener, so haven't been able to test the merged code. It still works with the Kogan opener.

If anyone has another opener and wants to try it, you can find my mods at [GarageDoorAccessory.js](https://github.com/davidh2075/homebridge-tuya/blob/master/lib/GarageDoorAccessory.js). I added an additional parameter, debug, to the config to toggle debug messages to the log. Much of the code I changed and added is related to the logging I used to help me understand the TuyAPI accessory interaction with the door. My config for the Kogan opener is:

```javascript
        {
            "name": "Garage Door",
            "type": "GarageDoor",
            "manufacturer": "Kogan",
            "model": "SmarterHome Wireless Garage Door Opener",
            "id": "0123456789abcdef01234",
            "key": "fedbca9876543210",
            "dpAction": 101,
            "dpStatus": 102,
            "flipState": false,
            "debug": false
        }
```

and you could use something like this for a generic opener:

```javascript
        {
            "name": "Garage Door",
            "type": "GarageDoor",
            "manufacturer": "Some Manufacturer",
            "model": "Some Model",
            "id": "0123456789abcdef01234",
            "key": "fedbca9876543210",
            "flipState": false,
            "debug": false
        }
```

If you set `"debug": true`, you will see debug messages in the log that start with `[TuyaAccessory] Kogan GarageDoor` for a Kogan opener or `[TuyaAccessory] GarageDoor` if you don't set the manufacturer value, i.e. use the generic door opener code. More correctly, if you set `"manufacturer": "Some Manufacturer"`, the log messages will start with `[TuyaAccessory] Some Manufacturer GarageDoor`.

I could have included the garage door name in the log messages, too, for those folk with multiple doors. Mine is a long single door, so it wasn't necessary for me.

**Comment by davidh2075** [comment]
Hello @iRayanKhan. With a lot of help from @Faisalthe01 on #108, I managed to get a generic Tuya garage door working with my modified GarageDoorAccessory.js. Learnt more about homebridge-tuya in the process, too. Would you be able to incorporate the changes in [GarageDoorAccessory.js](https://github.com/davidh2075/homebridge-tuya/blob/master/lib/GarageDoorAccessory.js) into your next release?
I'm happy to do a PR myself and add it to homebridge-tuya if you decide the changes are OK, but I don't know where you're at with v2 and I didn't want to mess up anything.

**Comment by violentlion** [comment]
> I have managed to get both the Kogan WIFI Garage Door Opener and Kogan Smart Blinds driver working in my home.
> 
> [GarageDoorAccessory.js](https://github.com/spadival/homebridge-tuya/blob/master/lib/GarageDoorAccessory.js) and [SimpleBlindsAccessory.js](https://github.com/spadival/homebridge-tuya/blob/master/lib/SimpleBlindsAccessory.js)
> 
> If you want to try it (at your own risk) while this plugin is being updated, you will have to update the plugin with the following terminal command. Terminal is available in Homebridge Config UI X
> 
> `sudo npm install -g git+https://github.com/spadival/homebridge-tuya.git`

@spadival I can't seem to install your plugin using the above link. Getting a ENOENT error. Is your plugin still available to install?

**Comment by Faisalthe01** [comment]
> > I have managed to get both the Kogan WIFI Garage Door Opener and Kogan Smart Blinds driver working in my home.
> > [GarageDoorAccessory.js](https://github.com/spadival/homebridge-tuya/blob/master/lib/GarageDoorAccessory.js) and [SimpleBlindsAccessory.js](https://github.com/spadival/homebridge-tuya/blob/master/lib/SimpleBlindsAccessory.js)
> > If you want to try it (at your own risk) while this plugin is being updated, you will have to update the plugin with the following terminal command. Terminal is available in Homebridge Config UI X
> > `sudo npm install -g git+https://github.com/spadival/homebridge-tuya.git`
> 
> @spadival I can't seem to install your plugin using the above link. Getting a ENOENT error. Is your plugin still available to install?

@iRayanKhan already added those files into v2.0 beta 3 of this plugin

**Comment by violentlion** [comment]
@spadival I have managed to get it working now. I've just replaced the SimpleBlindsAccessory.js script with yours and everything is working perfectly now.

Thanks
