### ISSUE TITLE
Please read before opening issues. 

### ISSUE THREAD

**Issue by iRayanKhan** [iRayanKhan/homebridge-tuya#91]
Hello everyone,

I have been silent for a month due to some personal issues regarding the current pandemic. I hope everyone is safe.

I have bene in the process of working on a plugin overhaul. I currently put some of the tasks that are being worked on in the Projects tab of the repo. They are in To-Do atm, but will be updated as more progress continues.

I see some common things in the issues section of adding device support. I will be making it way easier and providing documentation on how to do this your self so that way it takes less time and anyone can do without having to wait on me.

Currently there is no set-in-stone eta. I am working on mainly some Swift projects, as this is a hobby. I am planning for there to be a beta in 7-10 days. I would prefer to keep it a public beta, so more users can test, but more details on that soon. I will be replying to every issue once the first beta comes out as that is currently the focus. 

Thank you for understanding,
and stay safe.

**Comment by MikeDProducer** [comment]
Thank you, friend. I hope you are doing well during this crazy time.

**Comment by iRayanKhan** [comment]
Thanks for sticking around Mike! Hope you are doing well too.

Just to update everyone, I have added a new branch called RC.

Currently the only notable difference is that the readME has been overhauled, and #65 has been merged. I would like some feedback on the new readME as it is the face of the plugin essentially. 

Check out this [link](https://github.com/iRayanKhan/homebridge-tuya/projects/1) to see the planned changes, and status. It is the best way to view an "eta" or grab what you need from a beta if  a certain feature is done.



# Note to beta users

If you have used beta version of my other plugins, this plugin, or are keen on trying a beta read this:


Currently the only code changes to the RC are dependency fixes, schema support, readME overhaul, and such. 

Currently you can Git Clone the branch, I will be making a tutorial on how to do this, and later publishing the beta's to NPM. 


# Note about this issue and discussion

Currently I am going to use this issue as discussion for beta update feedback, and suggestions. A more feature heavy beta is in the works.

**Comment by dhutchison** [comment]
Hey @iRayanKhan, is the plugin overhaul something you are looking for assistance with or something you want to tackle on your own?

If you do want assistance, could you create some issues with details of areas (and your vision) that people could pick up?

**Comment by iRayanKhan** [comment]
Hey @dhutchison, do you have discord or an email I contact you at?

**Comment by dhutchison** [comment]
Just signed up to discord as DevWithImagination#3572 or you can email me at david@devwithimagination.com. 

Just about to head for a sleep though so don't expect an instant reply 🙂
