### ISSUE TITLE
Configurable dps mapping for Air Conditioner

### ISSUE THREAD

**Issue by RaymondMouthaan** [iRayanKhan/homebridge-tuya#92]
Hello @iRayanKhan,

Thanks for this awesome hb plugin!

I like to request configurable dps mapping for Air Conditioning, since my air conditioner has a different dps mapping as the plug in uses. 

In my case

```
{
  dps: {
    '1': false,
    '2': 'auto',
    '3': 'mid',
    '4': 0,
    '5': 21,
    '6': false,
    '7': false,
    '8': 23,
    '9': 0,
    '12': true,
    '13': false,
    '14': false,
    '15': 0
  }
}
```

where:
- dps 1 : power on | off
- dps 2 : Operation Mode auto | fan | cool | dry
- dps 3 : Fan Speed low | mid | high
- dps 4 : Timer 0 ... 24 [minutes]
- dps 5 : Temperature
- dps 6 : Night Mode on | off
- dps 7 : unknown
- dps 8 : Ambient Temperature 
- dps 9, 12 ~ 15 : unknown

Currently only power on/off and operation mode cool works. For setting the temperature I get the following error:

```
[TuyaLan] Ready to handle Duux Blizard (AirConditioner:3.3) with signature {"1":true,"2":"cool","3":"low","4":0,"5":23,"6":false,"7":false,"8":19,"9":0,"12":true,"13":false,"14":false,"15":0}

[TuyaAccessory] Socket had a problem and will reconnect to Duux Blizard (ECONNRESET)
[TuyaAccessory] Sending first query to Duux Blizard (3.3)
[TuyaAccessory] Heard back from Duux Blizard with command  10
```

Thanks,
Raymond

**Comment by iRayanKhan** [comment]
Hey, I am currently working on an easier way to config new devices. I will get back to you soon once a in stainable beta is ready.

**Comment by RaymondMouthaan** [comment]
> Hey, I am currently working on an easier way to config new devices. I will get back to you soon once a in stainable beta is ready.

Great! Looking forward to that 👍
