### ISSUE TITLE
ID & Key not working

### ISSUE THREAD

**Issue by jamie-2bit** [iRayanKhan/homebridge-tuya#94]
**Checklist**
- [x] I have read the common issues wiki page
- [x] I have checked to make sure the plugin is up to date

**Describe the bug**
Looks like the uComen Home app is no longer working to get the ID and Key either.

**To Reproduce**
Follow these instructions: https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions

**Expected behavior**
QR code scanned, certs installed. All knowen compatable apps launched including uComen Home. 

**Screenshots**

Getting the following errors:
------------------------------------------------------------
Proxy IP: 192.168.1.2
Proxy Port: 8080

Intercepted certificate request
Error: EPIPE { Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
Error: EPIPE { Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
------------------------------------------------------------

**Environment (please complete the following information):**
 - OS: 
-  iOS version:
-  Homehubs: 
 - Node Version: 
 - Plugin Version: Latest NPM
-  Accessory Type

**Additional context**

**Comment by iRayanKhan** [comment]
Hi @jamie-2bit,

[This](https://github.com/iRayanKhan/homebridge-tuya/wiki/Common-Problems#cant-get-device-keys)  section of the common issues wiki shows info about this issue. We have an existing issue about this topic #73. 
I have a method that is working for this, and will publish it within a week, so please stay tuned! 

Closed for duplicate.

**Comment by jamie-2bit** [comment]
Amazing. Thank you! 

>
