### ISSUE TITLE
plugin does not see the device

### ISSUE THREAD

**Issue by motogon** [iRayanKhan/homebridge-tuya#96]
**Checklist**
- [x ] I have read the common issues wiki page
- [x ] I have checked to make sure the plugin is up to date

**Describe the bug**
[TuyaAccessory] Socket had a problem and will reconnect to room1 (ECONNRESET)
[TuyaAccessory] Sending first query to room1 (3.1)
[TuyaDiscovery] UDP from 192.168.1.64:6667 0x000055aa...0x0000aa55

**To Reproduce**

Smart wifi Dimmer on another ip network, route added and available .

My config:

{
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "room1",
                    "type": "SimpleDimmer",
                    "manufacturer": "Cotify",
                    "model": "Smart Dimmer Switch",
                    "id": "48002207bxxxxxxxxxxxxx",
                    "key": "6ac6xxxxxxxxxx",
                    "ip": "192.168.3.240"
                }
            ]
        }

ping 192.168.3.240
PING 192.168.3.240 (192.168.3.240) 56(84) bytes of data.
64 bytes from 192.168.3.240: icmp_seq=1 ttl=253 time=174 ms
64 bytes from 192.168.3.240: icmp_seq=2 ttl=253 time=92.5 ms
64 bytes from 192.168.3.240: icmp_seq=3 ttl=253 time=318 ms
64 bytes from 192.168.3.240: icmp_seq=4 ttl=253 time=52.3 ms

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: 
-  iOS version:
-  Homehubs: 
 - Node Version: 
 - Plugin Version:
-  Accessory Type

**Additional context**

**Comment by iRayanKhan** [comment]
Are you able to provide you device's schema?

**Comment by motogon** [comment]
country house: tuye devices <- l2tp tunnel -> city apartment: server with homebridge

**Comment by iRayanKhan** [comment]
That's not the devices schema, its for the devices credentials. I would suggest using the web plugin if it supports dimmers, or the new update for the plugin. Please re-open if you are still facing this issue.
