### ISSUE TITLE
Colour issues

### ISSUE THREAD

**Issue by SparkyRedcar** [iRayanKhan/homebridge-tuya#97]
**Describe the bug**
RGB Lightbulbs work fine for power on and brightness adjustments however the colour selection is way off. For example I’ll select red on the Home app and the bulb changes to blue, the colour it changes to when switches to red sometimes changes.

Seems to happen with all colours.

**To Reproduce**
Change light to Red

**Expected behavior**
Light switches to Red

**Screenshots**
![image](https://user-images.githubusercontent.com/66794935/84800291-81ef1880-aff5-11ea-9efa-dba1f0d827bc.png)

![image](https://user-images.githubusercontent.com/66794935/84800309-87e4f980-aff5-11ea-8113-9cd069e980cf.jpeg)

**Environment (please complete the following information):**
 - OS: 
-  iOS version: 13
-  Homehubs: Homebridge 
 - Node Version: 12.18.0
 - Plugin Version: 0.3.3
-  Accessory Type: Bulb

**Additional context**
Thanks

**Comment by iRayanKhan** [comment]
Are you able to get your devices schema by chance?

**Comment by SparkyRedcar** [comment]
Hi. Thanks for your reply mate. Appreciate it.

It’s a Lohas Smart WiFi Bulb. I have attached a picture, hopefully this can help.

![image](https://user-images.githubusercontent.com/66794935/85227254-3c0ac980-b3d4-11ea-879b-4651caf3f321.jpeg)

**Comment by SparkyRedcar** [comment]
Hi, just wondered if there is any solution to this or anything I can do for a work around. Everything else works, on/off, brightness etc.

Just colours don't match, just asked for blue and it's gone like pink.

**Comment by iRayanKhan** [comment]
Hi, if you can get your devices schema which you need to look at the Wiki part for (unless I forgot about adding that), it will give all your device details, and get the exact colour definitions of your device.

**Comment by ElphaX** [comment]
Closed until further response from user with schema
