### ISSUE TITLE
New Device: Smart Switch

### ISSUE THREAD

**Issue by sebcastrov** [iRayanKhan/homebridge-tuya#98]
Hi

I have three of these wifi switches

![](https://user-images.githubusercontent.com/52010078/67991377-c91bcb00-fc17-11e9-84eb-c0fc681c7004.png)

**Partial Support?**
currently are not working under this config

{
"name": "Portátil",
"type": "Outlet",
"manufacturer": "SmartLife",
"model": "SCW NF101",
"id": "xx",
"key": "zz"

}

**Additional context**
raised the case in previous Tuya-lan https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/112 with more context of testing but never worked

thanks in advance!!!!

**Comment by ElphaX** [comment]
Looks like you haven't specified the dpPower datapoint in your config. Please re-open this issue if relevant.
